`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:38 CST (May 15 2023 01:04:38 UTC)

module Filter_Add_12Ux9U_13U_1(in2, in1, out1);
  input [11:0] in2;
  input [8:0] in1;
  output [12:0] out1;
  wire [11:0] in2;
  wire [8:0] in1;
  wire [12:0] out1;
  wire add_23_2_n_2, add_23_2_n_3, add_23_2_n_11, add_23_2_n_12,
       add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_54,
       add_23_2_n_55, add_23_2_n_56, add_23_2_n_57, add_23_2_n_58;
  wire add_23_2_n_59, add_23_2_n_61, add_23_2_n_63, add_23_2_n_64,
       add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68;
  wire add_23_2_n_69, add_23_2_n_70, add_23_2_n_73, add_23_2_n_74,
       add_23_2_n_75, n_99, n_101, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_112;
  MXI2XL add_23_2_g263(.A (add_23_2_n_11), .B (in2[10]), .S0
       (add_23_2_n_74), .Y (out1[10]));
  MXI2XL add_23_2_g264(.A (add_23_2_n_12), .B (in2[9]), .S0
       (add_23_2_n_75), .Y (out1[9]));
  OAI21X1 add_23_2_g265(.A0 (add_23_2_n_17), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_32), .Y (add_23_2_n_75));
  OAI21X1 add_23_2_g266(.A0 (add_23_2_n_41), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_36), .Y (add_23_2_n_74));
  NOR2BX1 add_23_2_g267(.AN (add_23_2_n_56), .B (add_23_2_n_70), .Y
       (add_23_2_n_73));
  MXI2XL add_23_2_g268(.A (add_23_2_n_44), .B (add_23_2_n_43), .S0
       (n_101), .Y (out1[8]));
  NOR2X2 add_23_2_g273(.A (add_23_2_n_55), .B (add_23_2_n_69), .Y
       (add_23_2_n_70));
  NOR2X2 add_23_2_g274(.A (add_23_2_n_58), .B (add_23_2_n_65), .Y
       (add_23_2_n_69));
  AOI21X1 add_23_2_g275(.A0 (add_23_2_n_37), .A1 (n_107), .B0
       (add_23_2_n_49), .Y (add_23_2_n_68));
  OAI21X1 add_23_2_g276(.A0 (add_23_2_n_18), .A1 (n_108), .B0
       (add_23_2_n_29), .Y (add_23_2_n_67));
  OAI21X1 add_23_2_g279(.A0 (add_23_2_n_51), .A1 (n_109), .B0
       (add_23_2_n_59), .Y (add_23_2_n_66));
  NOR2X2 add_23_2_g280(.A (add_23_2_n_54), .B (add_23_2_n_63), .Y
       (add_23_2_n_65));
  OAI21X1 add_23_2_g281(.A0 (add_23_2_n_16), .A1 (n_105), .B0
       (add_23_2_n_19), .Y (add_23_2_n_64));
  NOR2X2 add_23_2_g284(.A (add_23_2_n_48), .B (add_23_2_n_61), .Y
       (add_23_2_n_63));
  NOR2X2 add_23_2_g285(.A (add_23_2_n_3), .B (n_106), .Y
       (add_23_2_n_61));
  AOI21X1 add_23_2_g287(.A0 (add_23_2_n_27), .A1 (add_23_2_n_49), .B0
       (add_23_2_n_21), .Y (add_23_2_n_59));
  OAI2BB1X1 add_23_2_g288(.A0N (add_23_2_n_47), .A1N (add_23_2_n_49),
       .B0 (add_23_2_n_50), .Y (add_23_2_n_58));
  OAI21X4 add_23_2_g289(.A0 (add_23_2_n_22), .A1 (add_23_2_n_35), .B0
       (add_23_2_n_23), .Y (add_23_2_n_57));
  OR2XL add_23_2_g292(.A (add_23_2_n_11), .B (add_23_2_n_36), .Y
       (add_23_2_n_56));
  OR2XL add_23_2_g293(.A (add_23_2_n_11), .B (add_23_2_n_41), .Y
       (add_23_2_n_55));
  NAND2X1 add_23_2_g294(.A (add_23_2_n_47), .B (add_23_2_n_37), .Y
       (add_23_2_n_54));
  NAND2X1 add_23_2_g297(.A (add_23_2_n_27), .B (add_23_2_n_37), .Y
       (add_23_2_n_51));
  AOI2BB1X1 add_23_2_g298(.A0N (add_23_2_n_20), .A1N (add_23_2_n_28),
       .B0 (add_23_2_n_34), .Y (add_23_2_n_50));
  OAI21X2 add_23_2_g299(.A0 (add_23_2_n_29), .A1 (add_23_2_n_31), .B0
       (add_23_2_n_25), .Y (add_23_2_n_49));
  OAI21X1 add_23_2_g300(.A0 (add_23_2_n_19), .A1 (add_23_2_n_30), .B0
       (add_23_2_n_33), .Y (add_23_2_n_48));
  INVX1 add_23_2_g303(.A (add_23_2_n_43), .Y (add_23_2_n_44));
  NOR2X1 add_23_2_g305(.A (add_23_2_n_28), .B (add_23_2_n_26), .Y
       (add_23_2_n_47));
  NAND2X1 add_23_2_g307(.A (add_23_2_n_19), .B (add_23_2_n_15), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g308(.A (add_23_2_n_34), .B (add_23_2_n_28), .Y
       (add_23_2_n_45));
  NAND2BX1 add_23_2_g309(.AN (add_23_2_n_17), .B (add_23_2_n_32), .Y
       (add_23_2_n_43));
  NOR2BX1 add_23_2_g310(.AN (add_23_2_n_25), .B (add_23_2_n_31), .Y
       (add_23_2_n_42));
  OR2XL add_23_2_g311(.A (add_23_2_n_12), .B (add_23_2_n_17), .Y
       (add_23_2_n_41));
  NAND2BX1 add_23_2_g317(.AN (add_23_2_n_18), .B (add_23_2_n_29), .Y
       (add_23_2_n_40));
  NOR2BX1 add_23_2_g318(.AN (add_23_2_n_33), .B (n_112), .Y
       (add_23_2_n_39));
  NAND2X1 add_23_2_g319(.A (add_23_2_n_20), .B (add_23_2_n_27), .Y
       (add_23_2_n_38));
  NOR2X1 add_23_2_g320(.A (add_23_2_n_31), .B (add_23_2_n_18), .Y
       (add_23_2_n_37));
  OR2XL add_23_2_g321(.A (add_23_2_n_12), .B (add_23_2_n_32), .Y
       (add_23_2_n_36));
  INVX1 add_23_2_g323(.A (add_23_2_n_26), .Y (add_23_2_n_27));
  NOR2X4 add_23_2_g324(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_35));
  AND2X1 add_23_2_g325(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_34));
  NAND2X1 add_23_2_g326(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_33));
  NAND2X1 add_23_2_g327(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_32));
  NOR2X2 add_23_2_g328(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_31));
  NOR2X6 add_23_2_g329(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_30));
  NAND2X2 add_23_2_g330(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_29));
  NOR2X1 add_23_2_g331(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_28));
  NOR2X1 add_23_2_g332(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_26));
  INVX1 add_23_2_g334(.A (add_23_2_n_20), .Y (add_23_2_n_21));
  INVX1 add_23_2_g335(.A (add_23_2_n_15), .Y (add_23_2_n_16));
  NAND2X1 add_23_2_g336(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_25));
  NAND2X1 add_23_2_g337(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_24));
  NAND2X2 add_23_2_g338(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_23));
  NAND2X8 add_23_2_g339(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g340(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_20));
  NAND2X2 add_23_2_g341(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g342(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_18));
  NOR2X1 add_23_2_g343(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_17));
  NAND2X2 add_23_2_g344(.A (add_23_2_n_13), .B (add_23_2_n_14), .Y
       (add_23_2_n_15));
  CLKINVX2 add_23_2_g345(.A (in1[2]), .Y (add_23_2_n_14));
  CLKINVX2 add_23_2_g346(.A (in2[2]), .Y (add_23_2_n_13));
  INVX1 add_23_2_g349(.A (in2[9]), .Y (add_23_2_n_12));
  INVX1 add_23_2_g350(.A (in2[10]), .Y (add_23_2_n_11));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_22), .B (add_23_2_n_2), .Y
       (out1[1]));
  XNOR2X1 add_23_2_g351(.A (add_23_2_n_46), .B (n_104), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g352(.A (add_23_2_n_45), .B (add_23_2_n_66), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g353(.A (add_23_2_n_42), .B (add_23_2_n_67), .Y
       (out1[5]));
  XNOR2XL add_23_2_g354(.A (add_23_2_n_40), .B (n_107), .Y (out1[4]));
  CLKXOR2X1 add_23_2_g355(.A (add_23_2_n_39), .B (add_23_2_n_64), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g356(.A (add_23_2_n_38), .B (add_23_2_n_68), .Y
       (out1[6]));
  NAND2BX1 add_23_2_g357(.AN (add_23_2_n_30), .B (add_23_2_n_15), .Y
       (add_23_2_n_3));
  NOR2BX1 add_23_2_g358(.AN (add_23_2_n_23), .B (add_23_2_n_35), .Y
       (add_23_2_n_2));
  XNOR2XL add_23_2_g359(.A (in2[11]), .B (add_23_2_n_73), .Y
       (out1[11]));
  CLKXOR2X1 add_23_2_g360(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NOR2X4 g2(.A (n_99), .B (add_23_2_n_24), .Y (out1[12]));
  OA21X1 g3(.A0 (add_23_2_n_41), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_36), .Y (n_99));
  BUFX2 fopt(.A (add_23_2_n_69), .Y (n_101));
  INVXL fopt361(.A (n_105), .Y (n_104));
  BUFX3 fopt362(.A (n_106), .Y (n_105));
  CLKINVX3 fopt363(.A (add_23_2_n_57), .Y (n_106));
  CLKINVX1 fopt364(.A (n_107), .Y (n_108));
  CLKINVX1 fopt365(.A (n_107), .Y (n_109));
  CLKINVX1 fopt366(.A (add_23_2_n_63), .Y (n_107));
  BUFX2 fopt367(.A (add_23_2_n_30), .Y (n_112));
endmodule


