`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:35:49 CST (May 15 2023 01:35:49 UTC)

module Filter_Sub_12Ux7U_12U_1(in2, in1, out1);
  input [11:0] in2;
  input [6:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [6:0] in1;
  wire [11:0] out1;
  wire n_88, n_90, n_91, n_93, n_94, sub_23_2_n_0, sub_23_2_n_1,
       sub_23_2_n_2;
  wire sub_23_2_n_3, sub_23_2_n_4, sub_23_2_n_5, sub_23_2_n_6,
       sub_23_2_n_7, sub_23_2_n_9, sub_23_2_n_13, sub_23_2_n_14;
  wire sub_23_2_n_15, sub_23_2_n_17, sub_23_2_n_18, sub_23_2_n_19,
       sub_23_2_n_20, sub_23_2_n_21, sub_23_2_n_22, sub_23_2_n_23;
  wire sub_23_2_n_24, sub_23_2_n_25, sub_23_2_n_26, sub_23_2_n_27,
       sub_23_2_n_28, sub_23_2_n_29, sub_23_2_n_30, sub_23_2_n_32;
  wire sub_23_2_n_33, sub_23_2_n_34, sub_23_2_n_35, sub_23_2_n_36,
       sub_23_2_n_37, sub_23_2_n_38, sub_23_2_n_39, sub_23_2_n_40;
  wire sub_23_2_n_41, sub_23_2_n_42, sub_23_2_n_43, sub_23_2_n_44,
       sub_23_2_n_45, sub_23_2_n_46, sub_23_2_n_47, sub_23_2_n_48;
  wire sub_23_2_n_50, sub_23_2_n_51, sub_23_2_n_52, sub_23_2_n_53,
       sub_23_2_n_54, sub_23_2_n_55, sub_23_2_n_56, sub_23_2_n_57;
  wire sub_23_2_n_58, sub_23_2_n_59, sub_23_2_n_60, sub_23_2_n_61;
  MXI2XL sub_23_2_g267(.A (sub_23_2_n_14), .B (in2[9]), .S0
       (sub_23_2_n_60), .Y (out1[9]));
  MXI2XL sub_23_2_g268(.A (sub_23_2_n_20), .B (in2[10]), .S0
       (sub_23_2_n_61), .Y (out1[10]));
  MXI2XL sub_23_2_g269(.A (sub_23_2_n_18), .B (in2[11]), .S0
       (sub_23_2_n_59), .Y (out1[11]));
  MXI2XL sub_23_2_g270(.A (sub_23_2_n_19), .B (in2[7]), .S0
       (sub_23_2_n_58), .Y (out1[7]));
  MXI2XL sub_23_2_g271(.A (sub_23_2_n_41), .B (sub_23_2_n_40), .S0
       (sub_23_2_n_57), .Y (out1[6]));
  MXI2XL sub_23_2_g272(.A (sub_23_2_n_34), .B (sub_23_2_n_33), .S0
       (sub_23_2_n_56), .Y (out1[5]));
  MXI2XL sub_23_2_g273(.A (sub_23_2_n_13), .B (in2[8]), .S0
       (sub_23_2_n_55), .Y (out1[8]));
  NOR3BX1 sub_23_2_g274(.AN (sub_23_2_n_24), .B (sub_23_2_n_47), .C
       (sub_23_2_n_53), .Y (sub_23_2_n_61));
  NOR3X1 sub_23_2_g275(.A (in2[8]), .B (sub_23_2_n_47), .C
       (sub_23_2_n_53), .Y (sub_23_2_n_60));
  NOR3X1 sub_23_2_g276(.A (sub_23_2_n_37), .B (sub_23_2_n_47), .C
       (sub_23_2_n_53), .Y (sub_23_2_n_59));
  NOR2X1 sub_23_2_g277(.A (sub_23_2_n_48), .B (sub_23_2_n_53), .Y
       (sub_23_2_n_58));
  NOR2X1 sub_23_2_g278(.A (n_88), .B (sub_23_2_n_9), .Y
       (sub_23_2_n_57));
  NOR2X1 sub_23_2_g279(.A (sub_23_2_n_4), .B (sub_23_2_n_54), .Y
       (sub_23_2_n_56));
  NOR2X1 sub_23_2_g280(.A (sub_23_2_n_47), .B (sub_23_2_n_53), .Y
       (sub_23_2_n_55));
  NOR2X1 sub_23_2_g284(.A (sub_23_2_n_1), .B (sub_23_2_n_51), .Y
       (sub_23_2_n_54));
  NOR2X2 sub_23_2_g285(.A (sub_23_2_n_44), .B (sub_23_2_n_51), .Y
       (sub_23_2_n_53));
  AOI21X1 sub_23_2_g286(.A0 (sub_23_2_n_27), .A1 (n_91), .B0
       (sub_23_2_n_26), .Y (sub_23_2_n_52));
  NOR2X2 sub_23_2_g288(.A (sub_23_2_n_43), .B (sub_23_2_n_50), .Y
       (sub_23_2_n_51));
  NOR2X1 sub_23_2_g289(.A (sub_23_2_n_35), .B (sub_23_2_n_46), .Y
       (sub_23_2_n_50));
  NAND2X1 sub_23_2_g291(.A (sub_23_2_n_22), .B (sub_23_2_n_45), .Y
       (sub_23_2_n_48));
  NAND2X4 sub_23_2_g292(.A (sub_23_2_n_36), .B (sub_23_2_n_45), .Y
       (sub_23_2_n_47));
  AOI21X2 sub_23_2_g293(.A0 (sub_23_2_n_29), .A1 (sub_23_2_n_23), .B0
       (sub_23_2_n_30), .Y (sub_23_2_n_46));
  NAND2X2 sub_23_2_g295(.A (sub_23_2_n_3), .B (sub_23_2_n_42), .Y
       (sub_23_2_n_45));
  NAND2X1 sub_23_2_g297(.A (sub_23_2_n_3), .B (sub_23_2_n_5), .Y
       (sub_23_2_n_44));
  OAI2BB1X1 sub_23_2_g298(.A0N (sub_23_2_n_28), .A1N (sub_23_2_n_26),
       .B0 (sub_23_2_n_0), .Y (sub_23_2_n_43));
  NAND2X2 sub_23_2_g299(.A (sub_23_2_n_25), .B (sub_23_2_n_32), .Y
       (sub_23_2_n_42));
  INVX1 sub_23_2_g300(.A (sub_23_2_n_40), .Y (sub_23_2_n_41));
  NAND2X1 sub_23_2_g303(.A (sub_23_2_n_20), .B (sub_23_2_n_24), .Y
       (sub_23_2_n_37));
  AND2XL sub_23_2_g304(.A (sub_23_2_n_19), .B (sub_23_2_n_22), .Y
       (sub_23_2_n_36));
  NAND2X1 sub_23_2_g305(.A (sub_23_2_n_28), .B (sub_23_2_n_27), .Y
       (sub_23_2_n_35));
  NAND2X1 sub_23_2_g306(.A (sub_23_2_n_3), .B (sub_23_2_n_22), .Y
       (sub_23_2_n_40));
  NAND2X1 sub_23_2_g307(.A (sub_23_2_n_28), .B (sub_23_2_n_0), .Y
       (sub_23_2_n_39));
  NOR2X1 sub_23_2_g308(.A (sub_23_2_n_1), .B (sub_23_2_n_4), .Y
       (sub_23_2_n_38));
  INVXL sub_23_2_g309(.A (sub_23_2_n_33), .Y (sub_23_2_n_34));
  NAND2X2 sub_23_2_g312(.A (sub_23_2_n_4), .B (sub_23_2_n_2), .Y
       (sub_23_2_n_32));
  MXI2XL sub_23_2_g313(.A (sub_23_2_n_15), .B (in2[0]), .S0 (in1[0]),
       .Y (out1[0]));
  NAND2X1 sub_23_2_g315(.A (sub_23_2_n_2), .B (sub_23_2_n_25), .Y
       (sub_23_2_n_33));
  NOR2X2 sub_23_2_g321(.A (sub_23_2_n_21), .B (in1[1]), .Y
       (sub_23_2_n_30));
  NAND2X2 sub_23_2_g322(.A (in1[1]), .B (sub_23_2_n_21), .Y
       (sub_23_2_n_29));
  NAND2X2 sub_23_2_g324(.A (in1[3]), .B (n_94), .Y (sub_23_2_n_28));
  NAND2X1 sub_23_2_g325(.A (in1[2]), .B (sub_23_2_n_17), .Y
       (sub_23_2_n_27));
  NOR2X1 sub_23_2_g326(.A (sub_23_2_n_17), .B (in1[2]), .Y
       (sub_23_2_n_26));
  NAND2BX1 sub_23_2_g328(.AN (in1[5]), .B (in2[5]), .Y (sub_23_2_n_25));
  NOR2X1 sub_23_2_g329(.A (in2[9]), .B (in2[8]), .Y (sub_23_2_n_24));
  NAND2X2 sub_23_2_g331(.A (in1[0]), .B (sub_23_2_n_15), .Y
       (sub_23_2_n_23));
  NAND2BX1 sub_23_2_g332(.AN (in1[6]), .B (in2[6]), .Y (sub_23_2_n_22));
  CLKINVX4 sub_23_2_g337(.A (in2[1]), .Y (sub_23_2_n_21));
  INVX1 sub_23_2_g338(.A (in2[10]), .Y (sub_23_2_n_20));
  INVX1 sub_23_2_g339(.A (in2[7]), .Y (sub_23_2_n_19));
  INVXL sub_23_2_g340(.A (in2[11]), .Y (sub_23_2_n_18));
  INVX3 sub_23_2_g341(.A (in2[2]), .Y (sub_23_2_n_17));
  INVX1 sub_23_2_g346(.A (in2[0]), .Y (sub_23_2_n_15));
  INVXL sub_23_2_g347(.A (in2[9]), .Y (sub_23_2_n_14));
  INVXL sub_23_2_g348(.A (in2[8]), .Y (sub_23_2_n_13));
  XNOR2X1 sub_23_2_g2(.A (sub_23_2_n_23), .B (sub_23_2_n_7), .Y
       (out1[1]));
  CLKXOR2X1 sub_23_2_g349(.A (sub_23_2_n_39), .B (sub_23_2_n_52), .Y
       (out1[3]));
  XNOR2XL sub_23_2_g350(.A (sub_23_2_n_38), .B (sub_23_2_n_51), .Y
       (out1[4]));
  NOR2BX1 sub_23_2_g351(.AN (sub_23_2_n_5), .B (sub_23_2_n_51), .Y
       (sub_23_2_n_9));
  CLKXOR2X1 sub_23_2_g352(.A (sub_23_2_n_6), .B (n_90), .Y (out1[2]));
  NAND2BX1 sub_23_2_g353(.AN (sub_23_2_n_30), .B (sub_23_2_n_29), .Y
       (sub_23_2_n_7));
  NAND2BX1 sub_23_2_g354(.AN (sub_23_2_n_26), .B (sub_23_2_n_27), .Y
       (sub_23_2_n_6));
  NOR2BX1 sub_23_2_g355(.AN (sub_23_2_n_2), .B (sub_23_2_n_1), .Y
       (sub_23_2_n_5));
  NOR2BX1 sub_23_2_g356(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_4));
  NAND2BX1 sub_23_2_g357(.AN (in2[6]), .B (in1[6]), .Y (sub_23_2_n_3));
  NAND2BX4 sub_23_2_g358(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_2));
  NOR2BX1 sub_23_2_g359(.AN (in1[4]), .B (in2[4]), .Y (sub_23_2_n_1));
  NAND2BX1 sub_23_2_g360(.AN (in1[3]), .B (n_93), .Y (sub_23_2_n_0));
  BUFX2 fopt(.A (sub_23_2_n_42), .Y (n_88));
  INVXL fopt361(.A (n_91), .Y (n_90));
  CLKINVX1 fopt362(.A (sub_23_2_n_46), .Y (n_91));
  BUFX2 fopt363(.A (in2[3]), .Y (n_93));
  CLKINVX3 fopt364(.A (in2[3]), .Y (n_94));
endmodule


