`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:05 CST (May 15 2023 01:04:05 UTC)

module Filter_Sub_12Ux8U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire sub_23_2_n_0, sub_23_2_n_1, sub_23_2_n_2, sub_23_2_n_3,
       sub_23_2_n_4, sub_23_2_n_5, sub_23_2_n_6, sub_23_2_n_7;
  wire sub_23_2_n_8, sub_23_2_n_9, sub_23_2_n_10, sub_23_2_n_11,
       sub_23_2_n_12, sub_23_2_n_13, sub_23_2_n_14, sub_23_2_n_16;
  wire sub_23_2_n_17, sub_23_2_n_18, sub_23_2_n_19, sub_23_2_n_20,
       sub_23_2_n_21, sub_23_2_n_22, sub_23_2_n_23, sub_23_2_n_24;
  wire sub_23_2_n_25, sub_23_2_n_26, sub_23_2_n_27, sub_23_2_n_29,
       sub_23_2_n_30, sub_23_2_n_32, sub_23_2_n_35, sub_23_2_n_36;
  wire sub_23_2_n_37, sub_23_2_n_38, sub_23_2_n_39, sub_23_2_n_42,
       sub_23_2_n_44;
  XNOR2X1 sub_23_2_g254(.A (in2[11]), .B (sub_23_2_n_44), .Y
       (out1[11]));
  XOR2XL sub_23_2_g255(.A (in2[9]), .B (sub_23_2_n_39), .Y (out1[9]));
  XNOR2X1 sub_23_2_g256(.A (sub_23_2_n_16), .B (sub_23_2_n_42), .Y
       (out1[7]));
  OAI2BB1X1 sub_23_2_g257(.A0N (in2[10]), .A1N (sub_23_2_n_38), .B0
       (sub_23_2_n_44), .Y (out1[10]));
  OR2XL sub_23_2_g258(.A (in2[10]), .B (sub_23_2_n_38), .Y
       (sub_23_2_n_44));
  AO21XL sub_23_2_g259(.A0 (in2[8]), .A1 (sub_23_2_n_35), .B0
       (sub_23_2_n_39), .Y (out1[8]));
  AOI21X1 sub_23_2_g260(.A0 (sub_23_2_n_13), .A1 (sub_23_2_n_37), .B0
       (sub_23_2_n_12), .Y (sub_23_2_n_42));
  XNOR2X1 sub_23_2_g261(.A (sub_23_2_n_21), .B (sub_23_2_n_37), .Y
       (out1[6]));
  XNOR2X1 sub_23_2_g262(.A (sub_23_2_n_19), .B (sub_23_2_n_36), .Y
       (out1[5]));
  NOR2X1 sub_23_2_g263(.A (in2[8]), .B (sub_23_2_n_35), .Y
       (sub_23_2_n_39));
  OR3XL sub_23_2_g264(.A (sub_23_2_n_35), .B (in2[9]), .C (in2[8]), .Y
       (sub_23_2_n_38));
  OAI21X1 sub_23_2_g265(.A0 (sub_23_2_n_22), .A1 (sub_23_2_n_30), .B0
       (sub_23_2_n_25), .Y (sub_23_2_n_37));
  AOI2BB1XL sub_23_2_g266(.A0N (sub_23_2_n_6), .A1N (sub_23_2_n_30),
       .B0 (sub_23_2_n_10), .Y (sub_23_2_n_36));
  OAI31X1 sub_23_2_g267(.A0 (sub_23_2_n_30), .A1 (sub_23_2_n_18), .A2
       (sub_23_2_n_22), .B0 (sub_23_2_n_27), .Y (sub_23_2_n_35));
  XNOR2X1 sub_23_2_g268(.A (sub_23_2_n_17), .B (sub_23_2_n_30), .Y
       (out1[4]));
  XNOR2X1 sub_23_2_g269(.A (sub_23_2_n_20), .B (sub_23_2_n_32), .Y
       (out1[3]));
  AOI21X1 sub_23_2_g270(.A0 (sub_23_2_n_4), .A1 (sub_23_2_n_29), .B0
       (sub_23_2_n_9), .Y (sub_23_2_n_32));
  XNOR2X1 sub_23_2_g271(.A (sub_23_2_n_23), .B (sub_23_2_n_29), .Y
       (out1[2]));
  AOI221X1 sub_23_2_g272(.A0 (sub_23_2_n_3), .A1 (sub_23_2_n_9), .B0
       (sub_23_2_n_24), .B1 (sub_23_2_n_29), .C0 (sub_23_2_n_8), .Y
       (sub_23_2_n_30));
  ADDFX1 sub_23_2_g273(.A (sub_23_2_n_2), .B (in2[1]), .CI
       (sub_23_2_n_0), .CO (sub_23_2_n_29), .S (out1[1]));
  AOI211XL sub_23_2_g274(.A0 (sub_23_2_n_11), .A1 (sub_23_2_n_12), .B0
       (sub_23_2_n_26), .C0 (sub_23_2_n_7), .Y (sub_23_2_n_27));
  NOR2XL sub_23_2_g275(.A (sub_23_2_n_18), .B (sub_23_2_n_25), .Y
       (sub_23_2_n_26));
  AOI21X1 sub_23_2_g276(.A0 (sub_23_2_n_5), .A1 (sub_23_2_n_10), .B0
       (sub_23_2_n_14), .Y (sub_23_2_n_25));
  AND2X1 sub_23_2_g277(.A (sub_23_2_n_3), .B (sub_23_2_n_4), .Y
       (sub_23_2_n_24));
  NAND2BX1 sub_23_2_g278(.AN (sub_23_2_n_9), .B (sub_23_2_n_4), .Y
       (sub_23_2_n_23));
  NAND2BX1 sub_23_2_g279(.AN (sub_23_2_n_6), .B (sub_23_2_n_5), .Y
       (sub_23_2_n_22));
  NAND2BX1 sub_23_2_g280(.AN (sub_23_2_n_12), .B (sub_23_2_n_13), .Y
       (sub_23_2_n_21));
  NOR2BX1 sub_23_2_g281(.AN (sub_23_2_n_3), .B (sub_23_2_n_8), .Y
       (sub_23_2_n_20));
  NOR2BX1 sub_23_2_g282(.AN (sub_23_2_n_5), .B (sub_23_2_n_14), .Y
       (sub_23_2_n_19));
  NAND2X1 sub_23_2_g283(.A (sub_23_2_n_11), .B (sub_23_2_n_13), .Y
       (sub_23_2_n_18));
  NOR2X1 sub_23_2_g284(.A (sub_23_2_n_6), .B (sub_23_2_n_10), .Y
       (sub_23_2_n_17));
  NOR2BX1 sub_23_2_g285(.AN (sub_23_2_n_11), .B (sub_23_2_n_7), .Y
       (sub_23_2_n_16));
  OAI2BB1X1 sub_23_2_g286(.A0N (in2[0]), .A1N (sub_23_2_n_1), .B0
       (sub_23_2_n_2), .Y (out1[0]));
  NOR2BX1 sub_23_2_g287(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_14));
  NAND2BX1 sub_23_2_g288(.AN (in2[6]), .B (in1[6]), .Y (sub_23_2_n_13));
  NOR2BX1 sub_23_2_g289(.AN (in2[6]), .B (in1[6]), .Y (sub_23_2_n_12));
  NAND2BX1 sub_23_2_g290(.AN (in2[7]), .B (in1[7]), .Y (sub_23_2_n_11));
  NOR2BX1 sub_23_2_g291(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_10));
  NOR2BX1 sub_23_2_g292(.AN (in2[2]), .B (in1[2]), .Y (sub_23_2_n_9));
  NOR2BX1 sub_23_2_g293(.AN (in2[3]), .B (in1[3]), .Y (sub_23_2_n_8));
  NOR2BX1 sub_23_2_g294(.AN (in2[7]), .B (in1[7]), .Y (sub_23_2_n_7));
  NOR2BX1 sub_23_2_g295(.AN (in1[4]), .B (in2[4]), .Y (sub_23_2_n_6));
  NAND2BX1 sub_23_2_g296(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_5));
  NAND2BX1 sub_23_2_g297(.AN (in2[2]), .B (in1[2]), .Y (sub_23_2_n_4));
  NAND2BX1 sub_23_2_g298(.AN (in2[3]), .B (in1[3]), .Y (sub_23_2_n_3));
  NAND2BX1 sub_23_2_g299(.AN (in2[0]), .B (in1[0]), .Y (sub_23_2_n_2));
  INVXL sub_23_2_g300(.A (in1[0]), .Y (sub_23_2_n_1));
  INVX1 sub_23_2_g301(.A (in1[1]), .Y (sub_23_2_n_0));
endmodule


