`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:12 CST (May 15 2023 01:04:12 UTC)

module Filter_Add_5Ux3U_5U_4(in2, in1, out1);
  input [4:0] in2;
  input [2:0] in1;
  output [4:0] out1;
  wire [4:0] in2;
  wire [2:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_7, add_23_2_n_9, add_23_2_n_10;
  XNOR2X1 add_23_2_g80(.A (in2[4]), .B (add_23_2_n_9), .Y (out1[4]));
  XOR2XL add_23_2_g81(.A (in2[3]), .B (add_23_2_n_10), .Y (out1[3]));
  OAI2BB1X1 add_23_2_g82(.A0N (add_23_2_n_0), .A1N (add_23_2_n_7), .B0
       (add_23_2_n_2), .Y (add_23_2_n_10));
  AOI32X1 add_23_2_g83(.A0 (add_23_2_n_7), .A1 (in2[3]), .A2
       (add_23_2_n_0), .B0 (in2[3]), .B1 (add_23_2_n_1), .Y
       (add_23_2_n_9));
  XNOR2X1 add_23_2_g84(.A (add_23_2_n_3), .B (add_23_2_n_7), .Y
       (out1[2]));
  ADDFX1 add_23_2_g85(.A (add_23_2_n_4), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_7), .S (out1[1]));
  ADDHX1 add_23_2_g86(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_4), .S
       (out1[0]));
  NAND2X1 add_23_2_g87(.A (add_23_2_n_2), .B (add_23_2_n_0), .Y
       (add_23_2_n_3));
  INVX1 add_23_2_g88(.A (add_23_2_n_2), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g89(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  OR2X1 add_23_2_g90(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_0));
endmodule


