`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:07 CST (May 15 2023 01:04:07 UTC)

module Filter_Add_12Ux7U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [6:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [6:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_26;
  wire add_23_2_n_27, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32,
       add_23_2_n_35, add_23_2_n_36, add_23_2_n_37, add_23_2_n_39;
  XNOR2X1 add_23_2_g229(.A (in2[11]), .B (add_23_2_n_39), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g230(.A (in2[9]), .B (add_23_2_n_37), .Y (out1[9]));
  XNOR2X1 add_23_2_g231(.A (in2[10]), .B (add_23_2_n_36), .Y
       (out1[10]));
  XOR2XL add_23_2_g232(.A (in2[7]), .B (add_23_2_n_35), .Y (out1[7]));
  NAND2BX1 add_23_2_g233(.AN (add_23_2_n_36), .B (in2[10]), .Y
       (add_23_2_n_39));
  XNOR2X1 add_23_2_g234(.A (in2[8]), .B (add_23_2_n_32), .Y (out1[8]));
  NAND2BX1 add_23_2_g235(.AN (add_23_2_n_32), .B (in2[8]), .Y
       (add_23_2_n_37));
  NAND3BXL add_23_2_g236(.AN (add_23_2_n_32), .B (in2[9]), .C (in2[8]),
       .Y (add_23_2_n_36));
  OAI21X1 add_23_2_g237(.A0 (add_23_2_n_0), .A1 (add_23_2_n_31), .B0
       (add_23_2_n_3), .Y (add_23_2_n_35));
  XNOR2X1 add_23_2_g238(.A (add_23_2_n_14), .B (add_23_2_n_31), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g239(.A (add_23_2_n_12), .B (add_23_2_n_30), .Y
       (out1[5]));
  AOI221X1 add_23_2_g240(.A0 (add_23_2_n_15), .A1 (add_23_2_n_18), .B0
       (add_23_2_n_15), .B1 (add_23_2_n_27), .C0 (add_23_2_n_11), .Y
       (add_23_2_n_32));
  NOR2X1 add_23_2_g241(.A (add_23_2_n_18), .B (add_23_2_n_27), .Y
       (add_23_2_n_31));
  OAI2BB1X1 add_23_2_g242(.A0N (add_23_2_n_10), .A1N (add_23_2_n_24),
       .B0 (add_23_2_n_2), .Y (add_23_2_n_30));
  XNOR2X1 add_23_2_g243(.A (add_23_2_n_16), .B (add_23_2_n_24), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g244(.A (add_23_2_n_13), .B (add_23_2_n_26), .Y
       (out1[3]));
  NOR3BX1 add_23_2_g245(.AN (add_23_2_n_24), .B (add_23_2_n_1), .C
       (add_23_2_n_9), .Y (add_23_2_n_27));
  OAI2BB1X1 add_23_2_g246(.A0N (add_23_2_n_8), .A1N (add_23_2_n_22),
       .B0 (add_23_2_n_6), .Y (add_23_2_n_26));
  XNOR2X1 add_23_2_g247(.A (add_23_2_n_17), .B (add_23_2_n_22), .Y
       (out1[2]));
  OAI211X1 add_23_2_g248(.A0 (add_23_2_n_6), .A1 (add_23_2_n_7), .B0
       (add_23_2_n_23), .C0 (add_23_2_n_4), .Y (add_23_2_n_24));
  NAND3BXL add_23_2_g249(.AN (add_23_2_n_7), .B (add_23_2_n_22), .C
       (add_23_2_n_8), .Y (add_23_2_n_23));
  ADDFX1 add_23_2_g250(.A (add_23_2_n_19), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_22), .S (out1[1]));
  ADDHX1 add_23_2_g251(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_19),
       .S (out1[0]));
  OAI21X1 add_23_2_g252(.A0 (add_23_2_n_2), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_5), .Y (add_23_2_n_18));
  NAND2X1 add_23_2_g253(.A (add_23_2_n_6), .B (add_23_2_n_8), .Y
       (add_23_2_n_17));
  NAND2X1 add_23_2_g254(.A (add_23_2_n_2), .B (add_23_2_n_10), .Y
       (add_23_2_n_16));
  NOR2BX1 add_23_2_g255(.AN (in2[7]), .B (add_23_2_n_0), .Y
       (add_23_2_n_15));
  NOR2BX1 add_23_2_g256(.AN (add_23_2_n_3), .B (add_23_2_n_0), .Y
       (add_23_2_n_14));
  NAND2BX1 add_23_2_g257(.AN (add_23_2_n_7), .B (add_23_2_n_4), .Y
       (add_23_2_n_13));
  NAND2BX1 add_23_2_g258(.AN (add_23_2_n_1), .B (add_23_2_n_5), .Y
       (add_23_2_n_12));
  NOR2BX1 add_23_2_g259(.AN (in2[7]), .B (add_23_2_n_3), .Y
       (add_23_2_n_11));
  INVX1 add_23_2_g260(.A (add_23_2_n_9), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g261(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_9));
  OR2X1 add_23_2_g262(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_8));
  NOR2X1 add_23_2_g263(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g264(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g265(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g266(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g267(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g268(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g269(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g270(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_0));
endmodule


