`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:10 CST (May 15 2023 01:04:10 UTC)

module Filter_Div_12Ux3U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [2:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [2:0] in1;
  wire [11:0] out1;
  wire in2_1_0_, in2_1_3_, in2_2_0_, in2_4_0_, in2_4_1_, in2_4_3_,
       in2_5_0_, in2_5_1_;
  wire in2_7_0_, in2_7_1_, in2_7_2_, in2_7_3_, in2_8_0_, in2_8_1_,
       in2_8_2_, in2_10_0_;
  wire in2_10_1_, in2_10_2_, in2_10_3_, in2_11_0_, in2_11_1_,
       in2_11_2_, in2_13_0_, in2_13_1_;
  wire in2_13_2_, in2_13_3_, in2_14_0_, in2_14_1_, in2_14_2_,
       in2_16_0_, in2_16_1_, in2_16_2_;
  wire in2_16_3_, in2_17_0_, in2_17_1_, in2_17_2_, in2_19_0_,
       in2_19_1_, in2_19_2_, in2_19_3_;
  wire in2_20_0_, in2_20_1_, in2_20_2_, in2_22_0_, in2_22_1_,
       in2_22_2_, in2_22_3_, in2_23_0_;
  wire in2_23_1_, in2_23_2_, in2_25_0_, in2_25_1_, in2_25_2_,
       in2_25_3_, in2_26_0_, in2_26_1_;
  wire in2_26_2_, in2_28_0_, in2_28_1_, in2_28_2_, in2_28_3_,
       in2_29_0_, in2_29_1_, in2_29_2_;
  wire in2_31_0_, in2_31_1_, in2_31_2_, in2_31_3_, in2_32_0_,
       in2_32_1_, in2_32_2_, in2_34_3_;
  wire sub_69_2_n_1, sub_69_2_n_2, sub_69_2_n_3, sub_90_2_n_0,
       sub_90_2_n_1, sub_90_2_n_2, sub_90_2_n_4, sub_111_2_n_0;
  wire sub_111_2_n_1, sub_111_2_n_2, sub_111_2_n_3, sub_111_2_n_5,
       sub_111_2_n_7, sub_132_2_n_0, sub_132_2_n_1, sub_132_2_n_2;
  wire sub_132_2_n_3, sub_132_2_n_5, sub_132_2_n_7, sub_153_2_n_0,
       sub_153_2_n_1, sub_153_2_n_2, sub_153_2_n_3, sub_153_2_n_5;
  wire sub_153_2_n_7, sub_174_2_n_0, sub_174_2_n_1, sub_174_2_n_2,
       sub_174_2_n_3, sub_174_2_n_5, sub_174_2_n_7, sub_195_2_n_0;
  wire sub_195_2_n_1, sub_195_2_n_2, sub_195_2_n_3, sub_195_2_n_5,
       sub_195_2_n_7, sub_216_2_n_0, sub_216_2_n_1, sub_216_2_n_2;
  wire sub_216_2_n_3, sub_216_2_n_5, sub_216_2_n_7, sub_237_2_n_0,
       sub_237_2_n_1, sub_237_2_n_2, sub_237_2_n_3, sub_237_2_n_5;
  wire sub_237_2_n_7, sub_258_2_n_0, sub_258_2_n_1, sub_258_2_n_2,
       sub_258_2_n_3, sub_258_2_n_5, sub_258_2_n_7, sub_279_2_n_0;
  wire sub_279_2_n_1, sub_279_2_n_2, sub_279_2_n_3, sub_279_2_n_5,
       sub_279_2_n_7, sub_298_2_n_1, sub_298_2_n_2, sub_298_2_n_3;
  wire sub_298_2_n_4, sub_298_2_n_5, sub_298_2_n_6, sub_298_2_n_7;
  INVX1 g126(.A (in2_34_3_), .Y (out1[0]));
  MX2XL g119(.A (in2_1_0_), .B (in2[11]), .S0 (in2_1_3_), .Y
       (in2_2_0_));
  MX2X1 g130(.A (in2_4_1_), .B (in2_2_0_), .S0 (in2_4_3_), .Y
       (in2_5_1_));
  MX2XL g131(.A (in2_4_0_), .B (in2[10]), .S0 (in2_4_3_), .Y
       (in2_5_0_));
  MX2XL g141(.A (in2_7_2_), .B (in2_5_1_), .S0 (in2_7_3_), .Y
       (in2_8_2_));
  MX2X1 g142(.A (in2_7_1_), .B (in2_5_0_), .S0 (in2_7_3_), .Y
       (in2_8_1_));
  MX2XL g143(.A (in2_7_0_), .B (in2[9]), .S0 (in2_7_3_), .Y (in2_8_0_));
  MX2XL g144(.A (in2_10_2_), .B (in2_8_1_), .S0 (in2_10_3_), .Y
       (in2_11_2_));
  MX2X1 g145(.A (in2_10_1_), .B (in2_8_0_), .S0 (in2_10_3_), .Y
       (in2_11_1_));
  MX2XL g146(.A (in2_10_0_), .B (in2[8]), .S0 (in2_10_3_), .Y
       (in2_11_0_));
  MX2XL g147(.A (in2_13_2_), .B (in2_11_1_), .S0 (in2_13_3_), .Y
       (in2_14_2_));
  MX2XL g148(.A (in2_13_1_), .B (in2_11_0_), .S0 (in2_13_3_), .Y
       (in2_14_1_));
  MX2XL g149(.A (in2_13_0_), .B (in2[7]), .S0 (in2_13_3_), .Y
       (in2_14_0_));
  MX2XL g150(.A (in2_16_2_), .B (in2_14_1_), .S0 (in2_16_3_), .Y
       (in2_17_2_));
  MX2XL g151(.A (in2_16_1_), .B (in2_14_0_), .S0 (in2_16_3_), .Y
       (in2_17_1_));
  MX2XL g152(.A (in2_16_0_), .B (in2[6]), .S0 (in2_16_3_), .Y
       (in2_17_0_));
  MX2XL g153(.A (in2_19_2_), .B (in2_17_1_), .S0 (in2_19_3_), .Y
       (in2_20_2_));
  MX2X1 g154(.A (in2_19_1_), .B (in2_17_0_), .S0 (in2_19_3_), .Y
       (in2_20_1_));
  MX2XL g155(.A (in2_19_0_), .B (in2[5]), .S0 (in2_19_3_), .Y
       (in2_20_0_));
  INVX1 g120(.A (in2_1_3_), .Y (out1[11]));
  INVX1 g121(.A (in2_31_3_), .Y (out1[1]));
  INVX1 g122(.A (in2_28_3_), .Y (out1[2]));
  INVX1 g123(.A (in2_25_3_), .Y (out1[3]));
  INVX1 g124(.A (in2_22_3_), .Y (out1[4]));
  INVX1 g125(.A (in2_19_3_), .Y (out1[5]));
  INVX1 g156(.A (in2_16_3_), .Y (out1[6]));
  INVX1 g127(.A (in2_13_3_), .Y (out1[7]));
  INVX1 g128(.A (in2_10_3_), .Y (out1[8]));
  INVX1 g129(.A (in2_7_3_), .Y (out1[9]));
  INVX1 g157(.A (in2_4_3_), .Y (out1[10]));
  MX2XL g158(.A (in2_22_2_), .B (in2_20_1_), .S0 (in2_22_3_), .Y
       (in2_23_2_));
  MX2XL g159(.A (in2_22_1_), .B (in2_20_0_), .S0 (in2_22_3_), .Y
       (in2_23_1_));
  MX2XL g160(.A (in2_22_0_), .B (in2[4]), .S0 (in2_22_3_), .Y
       (in2_23_0_));
  MX2XL g161(.A (in2_25_2_), .B (in2_23_1_), .S0 (in2_25_3_), .Y
       (in2_26_2_));
  MX2XL g162(.A (in2_25_1_), .B (in2_23_0_), .S0 (in2_25_3_), .Y
       (in2_26_1_));
  MX2XL g163(.A (in2_25_0_), .B (in2[3]), .S0 (in2_25_3_), .Y
       (in2_26_0_));
  MX2XL g164(.A (in2_28_2_), .B (in2_26_1_), .S0 (in2_28_3_), .Y
       (in2_29_2_));
  MX2XL g165(.A (in2_28_1_), .B (in2_26_0_), .S0 (in2_28_3_), .Y
       (in2_29_1_));
  MX2XL g166(.A (in2_28_0_), .B (in2[2]), .S0 (in2_28_3_), .Y
       (in2_29_0_));
  MX2XL g167(.A (in2_31_2_), .B (in2_29_1_), .S0 (in2_31_3_), .Y
       (in2_32_2_));
  MX2X1 g168(.A (in2_31_1_), .B (in2_29_0_), .S0 (in2_31_3_), .Y
       (in2_32_1_));
  MX2XL g169(.A (in2_31_0_), .B (in2[1]), .S0 (in2_31_3_), .Y
       (in2_32_0_));
  OR3XL sub_69_2_g48(.A (in1[2]), .B (in1[1]), .C (sub_69_2_n_2), .Y
       (in2_1_3_));
  INVXL sub_69_2_g49(.A (sub_69_2_n_3), .Y (in2_1_0_));
  ADDHX1 sub_69_2_g50(.A (in1[0]), .B (sub_69_2_n_1), .CO
       (sub_69_2_n_2), .S (sub_69_2_n_3));
  INVX1 sub_69_2_g51(.A (in2[11]), .Y (sub_69_2_n_1));
  NAND2BX1 sub_90_2_g47(.AN (in1[2]), .B (sub_90_2_n_4), .Y (in2_4_3_));
  ADDFX1 sub_90_2_g48(.A (sub_90_2_n_2), .B (sub_90_2_n_1), .CI
       (in2_2_0_), .CO (sub_90_2_n_4), .S (in2_4_1_));
  OAI2BB1X1 sub_90_2_g49(.A0N (in2[10]), .A1N (sub_90_2_n_0), .B0
       (sub_90_2_n_2), .Y (in2_4_0_));
  NAND2BX1 sub_90_2_g50(.AN (in2[10]), .B (in1[0]), .Y (sub_90_2_n_2));
  INVX1 sub_90_2_g51(.A (in1[1]), .Y (sub_90_2_n_1));
  INVXL sub_90_2_g52(.A (in1[0]), .Y (sub_90_2_n_0));
  INVX1 sub_111_2_g65(.A (sub_111_2_n_7), .Y (in2_7_3_));
  ADDFX1 sub_111_2_g66(.A (sub_111_2_n_5), .B (in2_5_1_), .CI
       (sub_111_2_n_0), .CO (sub_111_2_n_7), .S (in2_7_2_));
  ADDFX1 sub_111_2_g67(.A (sub_111_2_n_3), .B (sub_111_2_n_2), .CI
       (in2_5_0_), .CO (sub_111_2_n_5), .S (in2_7_1_));
  OAI2BB1X1 sub_111_2_g68(.A0N (in2[9]), .A1N (sub_111_2_n_1), .B0
       (sub_111_2_n_3), .Y (in2_7_0_));
  NAND2BX1 sub_111_2_g69(.AN (in2[9]), .B (in1[0]), .Y (sub_111_2_n_3));
  INVX1 sub_111_2_g70(.A (in1[1]), .Y (sub_111_2_n_2));
  INVX1 sub_111_2_g71(.A (in1[0]), .Y (sub_111_2_n_1));
  INVX1 sub_111_2_g72(.A (in1[2]), .Y (sub_111_2_n_0));
  XNOR2X1 sub_132_2_g71(.A (in2_8_2_), .B (sub_132_2_n_7), .Y
       (in2_10_3_));
  ADDFX1 sub_132_2_g72(.A (sub_132_2_n_5), .B (in2_8_1_), .CI
       (sub_132_2_n_0), .CO (sub_132_2_n_7), .S (in2_10_2_));
  ADDFX1 sub_132_2_g73(.A (sub_132_2_n_3), .B (sub_132_2_n_1), .CI
       (in2_8_0_), .CO (sub_132_2_n_5), .S (in2_10_1_));
  OAI2BB1X1 sub_132_2_g74(.A0N (in2[8]), .A1N (sub_132_2_n_2), .B0
       (sub_132_2_n_3), .Y (in2_10_0_));
  NAND2BX1 sub_132_2_g75(.AN (in2[8]), .B (in1[0]), .Y (sub_132_2_n_3));
  INVX1 sub_132_2_g76(.A (in1[0]), .Y (sub_132_2_n_2));
  INVX1 sub_132_2_g77(.A (in1[1]), .Y (sub_132_2_n_1));
  INVX1 sub_132_2_g78(.A (in1[2]), .Y (sub_132_2_n_0));
  XNOR2X1 sub_153_2_g71(.A (in2_11_2_), .B (sub_153_2_n_7), .Y
       (in2_13_3_));
  ADDFX1 sub_153_2_g72(.A (sub_153_2_n_5), .B (in2_11_1_), .CI
       (sub_153_2_n_0), .CO (sub_153_2_n_7), .S (in2_13_2_));
  ADDFX1 sub_153_2_g73(.A (sub_153_2_n_3), .B (sub_153_2_n_1), .CI
       (in2_11_0_), .CO (sub_153_2_n_5), .S (in2_13_1_));
  OAI2BB1X1 sub_153_2_g74(.A0N (in2[7]), .A1N (sub_153_2_n_2), .B0
       (sub_153_2_n_3), .Y (in2_13_0_));
  NAND2BX1 sub_153_2_g75(.AN (in2[7]), .B (in1[0]), .Y (sub_153_2_n_3));
  INVX1 sub_153_2_g76(.A (in1[0]), .Y (sub_153_2_n_2));
  INVX1 sub_153_2_g77(.A (in1[1]), .Y (sub_153_2_n_1));
  INVX1 sub_153_2_g78(.A (in1[2]), .Y (sub_153_2_n_0));
  XNOR2X1 sub_174_2_g71(.A (in2_14_2_), .B (sub_174_2_n_7), .Y
       (in2_16_3_));
  ADDFX1 sub_174_2_g72(.A (sub_174_2_n_5), .B (in2_14_1_), .CI
       (sub_174_2_n_0), .CO (sub_174_2_n_7), .S (in2_16_2_));
  ADDFX1 sub_174_2_g73(.A (sub_174_2_n_3), .B (sub_174_2_n_1), .CI
       (in2_14_0_), .CO (sub_174_2_n_5), .S (in2_16_1_));
  OAI2BB1X1 sub_174_2_g74(.A0N (in2[6]), .A1N (sub_174_2_n_2), .B0
       (sub_174_2_n_3), .Y (in2_16_0_));
  NAND2BX1 sub_174_2_g75(.AN (in2[6]), .B (in1[0]), .Y (sub_174_2_n_3));
  INVX1 sub_174_2_g76(.A (in1[0]), .Y (sub_174_2_n_2));
  INVX1 sub_174_2_g77(.A (in1[1]), .Y (sub_174_2_n_1));
  INVX1 sub_174_2_g78(.A (in1[2]), .Y (sub_174_2_n_0));
  XNOR2X1 sub_195_2_g71(.A (in2_17_2_), .B (sub_195_2_n_7), .Y
       (in2_19_3_));
  ADDFX1 sub_195_2_g72(.A (sub_195_2_n_5), .B (in2_17_1_), .CI
       (sub_195_2_n_0), .CO (sub_195_2_n_7), .S (in2_19_2_));
  ADDFX1 sub_195_2_g73(.A (sub_195_2_n_3), .B (sub_195_2_n_1), .CI
       (in2_17_0_), .CO (sub_195_2_n_5), .S (in2_19_1_));
  OAI2BB1X1 sub_195_2_g74(.A0N (in2[5]), .A1N (sub_195_2_n_2), .B0
       (sub_195_2_n_3), .Y (in2_19_0_));
  NAND2BX1 sub_195_2_g75(.AN (in2[5]), .B (in1[0]), .Y (sub_195_2_n_3));
  INVX1 sub_195_2_g76(.A (in1[0]), .Y (sub_195_2_n_2));
  INVX1 sub_195_2_g77(.A (in1[1]), .Y (sub_195_2_n_1));
  INVX1 sub_195_2_g78(.A (in1[2]), .Y (sub_195_2_n_0));
  XNOR2X1 sub_216_2_g71(.A (in2_20_2_), .B (sub_216_2_n_7), .Y
       (in2_22_3_));
  ADDFX1 sub_216_2_g72(.A (sub_216_2_n_5), .B (in2_20_1_), .CI
       (sub_216_2_n_0), .CO (sub_216_2_n_7), .S (in2_22_2_));
  ADDFX1 sub_216_2_g73(.A (sub_216_2_n_3), .B (sub_216_2_n_1), .CI
       (in2_20_0_), .CO (sub_216_2_n_5), .S (in2_22_1_));
  OAI2BB1X1 sub_216_2_g74(.A0N (in2[4]), .A1N (sub_216_2_n_2), .B0
       (sub_216_2_n_3), .Y (in2_22_0_));
  NAND2BX1 sub_216_2_g75(.AN (in2[4]), .B (in1[0]), .Y (sub_216_2_n_3));
  INVX1 sub_216_2_g76(.A (in1[0]), .Y (sub_216_2_n_2));
  INVX1 sub_216_2_g77(.A (in1[1]), .Y (sub_216_2_n_1));
  INVX1 sub_216_2_g78(.A (in1[2]), .Y (sub_216_2_n_0));
  XNOR2X1 sub_237_2_g71(.A (in2_23_2_), .B (sub_237_2_n_7), .Y
       (in2_25_3_));
  ADDFX1 sub_237_2_g72(.A (sub_237_2_n_5), .B (in2_23_1_), .CI
       (sub_237_2_n_0), .CO (sub_237_2_n_7), .S (in2_25_2_));
  ADDFX1 sub_237_2_g73(.A (sub_237_2_n_3), .B (sub_237_2_n_1), .CI
       (in2_23_0_), .CO (sub_237_2_n_5), .S (in2_25_1_));
  OAI2BB1X1 sub_237_2_g74(.A0N (in2[3]), .A1N (sub_237_2_n_2), .B0
       (sub_237_2_n_3), .Y (in2_25_0_));
  NAND2BX1 sub_237_2_g75(.AN (in2[3]), .B (in1[0]), .Y (sub_237_2_n_3));
  INVX1 sub_237_2_g76(.A (in1[0]), .Y (sub_237_2_n_2));
  INVX1 sub_237_2_g77(.A (in1[1]), .Y (sub_237_2_n_1));
  INVX1 sub_237_2_g78(.A (in1[2]), .Y (sub_237_2_n_0));
  XNOR2X1 sub_258_2_g71(.A (in2_26_2_), .B (sub_258_2_n_7), .Y
       (in2_28_3_));
  ADDFX1 sub_258_2_g72(.A (sub_258_2_n_5), .B (in2_26_1_), .CI
       (sub_258_2_n_0), .CO (sub_258_2_n_7), .S (in2_28_2_));
  ADDFX1 sub_258_2_g73(.A (sub_258_2_n_3), .B (sub_258_2_n_1), .CI
       (in2_26_0_), .CO (sub_258_2_n_5), .S (in2_28_1_));
  OAI2BB1X1 sub_258_2_g74(.A0N (in2[2]), .A1N (sub_258_2_n_2), .B0
       (sub_258_2_n_3), .Y (in2_28_0_));
  NAND2BX1 sub_258_2_g75(.AN (in2[2]), .B (in1[0]), .Y (sub_258_2_n_3));
  INVX1 sub_258_2_g76(.A (in1[0]), .Y (sub_258_2_n_2));
  INVX1 sub_258_2_g77(.A (in1[1]), .Y (sub_258_2_n_1));
  INVX1 sub_258_2_g78(.A (in1[2]), .Y (sub_258_2_n_0));
  XNOR2X1 sub_279_2_g71(.A (in2_29_2_), .B (sub_279_2_n_7), .Y
       (in2_31_3_));
  ADDFX1 sub_279_2_g72(.A (sub_279_2_n_5), .B (in2_29_1_), .CI
       (sub_279_2_n_0), .CO (sub_279_2_n_7), .S (in2_31_2_));
  ADDFX1 sub_279_2_g73(.A (sub_279_2_n_3), .B (sub_279_2_n_1), .CI
       (in2_29_0_), .CO (sub_279_2_n_5), .S (in2_31_1_));
  OAI2BB1X1 sub_279_2_g74(.A0N (in2[1]), .A1N (sub_279_2_n_2), .B0
       (sub_279_2_n_3), .Y (in2_31_0_));
  NAND2BX1 sub_279_2_g75(.AN (in2[1]), .B (in1[0]), .Y (sub_279_2_n_3));
  INVX1 sub_279_2_g76(.A (in1[0]), .Y (sub_279_2_n_2));
  INVX1 sub_279_2_g77(.A (in1[1]), .Y (sub_279_2_n_1));
  INVX1 sub_279_2_g78(.A (in1[2]), .Y (sub_279_2_n_0));
  XNOR2X1 sub_298_2_g54(.A (in2_32_2_), .B (sub_298_2_n_7), .Y
       (in2_34_3_));
  OAI22X1 sub_298_2_g55(.A0 (sub_298_2_n_4), .A1 (sub_298_2_n_6), .B0
       (sub_298_2_n_2), .B1 (in1[2]), .Y (sub_298_2_n_7));
  AOI22X1 sub_298_2_g56(.A0 (sub_298_2_n_3), .A1 (sub_298_2_n_5), .B0
       (in2_32_0_), .B1 (sub_298_2_n_1), .Y (sub_298_2_n_6));
  NAND2BX1 sub_298_2_g57(.AN (in2[0]), .B (in1[0]), .Y (sub_298_2_n_5));
  NOR2BX1 sub_298_2_g58(.AN (in1[2]), .B (in2_32_1_), .Y
       (sub_298_2_n_4));
  OR2XL sub_298_2_g59(.A (sub_298_2_n_1), .B (in2_32_0_), .Y
       (sub_298_2_n_3));
  INVX1 sub_298_2_g60(.A (in2_32_1_), .Y (sub_298_2_n_2));
  INVX1 sub_298_2_g61(.A (in1[1]), .Y (sub_298_2_n_1));
endmodule


