`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:15 CST (May 15 2023 01:04:15 UTC)

module Filter_Mul_3Ux2U_5U_4(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_4,
       mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7, mul_22_8_n_8;
  wire mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_12, mul_22_8_n_13,
       mul_22_8_n_16;
  XOR2XL mul_22_8_g104(.A (mul_22_8_n_1), .B (mul_22_8_n_16), .Y
       (out1[3]));
  AOI21X1 mul_22_8_g105(.A0 (mul_22_8_n_9), .A1 (mul_22_8_n_8), .B0
       (mul_22_8_n_6), .Y (mul_22_8_n_16));
  XNOR2X1 mul_22_8_g106(.A (mul_22_8_n_8), .B (mul_22_8_n_12), .Y
       (out1[2]));
  OAI32X1 mul_22_8_g107(.A0 (mul_22_8_n_13), .A1 (mul_22_8_n_1), .A2
       (mul_22_8_n_10), .B0 (mul_22_8_n_1), .B1 (mul_22_8_n_7), .Y
       (out1[4]));
  INVX1 mul_22_8_g108(.A (mul_22_8_n_8), .Y (mul_22_8_n_13));
  NAND2X1 mul_22_8_g109(.A (mul_22_8_n_9), .B (mul_22_8_n_7), .Y
       (mul_22_8_n_12));
  AOI21X1 mul_22_8_g110(.A0 (mul_22_8_n_4), .A1 (mul_22_8_n_0), .B0
       (mul_22_8_n_8), .Y (out1[1]));
  INVX1 mul_22_8_g111(.A (mul_22_8_n_9), .Y (mul_22_8_n_10));
  NAND2X1 mul_22_8_g112(.A (mul_22_8_n_2), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_9));
  NOR2X1 mul_22_8_g113(.A (mul_22_8_n_4), .B (mul_22_8_n_0), .Y
       (mul_22_8_n_8));
  INVX1 mul_22_8_g114(.A (mul_22_8_n_6), .Y (mul_22_8_n_7));
  NOR2X1 mul_22_8_g115(.A (mul_22_8_n_2), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_6));
  NAND2X1 mul_22_8_g116(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_5));
  NAND2X1 mul_22_8_g117(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_4));
  AND2XL mul_22_8_g118(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g119(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_2));
  NAND2X1 mul_22_8_g120(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_1));
  NAND2X1 mul_22_8_g121(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_0));
endmodule


