`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:08 CST (May 15 2023 01:04:08 UTC)

module Filter_Div_7Ux3U_7U_4(in2, in1, out1);
  input [6:0] in2;
  input [2:0] in1;
  output [6:0] out1;
  wire [6:0] in2;
  wire [2:0] in1;
  wire [6:0] out1;
  wire in2_1_0_, in2_1_3_, in2_2_0_, in2_4_0_, in2_4_1_, in2_4_3_,
       in2_5_0_, in2_5_1_;
  wire in2_7_0_, in2_7_1_, in2_7_2_, in2_7_3_, in2_8_0_, in2_8_1_,
       in2_8_2_, in2_10_0_;
  wire in2_10_1_, in2_10_2_, in2_10_3_, in2_11_0_, in2_11_1_,
       in2_11_2_, in2_13_0_, in2_13_1_;
  wire in2_13_2_, in2_13_3_, in2_14_0_, in2_14_1_, in2_14_2_,
       in2_16_0_, in2_16_1_, in2_16_2_;
  wire in2_16_3_, in2_17_0_, in2_17_1_, in2_17_2_, in2_19_3_,
       sub_49_2_n_1, sub_49_2_n_2, sub_49_2_n_3;
  wire sub_70_2_n_0, sub_70_2_n_1, sub_70_2_n_2, sub_70_2_n_4,
       sub_91_2_n_0, sub_91_2_n_1, sub_91_2_n_2, sub_91_2_n_3;
  wire sub_91_2_n_5, sub_91_2_n_7, sub_112_2_n_0, sub_112_2_n_1,
       sub_112_2_n_2, sub_112_2_n_3, sub_112_2_n_5, sub_112_2_n_7;
  wire sub_133_2_n_0, sub_133_2_n_1, sub_133_2_n_2, sub_133_2_n_3,
       sub_133_2_n_5, sub_133_2_n_7, sub_154_2_n_0, sub_154_2_n_1;
  wire sub_154_2_n_2, sub_154_2_n_3, sub_154_2_n_5, sub_154_2_n_7,
       sub_173_2_n_1, sub_173_2_n_2, sub_173_2_n_3, sub_173_2_n_4;
  wire sub_173_2_n_5, sub_173_2_n_6, sub_173_2_n_7;
  INVX1 g68(.A (in2_19_3_), .Y (out1[0]));
  MX2XL g69(.A (in2_1_0_), .B (in2[6]), .S0 (in2_1_3_), .Y (in2_2_0_));
  MX2X1 g80(.A (in2_4_1_), .B (in2_2_0_), .S0 (in2_4_3_), .Y
       (in2_5_1_));
  MX2XL g81(.A (in2_4_0_), .B (in2[5]), .S0 (in2_4_3_), .Y (in2_5_0_));
  MX2XL g91(.A (in2_7_2_), .B (in2_5_1_), .S0 (in2_7_3_), .Y
       (in2_8_2_));
  MX2X1 g92(.A (in2_7_1_), .B (in2_5_0_), .S0 (in2_7_3_), .Y
       (in2_8_1_));
  MX2XL g93(.A (in2_7_0_), .B (in2[4]), .S0 (in2_7_3_), .Y (in2_8_0_));
  MX2XL g94(.A (in2_10_2_), .B (in2_8_1_), .S0 (in2_10_3_), .Y
       (in2_11_2_));
  MX2XL g95(.A (in2_10_1_), .B (in2_8_0_), .S0 (in2_10_3_), .Y
       (in2_11_1_));
  MX2XL g96(.A (in2_10_0_), .B (in2[3]), .S0 (in2_10_3_), .Y
       (in2_11_0_));
  INVX1 g65(.A (in2_1_3_), .Y (out1[6]));
  INVX1 g66(.A (in2_16_3_), .Y (out1[1]));
  INVX1 g67(.A (in2_7_3_), .Y (out1[4]));
  INVX1 g97(.A (in2_10_3_), .Y (out1[3]));
  INVX1 g98(.A (in2_13_3_), .Y (out1[2]));
  INVX1 g70(.A (in2_4_3_), .Y (out1[5]));
  MX2XL g99(.A (in2_13_2_), .B (in2_11_1_), .S0 (in2_13_3_), .Y
       (in2_14_2_));
  MX2XL g100(.A (in2_13_1_), .B (in2_11_0_), .S0 (in2_13_3_), .Y
       (in2_14_1_));
  MX2XL g101(.A (in2_13_0_), .B (in2[2]), .S0 (in2_13_3_), .Y
       (in2_14_0_));
  MX2XL g102(.A (in2_16_2_), .B (in2_14_1_), .S0 (in2_16_3_), .Y
       (in2_17_2_));
  MX2X1 g103(.A (in2_16_1_), .B (in2_14_0_), .S0 (in2_16_3_), .Y
       (in2_17_1_));
  MX2XL g104(.A (in2_16_0_), .B (in2[1]), .S0 (in2_16_3_), .Y
       (in2_17_0_));
  OR3XL sub_49_2_g48(.A (in1[2]), .B (in1[1]), .C (sub_49_2_n_2), .Y
       (in2_1_3_));
  INVXL sub_49_2_g49(.A (sub_49_2_n_3), .Y (in2_1_0_));
  ADDHX1 sub_49_2_g50(.A (in1[0]), .B (sub_49_2_n_1), .CO
       (sub_49_2_n_2), .S (sub_49_2_n_3));
  INVX1 sub_49_2_g51(.A (in2[6]), .Y (sub_49_2_n_1));
  NAND2BX1 sub_70_2_g47(.AN (in1[2]), .B (sub_70_2_n_4), .Y (in2_4_3_));
  ADDFX1 sub_70_2_g48(.A (sub_70_2_n_2), .B (sub_70_2_n_1), .CI
       (in2_2_0_), .CO (sub_70_2_n_4), .S (in2_4_1_));
  OAI2BB1X1 sub_70_2_g49(.A0N (in2[5]), .A1N (sub_70_2_n_0), .B0
       (sub_70_2_n_2), .Y (in2_4_0_));
  NAND2BX1 sub_70_2_g50(.AN (in2[5]), .B (in1[0]), .Y (sub_70_2_n_2));
  INVX1 sub_70_2_g51(.A (in1[1]), .Y (sub_70_2_n_1));
  INVXL sub_70_2_g52(.A (in1[0]), .Y (sub_70_2_n_0));
  INVX1 sub_91_2_g65(.A (sub_91_2_n_7), .Y (in2_7_3_));
  ADDFX1 sub_91_2_g66(.A (sub_91_2_n_5), .B (in2_5_1_), .CI
       (sub_91_2_n_0), .CO (sub_91_2_n_7), .S (in2_7_2_));
  ADDFX1 sub_91_2_g67(.A (sub_91_2_n_3), .B (sub_91_2_n_2), .CI
       (in2_5_0_), .CO (sub_91_2_n_5), .S (in2_7_1_));
  OAI2BB1X1 sub_91_2_g68(.A0N (in2[4]), .A1N (sub_91_2_n_1), .B0
       (sub_91_2_n_3), .Y (in2_7_0_));
  NAND2BX1 sub_91_2_g69(.AN (in2[4]), .B (in1[0]), .Y (sub_91_2_n_3));
  INVX1 sub_91_2_g70(.A (in1[1]), .Y (sub_91_2_n_2));
  INVX1 sub_91_2_g71(.A (in1[0]), .Y (sub_91_2_n_1));
  INVX1 sub_91_2_g72(.A (in1[2]), .Y (sub_91_2_n_0));
  XNOR2X1 sub_112_2_g71(.A (in2_8_2_), .B (sub_112_2_n_7), .Y
       (in2_10_3_));
  ADDFX1 sub_112_2_g72(.A (sub_112_2_n_5), .B (in2_8_1_), .CI
       (sub_112_2_n_0), .CO (sub_112_2_n_7), .S (in2_10_2_));
  ADDFX1 sub_112_2_g73(.A (sub_112_2_n_3), .B (sub_112_2_n_1), .CI
       (in2_8_0_), .CO (sub_112_2_n_5), .S (in2_10_1_));
  OAI2BB1X1 sub_112_2_g74(.A0N (in2[3]), .A1N (sub_112_2_n_2), .B0
       (sub_112_2_n_3), .Y (in2_10_0_));
  NAND2BX1 sub_112_2_g75(.AN (in2[3]), .B (in1[0]), .Y (sub_112_2_n_3));
  INVX1 sub_112_2_g76(.A (in1[0]), .Y (sub_112_2_n_2));
  INVX1 sub_112_2_g77(.A (in1[1]), .Y (sub_112_2_n_1));
  INVX1 sub_112_2_g78(.A (in1[2]), .Y (sub_112_2_n_0));
  XNOR2X1 sub_133_2_g71(.A (in2_11_2_), .B (sub_133_2_n_7), .Y
       (in2_13_3_));
  ADDFX1 sub_133_2_g72(.A (sub_133_2_n_5), .B (in2_11_1_), .CI
       (sub_133_2_n_0), .CO (sub_133_2_n_7), .S (in2_13_2_));
  ADDFX1 sub_133_2_g73(.A (sub_133_2_n_3), .B (sub_133_2_n_1), .CI
       (in2_11_0_), .CO (sub_133_2_n_5), .S (in2_13_1_));
  OAI2BB1X1 sub_133_2_g74(.A0N (in2[2]), .A1N (sub_133_2_n_2), .B0
       (sub_133_2_n_3), .Y (in2_13_0_));
  NAND2BX1 sub_133_2_g75(.AN (in2[2]), .B (in1[0]), .Y (sub_133_2_n_3));
  INVX1 sub_133_2_g76(.A (in1[0]), .Y (sub_133_2_n_2));
  INVX1 sub_133_2_g77(.A (in1[1]), .Y (sub_133_2_n_1));
  INVX1 sub_133_2_g78(.A (in1[2]), .Y (sub_133_2_n_0));
  XNOR2X1 sub_154_2_g71(.A (in2_14_2_), .B (sub_154_2_n_7), .Y
       (in2_16_3_));
  ADDFX1 sub_154_2_g72(.A (sub_154_2_n_5), .B (in2_14_1_), .CI
       (sub_154_2_n_0), .CO (sub_154_2_n_7), .S (in2_16_2_));
  ADDFX1 sub_154_2_g73(.A (sub_154_2_n_3), .B (sub_154_2_n_1), .CI
       (in2_14_0_), .CO (sub_154_2_n_5), .S (in2_16_1_));
  OAI2BB1X1 sub_154_2_g74(.A0N (in2[1]), .A1N (sub_154_2_n_2), .B0
       (sub_154_2_n_3), .Y (in2_16_0_));
  NAND2BX1 sub_154_2_g75(.AN (in2[1]), .B (in1[0]), .Y (sub_154_2_n_3));
  INVX1 sub_154_2_g76(.A (in1[0]), .Y (sub_154_2_n_2));
  INVX1 sub_154_2_g77(.A (in1[1]), .Y (sub_154_2_n_1));
  INVX1 sub_154_2_g78(.A (in1[2]), .Y (sub_154_2_n_0));
  XNOR2X1 sub_173_2_g54(.A (in2_17_2_), .B (sub_173_2_n_7), .Y
       (in2_19_3_));
  OAI22X1 sub_173_2_g55(.A0 (sub_173_2_n_4), .A1 (sub_173_2_n_6), .B0
       (sub_173_2_n_2), .B1 (in1[2]), .Y (sub_173_2_n_7));
  AOI22X1 sub_173_2_g56(.A0 (sub_173_2_n_3), .A1 (sub_173_2_n_5), .B0
       (in2_17_0_), .B1 (sub_173_2_n_1), .Y (sub_173_2_n_6));
  NAND2BX1 sub_173_2_g57(.AN (in2[0]), .B (in1[0]), .Y (sub_173_2_n_5));
  NOR2BX1 sub_173_2_g58(.AN (in1[2]), .B (in2_17_1_), .Y
       (sub_173_2_n_4));
  OR2XL sub_173_2_g59(.A (sub_173_2_n_1), .B (in2_17_0_), .Y
       (sub_173_2_n_3));
  INVX1 sub_173_2_g60(.A (in2_17_1_), .Y (sub_173_2_n_2));
  INVX1 sub_173_2_g61(.A (in1[1]), .Y (sub_173_2_n_1));
endmodule


