`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:06 CST (May 15 2023 01:04:06 UTC)

module Filter_Add_4Ux1U_4U_4(in2, in1, out1);
  input [3:0] in2;
  input in1;
  output [3:0] out1;
  wire [3:0] in2;
  wire in1;
  wire [3:0] out1;
  wire inc_add_23_2_1_n_0, inc_add_23_2_1_n_2, inc_add_23_2_1_n_4;
  XNOR2X1 inc_add_23_2_1_g33(.A (in2[3]), .B (inc_add_23_2_1_n_4), .Y
       (out1[3]));
  XNOR2X1 inc_add_23_2_1_g34(.A (in2[2]), .B (inc_add_23_2_1_n_2), .Y
       (out1[2]));
  NAND2BX1 inc_add_23_2_1_g35(.AN (inc_add_23_2_1_n_2), .B (in2[2]), .Y
       (inc_add_23_2_1_n_4));
  XNOR2X1 inc_add_23_2_1_g36(.A (in2[1]), .B (inc_add_23_2_1_n_0), .Y
       (out1[1]));
  NAND2BX1 inc_add_23_2_1_g37(.AN (inc_add_23_2_1_n_0), .B (in2[1]), .Y
       (inc_add_23_2_1_n_2));
  XOR2XL inc_add_23_2_1_g38(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2X1 inc_add_23_2_1_g39(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_0));
endmodule


