`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:21 CST (May 15 2023 01:04:21 UTC)

module Filter_N_Mux_12_2_1_1(in3, in2, ctrl1, out1);
  input [11:0] in3, in2;
  input ctrl1;
  output [11:0] out1;
  wire [11:0] in3, in2;
  wire ctrl1;
  wire [11:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  OAI21X4 g121(.A0 (ctrl1), .A1 (n_1), .B0 (n_23), .Y (out1[11]));
  OAI21X4 g127(.A0 (ctrl1), .A1 (n_2), .B0 (n_12), .Y (out1[2]));
  OAI21X4 g131(.A0 (ctrl1), .A1 (n_10), .B0 (n_22), .Y (out1[1]));
  OAI21X4 g132(.A0 (ctrl1), .A1 (n_8), .B0 (n_15), .Y (out1[0]));
  OAI21X4 g128(.A0 (ctrl1), .A1 (n_9), .B0 (n_18), .Y (out1[10]));
  OAI21X4 g129(.A0 (ctrl1), .A1 (n_6), .B0 (n_19), .Y (out1[9]));
  OAI21X4 g122(.A0 (ctrl1), .A1 (n_3), .B0 (n_21), .Y (out1[8]));
  OAI21X4 g125(.A0 (ctrl1), .A1 (n_0), .B0 (n_14), .Y (out1[7]));
  OAI21X4 g130(.A0 (ctrl1), .A1 (n_5), .B0 (n_17), .Y (out1[6]));
  OAI21X4 g123(.A0 (ctrl1), .A1 (n_4), .B0 (n_20), .Y (out1[5]));
  OAI21X4 g124(.A0 (ctrl1), .A1 (n_11), .B0 (n_16), .Y (out1[4]));
  OAI21X4 g126(.A0 (ctrl1), .A1 (n_7), .B0 (n_13), .Y (out1[3]));
  NAND2X8 g133(.A (in2[11]), .B (ctrl1), .Y (n_23));
  NAND2X8 g141(.A (in2[1]), .B (ctrl1), .Y (n_22));
  NAND2X8 g137(.A (in2[8]), .B (ctrl1), .Y (n_21));
  NAND2X8 g135(.A (in2[5]), .B (ctrl1), .Y (n_20));
  NAND2X8 g142(.A (in2[9]), .B (ctrl1), .Y (n_19));
  NAND2X8 g134(.A (in2[10]), .B (ctrl1), .Y (n_18));
  NAND2X8 g143(.A (in2[6]), .B (ctrl1), .Y (n_17));
  NAND2X8 g138(.A (in2[4]), .B (ctrl1), .Y (n_16));
  NAND2X8 g144(.A (in2[0]), .B (ctrl1), .Y (n_15));
  NAND2X8 g136(.A (in2[7]), .B (ctrl1), .Y (n_14));
  NAND2X8 g139(.A (in2[3]), .B (ctrl1), .Y (n_13));
  NAND2X8 g140(.A (in2[2]), .B (ctrl1), .Y (n_12));
  CLKINVX4 g151(.A (in3[4]), .Y (n_11));
  CLKINVX4 g156(.A (in3[1]), .Y (n_10));
  CLKINVX4 g152(.A (in3[10]), .Y (n_9));
  CLKINVX4 g154(.A (in3[0]), .Y (n_8));
  CLKINVX4 g155(.A (in3[3]), .Y (n_7));
  CLKINVX4 g150(.A (in3[9]), .Y (n_6));
  CLKINVX4 g149(.A (in3[6]), .Y (n_5));
  CLKINVX4 g147(.A (in3[5]), .Y (n_4));
  CLKINVX4 g146(.A (in3[8]), .Y (n_3));
  CLKINVX4 g148(.A (in3[2]), .Y (n_2));
  CLKINVX4 g153(.A (in3[11]), .Y (n_1));
  CLKINVX4 g145(.A (in3[7]), .Y (n_0));
endmodule


