`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:35:48 CST (May 15 2023 01:35:48 UTC)

module Filter_Sub_12Ux7U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [6:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [6:0] in1;
  wire [11:0] out1;
  wire sub_23_2_n_0, sub_23_2_n_1, sub_23_2_n_2, sub_23_2_n_3,
       sub_23_2_n_4, sub_23_2_n_5, sub_23_2_n_6, sub_23_2_n_7;
  wire sub_23_2_n_8, sub_23_2_n_9, sub_23_2_n_10, sub_23_2_n_11,
       sub_23_2_n_12, sub_23_2_n_13, sub_23_2_n_15, sub_23_2_n_16;
  wire sub_23_2_n_17, sub_23_2_n_18, sub_23_2_n_19, sub_23_2_n_20,
       sub_23_2_n_21, sub_23_2_n_22, sub_23_2_n_23, sub_23_2_n_24;
  wire sub_23_2_n_26, sub_23_2_n_27, sub_23_2_n_28, sub_23_2_n_30,
       sub_23_2_n_33, sub_23_2_n_34, sub_23_2_n_35, sub_23_2_n_36;
  wire sub_23_2_n_37, sub_23_2_n_40, sub_23_2_n_42;
  XNOR2X1 sub_23_2_g248(.A (in2[11]), .B (sub_23_2_n_42), .Y
       (out1[11]));
  XOR2XL sub_23_2_g249(.A (in2[9]), .B (sub_23_2_n_37), .Y (out1[9]));
  XNOR2X1 sub_23_2_g250(.A (in2[7]), .B (sub_23_2_n_40), .Y (out1[7]));
  OAI2BB1X1 sub_23_2_g251(.A0N (in2[10]), .A1N (sub_23_2_n_36), .B0
       (sub_23_2_n_42), .Y (out1[10]));
  OR2XL sub_23_2_g252(.A (in2[10]), .B (sub_23_2_n_36), .Y
       (sub_23_2_n_42));
  AO21XL sub_23_2_g253(.A0 (in2[8]), .A1 (sub_23_2_n_33), .B0
       (sub_23_2_n_37), .Y (out1[8]));
  OAI21X1 sub_23_2_g254(.A0 (sub_23_2_n_3), .A1 (sub_23_2_n_35), .B0
       (sub_23_2_n_11), .Y (sub_23_2_n_40));
  XNOR2X1 sub_23_2_g255(.A (sub_23_2_n_18), .B (sub_23_2_n_35), .Y
       (out1[6]));
  XNOR2X1 sub_23_2_g256(.A (sub_23_2_n_16), .B (sub_23_2_n_34), .Y
       (out1[5]));
  NOR2X1 sub_23_2_g257(.A (in2[8]), .B (sub_23_2_n_33), .Y
       (sub_23_2_n_37));
  OR3XL sub_23_2_g258(.A (sub_23_2_n_33), .B (in2[9]), .C (in2[8]), .Y
       (sub_23_2_n_36));
  AOI21X1 sub_23_2_g259(.A0 (sub_23_2_n_15), .A1 (sub_23_2_n_28), .B0
       (sub_23_2_n_21), .Y (sub_23_2_n_35));
  AOI21X1 sub_23_2_g260(.A0 (sub_23_2_n_7), .A1 (sub_23_2_n_28), .B0
       (sub_23_2_n_5), .Y (sub_23_2_n_34));
  OAI2BB1X1 sub_23_2_g261(.A0N (sub_23_2_n_22), .A1N (sub_23_2_n_28),
       .B0 (sub_23_2_n_24), .Y (sub_23_2_n_33));
  XNOR2X1 sub_23_2_g262(.A (sub_23_2_n_17), .B (sub_23_2_n_28), .Y
       (out1[4]));
  XNOR2X1 sub_23_2_g263(.A (sub_23_2_n_20), .B (sub_23_2_n_30), .Y
       (out1[3]));
  AOI21X1 sub_23_2_g264(.A0 (sub_23_2_n_4), .A1 (sub_23_2_n_26), .B0
       (sub_23_2_n_9), .Y (sub_23_2_n_30));
  XNOR2X1 sub_23_2_g265(.A (sub_23_2_n_19), .B (sub_23_2_n_26), .Y
       (out1[2]));
  OAI211X1 sub_23_2_g266(.A0 (sub_23_2_n_10), .A1 (sub_23_2_n_8), .B0
       (sub_23_2_n_27), .C0 (sub_23_2_n_13), .Y (sub_23_2_n_28));
  NAND3BXL sub_23_2_g267(.AN (sub_23_2_n_10), .B (sub_23_2_n_26), .C
       (sub_23_2_n_4), .Y (sub_23_2_n_27));
  ADDFX1 sub_23_2_g268(.A (sub_23_2_n_2), .B (in2[1]), .CI
       (sub_23_2_n_0), .CO (sub_23_2_n_26), .S (out1[1]));
  NOR3BX1 sub_23_2_g269(.AN (sub_23_2_n_11), .B (sub_23_2_n_23), .C
       (in2[7]), .Y (sub_23_2_n_24));
  NOR2BX1 sub_23_2_g270(.AN (sub_23_2_n_21), .B (sub_23_2_n_3), .Y
       (sub_23_2_n_23));
  NOR2BX1 sub_23_2_g271(.AN (sub_23_2_n_15), .B (sub_23_2_n_3), .Y
       (sub_23_2_n_22));
  OAI2BB1X1 sub_23_2_g272(.A0N (sub_23_2_n_6), .A1N (sub_23_2_n_5), .B0
       (sub_23_2_n_12), .Y (sub_23_2_n_21));
  NOR2BX1 sub_23_2_g273(.AN (sub_23_2_n_13), .B (sub_23_2_n_10), .Y
       (sub_23_2_n_20));
  NAND2X1 sub_23_2_g274(.A (sub_23_2_n_4), .B (sub_23_2_n_8), .Y
       (sub_23_2_n_19));
  NOR2BX1 sub_23_2_g275(.AN (sub_23_2_n_11), .B (sub_23_2_n_3), .Y
       (sub_23_2_n_18));
  NAND2BX1 sub_23_2_g276(.AN (sub_23_2_n_5), .B (sub_23_2_n_7), .Y
       (sub_23_2_n_17));
  AND2XL sub_23_2_g277(.A (sub_23_2_n_6), .B (sub_23_2_n_12), .Y
       (sub_23_2_n_16));
  AND2X1 sub_23_2_g278(.A (sub_23_2_n_6), .B (sub_23_2_n_7), .Y
       (sub_23_2_n_15));
  OAI2BB1X1 sub_23_2_g279(.A0N (in2[0]), .A1N (sub_23_2_n_1), .B0
       (sub_23_2_n_2), .Y (out1[0]));
  INVX1 sub_23_2_g280(.A (sub_23_2_n_8), .Y (sub_23_2_n_9));
  NAND2BXL sub_23_2_g281(.AN (in1[3]), .B (in2[3]), .Y (sub_23_2_n_13));
  NAND2BXL sub_23_2_g282(.AN (in1[5]), .B (in2[5]), .Y (sub_23_2_n_12));
  NAND2BX1 sub_23_2_g283(.AN (in1[6]), .B (in2[6]), .Y (sub_23_2_n_11));
  NOR2BX1 sub_23_2_g284(.AN (in1[3]), .B (in2[3]), .Y (sub_23_2_n_10));
  NAND2BX1 sub_23_2_g285(.AN (in1[2]), .B (in2[2]), .Y (sub_23_2_n_8));
  NAND2BX1 sub_23_2_g286(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_7));
  NAND2BX1 sub_23_2_g287(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_6));
  NOR2BX1 sub_23_2_g288(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_5));
  NAND2BX1 sub_23_2_g289(.AN (in2[2]), .B (in1[2]), .Y (sub_23_2_n_4));
  NOR2BX1 sub_23_2_g290(.AN (in1[6]), .B (in2[6]), .Y (sub_23_2_n_3));
  NAND2BX1 sub_23_2_g291(.AN (in2[0]), .B (in1[0]), .Y (sub_23_2_n_2));
  INVXL sub_23_2_g292(.A (in1[0]), .Y (sub_23_2_n_1));
  INVX1 sub_23_2_g293(.A (in1[1]), .Y (sub_23_2_n_0));
endmodule


