`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:04:22 CST (May 15 2023 01:04:22 UTC)

module Filter_Add_12Ux7U_12U_1(in2, in1, out1);
  input [11:0] in2;
  input [6:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [6:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_1, add_23_2_n_6, add_23_2_n_8, add_23_2_n_9,
       add_23_2_n_10, add_23_2_n_11, add_23_2_n_12, add_23_2_n_13;
  wire add_23_2_n_14, add_23_2_n_15, add_23_2_n_16, add_23_2_n_17,
       add_23_2_n_18, add_23_2_n_19, add_23_2_n_20, add_23_2_n_21;
  wire add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_25,
       add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29;
  wire add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33,
       add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37;
  wire add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41,
       add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45;
  wire add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49,
       add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53;
  wire add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57,
       add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61;
  wire add_23_2_n_62, add_23_2_n_63, add_23_2_n_64, n_90, n_91, n_92,
       n_94;
  MXI2X1 add_23_2_g243(.A (add_23_2_n_14), .B (in2[9]), .S0
       (add_23_2_n_63), .Y (out1[9]));
  MXI2X1 add_23_2_g244(.A (add_23_2_n_11), .B (in2[11]), .S0
       (add_23_2_n_62), .Y (out1[11]));
  MXI2X1 add_23_2_g245(.A (add_23_2_n_9), .B (in2[10]), .S0
       (add_23_2_n_64), .Y (out1[10]));
  MXI2XL add_23_2_g246(.A (in2[8]), .B (add_23_2_n_8), .S0
       (add_23_2_n_60), .Y (out1[8]));
  MXI2XL add_23_2_g247(.A (add_23_2_n_38), .B (add_23_2_n_37), .S0
       (add_23_2_n_6), .Y (out1[6]));
  MXI2XL add_23_2_g249(.A (in2[7]), .B (add_23_2_n_13), .S0
       (add_23_2_n_59), .Y (out1[7]));
  NOR2X1 add_23_2_g250(.A (add_23_2_n_20), .B (add_23_2_n_60), .Y
       (add_23_2_n_64));
  NOR2X1 add_23_2_g251(.A (add_23_2_n_8), .B (add_23_2_n_60), .Y
       (add_23_2_n_63));
  NOR2X1 add_23_2_g252(.A (add_23_2_n_35), .B (add_23_2_n_60), .Y
       (add_23_2_n_62));
  NOR2BX1 add_23_2_g254(.AN (add_23_2_n_16), .B (add_23_2_n_57), .Y
       (add_23_2_n_61));
  NOR2X2 add_23_2_g255(.A (add_23_2_n_49), .B (add_23_2_n_56), .Y
       (add_23_2_n_60));
  NOR2X1 add_23_2_g258(.A (add_23_2_n_50), .B (add_23_2_n_55), .Y
       (add_23_2_n_59));
  NOR2BX1 add_23_2_g259(.AN (add_23_2_n_36), .B (add_23_2_n_53), .Y
       (add_23_2_n_58));
  NOR2X1 add_23_2_g260(.A (add_23_2_n_22), .B (add_23_2_n_53), .Y
       (add_23_2_n_57));
  NOR2X4 add_23_2_g261(.A (add_23_2_n_45), .B (add_23_2_n_53), .Y
       (add_23_2_n_56));
  NOR2X1 add_23_2_g262(.A (add_23_2_n_46), .B (add_23_2_n_53), .Y
       (add_23_2_n_55));
  NOR2BX1 add_23_2_g263(.AN (add_23_2_n_24), .B (add_23_2_n_52), .Y
       (add_23_2_n_54));
  NOR2X2 add_23_2_g265(.A (add_23_2_n_44), .B (add_23_2_n_51), .Y
       (add_23_2_n_53));
  NOR2X1 add_23_2_g266(.A (add_23_2_n_25), .B (n_91), .Y
       (add_23_2_n_52));
  NOR2X2 add_23_2_g267(.A (add_23_2_n_1), .B (add_23_2_n_48), .Y
       (add_23_2_n_51));
  OAI21X1 add_23_2_g268(.A0 (add_23_2_n_15), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_18), .Y (add_23_2_n_50));
  OAI21X1 add_23_2_g269(.A0 (add_23_2_n_42), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_32), .Y (add_23_2_n_49));
  NOR2X2 add_23_2_g270(.A (add_23_2_n_29), .B (add_23_2_n_47), .Y
       (add_23_2_n_48));
  NOR2X2 add_23_2_g272(.A (add_23_2_n_19), .B (add_23_2_n_21), .Y
       (add_23_2_n_47));
  NAND2BX1 add_23_2_g274(.AN (add_23_2_n_15), .B (add_23_2_n_36), .Y
       (add_23_2_n_46));
  NAND2X1 add_23_2_g275(.A (add_23_2_n_41), .B (add_23_2_n_36), .Y
       (add_23_2_n_45));
  OAI21X1 add_23_2_g276(.A0 (add_23_2_n_23), .A1 (add_23_2_n_24), .B0
       (add_23_2_n_27), .Y (add_23_2_n_44));
  NOR2X1 add_23_2_g278(.A (add_23_2_n_28), .B (add_23_2_n_31), .Y
       (add_23_2_n_43));
  INVX1 add_23_2_g279(.A (add_23_2_n_41), .Y (add_23_2_n_42));
  INVX1 add_23_2_g282(.A (add_23_2_n_37), .Y (add_23_2_n_38));
  OR2XL add_23_2_g283(.A (add_23_2_n_9), .B (add_23_2_n_20), .Y
       (add_23_2_n_35));
  NOR2X1 add_23_2_g284(.A (add_23_2_n_13), .B (add_23_2_n_15), .Y
       (add_23_2_n_41));
  NOR2BX1 add_23_2_g285(.AN (add_23_2_n_27), .B (n_94), .Y
       (add_23_2_n_40));
  NAND2BX1 add_23_2_g286(.AN (add_23_2_n_22), .B (add_23_2_n_16), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g287(.AN (add_23_2_n_15), .B (add_23_2_n_18), .Y
       (add_23_2_n_37));
  NOR2X1 add_23_2_g288(.A (add_23_2_n_17), .B (add_23_2_n_22), .Y
       (add_23_2_n_36));
  OR2XL add_23_2_g293(.A (add_23_2_n_13), .B (add_23_2_n_18), .Y
       (add_23_2_n_32));
  NOR2X1 add_23_2_g294(.A (add_23_2_n_16), .B (add_23_2_n_17), .Y
       (add_23_2_n_31));
  NOR2X1 add_23_2_g295(.A (add_23_2_n_29), .B (add_23_2_n_21), .Y
       (add_23_2_n_30));
  NAND2X1 add_23_2_g296(.A (add_23_2_n_24), .B (add_23_2_n_26), .Y
       (add_23_2_n_34));
  NOR2X1 add_23_2_g297(.A (add_23_2_n_28), .B (add_23_2_n_17), .Y
       (add_23_2_n_33));
  INVX1 add_23_2_g298(.A (add_23_2_n_25), .Y (add_23_2_n_26));
  NOR2X2 add_23_2_g300(.A (add_23_2_n_10), .B (add_23_2_n_12), .Y
       (add_23_2_n_29));
  AND2X1 add_23_2_g301(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g302(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_27));
  NOR2X4 add_23_2_g303(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_25));
  NAND2X1 add_23_2_g304(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_24));
  NOR2X8 add_23_2_g305(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_23));
  NOR2X1 add_23_2_g306(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_22));
  NOR2X6 add_23_2_g307(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g308(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_20));
  NAND2X8 add_23_2_g309(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_19));
  NAND2X1 add_23_2_g310(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_18));
  NOR2X2 add_23_2_g311(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_17));
  NAND2X1 add_23_2_g312(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_16));
  NOR2X1 add_23_2_g313(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_15));
  INVXL add_23_2_g315(.A (in2[9]), .Y (add_23_2_n_14));
  INVX1 add_23_2_g316(.A (in2[7]), .Y (add_23_2_n_13));
  CLKINVX2 add_23_2_g317(.A (in1[1]), .Y (add_23_2_n_12));
  INVXL add_23_2_g318(.A (in2[11]), .Y (add_23_2_n_11));
  CLKINVX2 add_23_2_g319(.A (in2[1]), .Y (add_23_2_n_10));
  INVX1 add_23_2_g320(.A (in2[10]), .Y (add_23_2_n_9));
  INVX1 add_23_2_g321(.A (in2[8]), .Y (add_23_2_n_8));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_19), .B (add_23_2_n_30), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g322(.AN (add_23_2_n_43), .B (add_23_2_n_58), .Y
       (add_23_2_n_6));
  XNOR2XL add_23_2_g323(.A (add_23_2_n_40), .B (add_23_2_n_54), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g324(.A (add_23_2_n_39), .B (add_23_2_n_53), .Y
       (out1[4]));
  CLKXOR2X1 add_23_2_g325(.A (add_23_2_n_34), .B (n_90), .Y (out1[2]));
  XNOR2XL add_23_2_g326(.A (add_23_2_n_33), .B (add_23_2_n_61), .Y
       (out1[5]));
  NAND2BX1 add_23_2_g327(.AN (add_23_2_n_23), .B (add_23_2_n_26), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g328(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_92), .Y (n_90));
  INVXL fopt329(.A (n_92), .Y (n_91));
  INVXL fopt330(.A (add_23_2_n_48), .Y (n_92));
  BUFX2 fopt331(.A (add_23_2_n_23), .Y (n_94));
endmodule


