// Generated by stratus_hls 21.20-p100  (96289.240513)
// Mon May 15 09:19:21 2023
// from ../Filter.cpp

`timescale 1ps / 1ps


module Filter_RAM_3X12_4( DIN, CE, RW, in1, out1, clk );

    input [11:0] DIN;
    input CE;
    input RW;
    input [1:0] in1;
    input clk;
    output [11:0] out1;
    reg [11:0] out1;
    reg[11:0] mem[2:0];

    
always @(posedge clk)
      begin : Filter_RAM_3X12_4_thread_1
        if (in1 < 2'd3) 
          begin
            if (CE) 
              begin
                if (RW) 
                  begin
                    mem[in1] = DIN;
                  end 
                else 
                  begin
                    out1 <= mem[in1];
                  end
              end 
            else 
              begin
                out1 <= 12'd0000;
              end
          end 
      end

endmodule

