// Generated by stratus_hls 21.20-p100  (96289.240513)
// Mon May 15 09:19:21 2023
// from ../Filter.cpp
#include "Filter_RAM_18X8_2.h"

struct Filter_RAM_18X8_2;
Filter_RAM_18X8_2::Filter_RAM_18X8_2(sc_module_name name) : sc_module(name) 
    ,DIN("DIN")
    ,CE("CE")
    ,RW("RW")
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,mem()
{
  SC_METHOD(Filter_RAM_18X8_2_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void Filter_RAM_18X8_2::Filter_RAM_18X8_2_thread_1(){
  if ( (/*imp*/sc_uint<1>)(in1.read() < ((/*imp*/sc_uint<5> )(18ULL))) ) {
    if ( CE.read() ) {
      if ( RW.read() ) {
        (mem)[in1.read()] = DIN.read();
      } else {
        out1 = (mem)[in1.read()];
      }
    } else {
      out1 = 0ULL;
    }
  } 
}
