// Generated by stratus_hls 21.20-p100  (96289.240513)
// Mon May 15 07:59:21 2023
// from ../Filter.cpp
#ifndef CYNTH_PART_Filter_Filter_Div_31Ux3U_31U_4_h
#define CYNTH_PART_Filter_Filter_Div_31Ux3U_31U_4_h

#include "systemc.h"
#include "stratus_hls.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct Filter_Div_31Ux3U_31U_4 : public sc_module {
  sc_in<sc_uint<31> > in2;
  sc_in<sc_uint<3> > in1;
  sc_out<sc_uint<31> > out1;
  sc_in<bool > clk;
  sc_in<sc_uint<1> > stall;
  Filter_Div_31Ux3U_31U_4( sc_module_name name );
  SC_HAS_PROCESS(Filter_Div_31Ux3U_31U_4);
  sc_uint<31> out1_0;
  void Filter_Div_31Ux3U_31U_4_thread_1();
};

#endif
