// Generated by stratus_hls 21.20-p100  (96289.240513)
// Mon May 15 07:59:21 2023
// from ../Filter.cpp
#include "Filter_Div_31Ux3U_31U_4.h"

struct Filter_Div_31Ux3U_31U_4;
Filter_Div_31Ux3U_31U_4::Filter_Div_31Ux3U_31U_4(sc_module_name name) : sc_module(name) 
    ,in2("in2")
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,stall("stall")
{
  SC_METHOD(Filter_Div_31Ux3U_31U_4_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void Filter_Div_31Ux3U_31U_4::Filter_Div_31Ux3U_31U_4_thread_1(){
  out1_0 = (/*cliff*/sc_uint<32>)(in1.read() == 0 ? ((sc_uint<31> ) -1) : (
           sc_uint<31> ) (in2.read() / in1.read()));
  if ( !stall.read() ) {
    out1 = out1_0;
  } 
}
