`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:17 CST (May 15 2023 01:19:17 UTC)

module Filter_Mul_4Ux2U_5U_1(in2, in1, out1);
  input [3:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire mul_22_8_n_2, mul_22_8_n_3, mul_22_8_n_4, mul_22_8_n_5,
       mul_22_8_n_6, mul_22_8_n_7, mul_22_8_n_8, mul_22_8_n_9;
  wire mul_22_8_n_10, mul_22_8_n_11, mul_22_8_n_12, mul_22_8_n_13,
       mul_22_8_n_14, mul_22_8_n_15, mul_22_8_n_17, mul_22_8_n_18;
  wire mul_22_8_n_19, mul_22_8_n_20, mul_22_8_n_21, mul_22_8_n_22,
       mul_22_8_n_23, mul_22_8_n_25, mul_22_8_n_26, n_34;
  wire n_35, n_36;
  MXI2XL mul_22_8_g160(.A (mul_22_8_n_18), .B (mul_22_8_n_17), .S0
       (mul_22_8_n_26), .Y (out1[3]));
  AOI21X1 mul_22_8_g162(.A0 (n_35), .A1 (mul_22_8_n_14), .B0
       (mul_22_8_n_11), .Y (mul_22_8_n_26));
  NOR2X1 mul_22_8_g163(.A (mul_22_8_n_23), .B (mul_22_8_n_2), .Y
       (mul_22_8_n_25));
  MXI2XL mul_22_8_g164(.A (mul_22_8_n_14), .B (mul_22_8_n_22), .S0
       (mul_22_8_n_21), .Y (out1[2]));
  NOR2X1 mul_22_8_g165(.A (mul_22_8_n_22), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_23));
  INVX1 mul_22_8_g166(.A (mul_22_8_n_14), .Y (mul_22_8_n_22));
  NAND2BX1 mul_22_8_g168(.AN (mul_22_8_n_11), .B (n_34), .Y
       (mul_22_8_n_21));
  NAND2X1 mul_22_8_g169(.A (mul_22_8_n_11), .B (mul_22_8_n_10), .Y
       (mul_22_8_n_20));
  NAND2X1 mul_22_8_g170(.A (mul_22_8_n_10), .B (mul_22_8_n_15), .Y
       (mul_22_8_n_19));
  INVX1 mul_22_8_g171(.A (mul_22_8_n_17), .Y (mul_22_8_n_18));
  NAND2BX1 mul_22_8_g172(.AN (mul_22_8_n_12), .B (mul_22_8_n_10), .Y
       (mul_22_8_n_17));
  NOR2BX1 mul_22_8_g173(.AN (mul_22_8_n_13), .B (mul_22_8_n_14), .Y
       (out1[1]));
  NAND2X1 mul_22_8_g174(.A (mul_22_8_n_5), .B (mul_22_8_n_9), .Y
       (mul_22_8_n_15));
  NOR2X4 mul_22_8_g175(.A (mul_22_8_n_7), .B (mul_22_8_n_8), .Y
       (mul_22_8_n_14));
  NAND2X1 mul_22_8_g176(.A (mul_22_8_n_7), .B (mul_22_8_n_8), .Y
       (mul_22_8_n_13));
  NOR2X1 mul_22_8_g178(.A (mul_22_8_n_6), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_12));
  NOR2X2 mul_22_8_g179(.A (mul_22_8_n_5), .B (mul_22_8_n_9), .Y
       (mul_22_8_n_11));
  NAND2X4 mul_22_8_g180(.A (mul_22_8_n_6), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_10));
  NAND2X4 mul_22_8_g181(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_9));
  NAND2X4 mul_22_8_g182(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_8));
  NAND2X6 mul_22_8_g183(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_7));
  NAND2X8 mul_22_8_g184(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_6));
  NAND2X6 mul_22_8_g185(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_5));
  NAND2X4 mul_22_8_g186(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_4));
  NAND2X1 mul_22_8_g188(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_3));
  NAND2BX1 mul_22_8_g2(.AN (mul_22_8_n_12), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_2));
  CLKXOR2X1 mul_22_8_g192(.A (mul_22_8_n_3), .B (mul_22_8_n_25), .Y
       (out1[4]));
  AND2X1 mul_22_8_g193(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_36), .Y (n_34));
  INVXL fopt194(.A (n_36), .Y (n_35));
  INVXL fopt195(.A (mul_22_8_n_15), .Y (n_36));
endmodule

