`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:14 CST (May 15 2023 01:19:14 UTC)

module Filter_Add_5Ux1U_5U_1(in2, in1, out1);
  input [4:0] in2;
  input in1;
  output [4:0] out1;
  wire [4:0] in2;
  wire in1;
  wire [4:0] out1;
  wire inc_add_23_2_1_n_0, inc_add_23_2_1_n_1, inc_add_23_2_1_n_2,
       inc_add_23_2_1_n_3, inc_add_23_2_1_n_4, inc_add_23_2_1_n_5,
       inc_add_23_2_1_n_6, inc_add_23_2_1_n_8;
  wire inc_add_23_2_1_n_11, inc_add_23_2_1_n_12, n_25, n_26, n_27;
  MXI2XL inc_add_23_2_1_g42(.A (inc_add_23_2_1_n_2), .B (in2[3]), .S0
       (inc_add_23_2_1_n_12), .Y (out1[3]));
  MXI2XL inc_add_23_2_1_g43(.A (inc_add_23_2_1_n_4), .B (in2[4]), .S0
       (inc_add_23_2_1_n_11), .Y (out1[4]));
  MXI2XL inc_add_23_2_1_g44(.A (inc_add_23_2_1_n_1), .B (in2[2]), .S0
       (n_25), .Y (out1[2]));
  NOR2X1 inc_add_23_2_1_g45(.A (inc_add_23_2_1_n_1), .B (n_26), .Y
       (inc_add_23_2_1_n_12));
  NOR2X1 inc_add_23_2_1_g46(.A (inc_add_23_2_1_n_6), .B (n_26), .Y
       (inc_add_23_2_1_n_11));
  MXI2XL inc_add_23_2_1_g48(.A (in2[1]), .B (inc_add_23_2_1_n_3), .S0
       (n_27), .Y (out1[1]));
  NOR2X2 inc_add_23_2_1_g49(.A (inc_add_23_2_1_n_3), .B
       (inc_add_23_2_1_n_5), .Y (inc_add_23_2_1_n_8));
  MXI2XL inc_add_23_2_1_g50(.A (inc_add_23_2_1_n_0), .B (in2[0]), .S0
       (in1), .Y (out1[0]));
  NAND2X1 inc_add_23_2_1_g51(.A (in2[3]), .B (in2[2]), .Y
       (inc_add_23_2_1_n_6));
  NAND2X8 inc_add_23_2_1_g52(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_5));
  INVXL inc_add_23_2_1_g53(.A (in2[4]), .Y (inc_add_23_2_1_n_4));
  INVX1 inc_add_23_2_1_g54(.A (in2[1]), .Y (inc_add_23_2_1_n_3));
  INVXL inc_add_23_2_1_g55(.A (in2[3]), .Y (inc_add_23_2_1_n_2));
  INVX1 inc_add_23_2_1_g56(.A (in2[2]), .Y (inc_add_23_2_1_n_1));
  INVX1 inc_add_23_2_1_g57(.A (in2[0]), .Y (inc_add_23_2_1_n_0));
  INVXL fopt(.A (n_26), .Y (n_25));
  CLKINVX2 fopt59(.A (inc_add_23_2_1_n_8), .Y (n_26));
  BUFX2 fopt60(.A (inc_add_23_2_1_n_5), .Y (n_27));
endmodule

