`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:20 CST (May 15 2023 01:19:20 UTC)

module Filter_Add_6U_3_4(in1, out1);
  input [5:0] in1;
  output [5:0] out1;
  wire [5:0] in1;
  wire [5:0] out1;
  wire inc_add_21_2_1_n_0, inc_add_21_2_1_n_2, inc_add_21_2_1_n_3,
       inc_add_21_2_1_n_5;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_21_2_1_g47(.A (in1[5]), .B (inc_add_21_2_1_n_5), .Y
       (out1[5]));
  XNOR2X1 inc_add_21_2_1_g48(.A (in1[3]), .B (inc_add_21_2_1_n_3), .Y
       (out1[3]));
  XNOR2X1 inc_add_21_2_1_g49(.A (in1[4]), .B (inc_add_21_2_1_n_2), .Y
       (out1[4]));
  NAND2BX1 inc_add_21_2_1_g50(.AN (inc_add_21_2_1_n_2), .B (in1[4]), .Y
       (inc_add_21_2_1_n_5));
  XNOR2X1 inc_add_21_2_1_g51(.A (in1[2]), .B (inc_add_21_2_1_n_0), .Y
       (out1[2]));
  NAND2BX1 inc_add_21_2_1_g52(.AN (inc_add_21_2_1_n_0), .B (in1[2]), .Y
       (inc_add_21_2_1_n_3));
  NAND3BXL inc_add_21_2_1_g53(.AN (inc_add_21_2_1_n_0), .B (in1[3]), .C
       (in1[2]), .Y (inc_add_21_2_1_n_2));
  XOR2XL inc_add_21_2_1_g54(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_21_2_1_g55(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_1_n_0));
endmodule

