`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:09 CST (May 15 2023 01:19:09 UTC)

module Filter_Sub_12Ux8U_12U_1(in2, in1, out1);
  input [11:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire sub_23_2_n_0, sub_23_2_n_2, sub_23_2_n_3, sub_23_2_n_4,
       sub_23_2_n_5, sub_23_2_n_6, sub_23_2_n_7, sub_23_2_n_8;
  wire sub_23_2_n_12, sub_23_2_n_16, sub_23_2_n_18, sub_23_2_n_19,
       sub_23_2_n_20, sub_23_2_n_21, sub_23_2_n_22, sub_23_2_n_23;
  wire sub_23_2_n_24, sub_23_2_n_25, sub_23_2_n_26, sub_23_2_n_27,
       sub_23_2_n_28, sub_23_2_n_29, sub_23_2_n_30, sub_23_2_n_31;
  wire sub_23_2_n_32, sub_23_2_n_33, sub_23_2_n_34, sub_23_2_n_35,
       sub_23_2_n_36, sub_23_2_n_37, sub_23_2_n_38, sub_23_2_n_39;
  wire sub_23_2_n_40, sub_23_2_n_42, sub_23_2_n_43, sub_23_2_n_44,
       sub_23_2_n_45, sub_23_2_n_46, sub_23_2_n_47, sub_23_2_n_48;
  wire sub_23_2_n_49, sub_23_2_n_50, sub_23_2_n_51, sub_23_2_n_52,
       sub_23_2_n_53, sub_23_2_n_54, sub_23_2_n_55, sub_23_2_n_56;
  wire sub_23_2_n_57, sub_23_2_n_58, sub_23_2_n_59, sub_23_2_n_60,
       sub_23_2_n_61, sub_23_2_n_62, sub_23_2_n_63, sub_23_2_n_64;
  wire sub_23_2_n_65, sub_23_2_n_66, sub_23_2_n_67, sub_23_2_n_68,
       sub_23_2_n_69, sub_23_2_n_70;
  MXI2X1 sub_23_2_g278(.A (sub_23_2_n_19), .B (in2[9]), .S0
       (sub_23_2_n_18), .Y (out1[9]));
  MXI2XL sub_23_2_g279(.A (in2[10]), .B (sub_23_2_n_24), .S0
       (sub_23_2_n_70), .Y (out1[10]));
  MXI2XL sub_23_2_g280(.A (in2[11]), .B (sub_23_2_n_20), .S0
       (sub_23_2_n_69), .Y (out1[11]));
  NAND2X1 sub_23_2_g286(.A (sub_23_2_n_39), .B (sub_23_2_n_67), .Y
       (sub_23_2_n_70));
  NAND2X1 sub_23_2_g287(.A (sub_23_2_n_46), .B (sub_23_2_n_67), .Y
       (sub_23_2_n_69));
  NOR2X1 sub_23_2_g289(.A (sub_23_2_n_3), .B (sub_23_2_n_65), .Y
       (sub_23_2_n_68));
  NOR2X4 sub_23_2_g291(.A (sub_23_2_n_57), .B (sub_23_2_n_64), .Y
       (sub_23_2_n_67));
  NOR2X1 sub_23_2_g294(.A (sub_23_2_n_58), .B (sub_23_2_n_63), .Y
       (sub_23_2_n_66));
  NOR2X1 sub_23_2_g296(.A (sub_23_2_n_5), .B (sub_23_2_n_61), .Y
       (sub_23_2_n_65));
  NOR2X2 sub_23_2_g297(.A (sub_23_2_n_55), .B (sub_23_2_n_61), .Y
       (sub_23_2_n_64));
  NOR2X1 sub_23_2_g298(.A (sub_23_2_n_54), .B (sub_23_2_n_61), .Y
       (sub_23_2_n_63));
  AOI21X1 sub_23_2_g299(.A0 (sub_23_2_n_30), .A1 (sub_23_2_n_59), .B0
       (sub_23_2_n_29), .Y (sub_23_2_n_62));
  NOR2X4 sub_23_2_g301(.A (sub_23_2_n_53), .B (sub_23_2_n_60), .Y
       (sub_23_2_n_61));
  NOR2X2 sub_23_2_g302(.A (sub_23_2_n_45), .B (sub_23_2_n_56), .Y
       (sub_23_2_n_60));
  INVX1 sub_23_2_g303(.A (sub_23_2_n_56), .Y (sub_23_2_n_59));
  OAI21X1 sub_23_2_g304(.A0 (sub_23_2_n_2), .A1 (sub_23_2_n_52), .B0
       (sub_23_2_n_35), .Y (sub_23_2_n_58));
  OAI21X2 sub_23_2_g305(.A0 (sub_23_2_n_52), .A1 (sub_23_2_n_43), .B0
       (sub_23_2_n_51), .Y (sub_23_2_n_57));
  AOI21X4 sub_23_2_g306(.A0 (sub_23_2_n_32), .A1 (sub_23_2_n_27), .B0
       (sub_23_2_n_37), .Y (sub_23_2_n_56));
  NAND2X1 sub_23_2_g309(.A (sub_23_2_n_7), .B (sub_23_2_n_47), .Y
       (sub_23_2_n_55));
  NAND2BX1 sub_23_2_g310(.AN (sub_23_2_n_2), .B (sub_23_2_n_47), .Y
       (sub_23_2_n_54));
  NAND2X2 sub_23_2_g311(.A (sub_23_2_n_38), .B (sub_23_2_n_40), .Y
       (sub_23_2_n_53));
  AOI21X4 sub_23_2_g313(.A0 (sub_23_2_n_3), .A1 (sub_23_2_n_0), .B0
       (sub_23_2_n_33), .Y (sub_23_2_n_52));
  AOI21X1 sub_23_2_g314(.A0 (sub_23_2_n_34), .A1 (sub_23_2_n_4), .B0
       (sub_23_2_n_36), .Y (sub_23_2_n_51));
  AND2XL sub_23_2_g319(.A (sub_23_2_n_24), .B (sub_23_2_n_39), .Y
       (sub_23_2_n_46));
  NAND2X1 sub_23_2_g320(.A (sub_23_2_n_28), .B (sub_23_2_n_30), .Y
       (sub_23_2_n_45));
  NOR2X1 sub_23_2_g321(.A (sub_23_2_n_5), .B (sub_23_2_n_3), .Y
       (sub_23_2_n_50));
  NAND2X1 sub_23_2_g322(.A (sub_23_2_n_28), .B (sub_23_2_n_38), .Y
       (sub_23_2_n_49));
  NOR2BX1 sub_23_2_g323(.AN (sub_23_2_n_34), .B (sub_23_2_n_36), .Y
       (sub_23_2_n_48));
  NOR2X2 sub_23_2_g324(.A (sub_23_2_n_5), .B (sub_23_2_n_31), .Y
       (sub_23_2_n_47));
  INVX2 sub_23_2_g327(.A (sub_23_2_n_7), .Y (sub_23_2_n_43));
  MXI2XL sub_23_2_g329(.A (sub_23_2_n_25), .B (in2[0]), .S0 (in1[0]),
       .Y (out1[0]));
  NAND2X2 sub_23_2_g330(.A (sub_23_2_n_29), .B (sub_23_2_n_28), .Y
       (sub_23_2_n_40));
  NOR2X1 sub_23_2_g333(.A (sub_23_2_n_31), .B (sub_23_2_n_33), .Y
       (sub_23_2_n_44));
  NOR2X1 sub_23_2_g335(.A (sub_23_2_n_2), .B (sub_23_2_n_4), .Y
       (sub_23_2_n_42));
  INVX1 sub_23_2_g337(.A (sub_23_2_n_4), .Y (sub_23_2_n_35));
  NOR2X1 sub_23_2_g339(.A (in2[9]), .B (in2[8]), .Y (sub_23_2_n_39));
  NAND2BX1 sub_23_2_g340(.AN (in1[3]), .B (in2[3]), .Y (sub_23_2_n_38));
  NOR2X2 sub_23_2_g341(.A (sub_23_2_n_21), .B (in1[1]), .Y
       (sub_23_2_n_37));
  NOR2BX1 sub_23_2_g342(.AN (in2[7]), .B (in1[7]), .Y (sub_23_2_n_36));
  NAND2X2 sub_23_2_g345(.A (in1[7]), .B (sub_23_2_n_22), .Y
       (sub_23_2_n_34));
  CLKINVX2 sub_23_2_g347(.A (sub_23_2_n_0), .Y (sub_23_2_n_31));
  NOR2BX1 sub_23_2_g349(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_33));
  NAND2X4 sub_23_2_g350(.A (in1[1]), .B (sub_23_2_n_21), .Y
       (sub_23_2_n_32));
  NAND2X2 sub_23_2_g352(.A (in1[2]), .B (sub_23_2_n_26), .Y
       (sub_23_2_n_30));
  NOR2X2 sub_23_2_g353(.A (sub_23_2_n_26), .B (in1[2]), .Y
       (sub_23_2_n_29));
  NAND2X4 sub_23_2_g354(.A (in1[3]), .B (sub_23_2_n_23), .Y
       (sub_23_2_n_28));
  NAND2X4 sub_23_2_g355(.A (in1[0]), .B (sub_23_2_n_25), .Y
       (sub_23_2_n_27));
  INVX2 sub_23_2_g359(.A (in2[2]), .Y (sub_23_2_n_26));
  CLKINVX2 sub_23_2_g362(.A (in2[0]), .Y (sub_23_2_n_25));
  INVX1 sub_23_2_g363(.A (in2[10]), .Y (sub_23_2_n_24));
  INVX2 sub_23_2_g365(.A (in2[3]), .Y (sub_23_2_n_23));
  CLKINVX2 sub_23_2_g366(.A (in2[7]), .Y (sub_23_2_n_22));
  CLKINVX4 sub_23_2_g367(.A (in2[1]), .Y (sub_23_2_n_21));
  INVXL sub_23_2_g368(.A (in2[11]), .Y (sub_23_2_n_20));
  INVXL sub_23_2_g370(.A (in2[9]), .Y (sub_23_2_n_19));
  NOR2BX1 sub_23_2_g2(.AN (sub_23_2_n_67), .B (in2[8]), .Y
       (sub_23_2_n_18));
  XNOR2X1 sub_23_2_g371(.A (sub_23_2_n_27), .B (sub_23_2_n_8), .Y
       (out1[1]));
  NOR2BX1 sub_23_2_g372(.AN (sub_23_2_n_52), .B (sub_23_2_n_12), .Y
       (sub_23_2_n_16));
  XNOR2X1 sub_23_2_g373(.A (sub_23_2_n_50), .B (sub_23_2_n_61), .Y
       (out1[4]));
  CLKXOR2X1 sub_23_2_g374(.A (sub_23_2_n_49), .B (sub_23_2_n_62), .Y
       (out1[3]));
  XNOR2XL sub_23_2_g375(.A (sub_23_2_n_48), .B (sub_23_2_n_66), .Y
       (out1[7]));
  NOR2BX1 sub_23_2_g376(.AN (sub_23_2_n_47), .B (sub_23_2_n_61), .Y
       (sub_23_2_n_12));
  CLKXOR2X1 sub_23_2_g377(.A (sub_23_2_n_6), .B (sub_23_2_n_56), .Y
       (out1[2]));
  XNOR2XL sub_23_2_g378(.A (sub_23_2_n_44), .B (sub_23_2_n_68), .Y
       (out1[5]));
  XNOR2XL sub_23_2_g379(.A (sub_23_2_n_42), .B (sub_23_2_n_16), .Y
       (out1[6]));
  NAND2BX1 sub_23_2_g380(.AN (sub_23_2_n_37), .B (sub_23_2_n_32), .Y
       (sub_23_2_n_8));
  NOR2BX2 sub_23_2_g381(.AN (sub_23_2_n_34), .B (sub_23_2_n_2), .Y
       (sub_23_2_n_7));
  NAND2BX1 sub_23_2_g382(.AN (sub_23_2_n_29), .B (sub_23_2_n_30), .Y
       (sub_23_2_n_6));
  NOR2BX1 sub_23_2_g383(.AN (in1[4]), .B (in2[4]), .Y (sub_23_2_n_5));
  NOR2BX1 sub_23_2_g384(.AN (in2[6]), .B (in1[6]), .Y (sub_23_2_n_4));
  NOR2BX2 sub_23_2_g385(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_3));
  NOR2BX2 sub_23_2_g386(.AN (in1[6]), .B (in2[6]), .Y (sub_23_2_n_2));
  XOR2XL sub_23_2_g387(.A (in2[8]), .B (sub_23_2_n_67), .Y (out1[8]));
  NAND2BX4 sub_23_2_g388(.AN (in2[5]), .B (in1[5]), .Y (sub_23_2_n_0));
endmodule

