`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 07:26:57 CST (May 14 2023 23:26:57 UTC)

module Filter_Not_1U_1U_1(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  CLKINVX12 g2(.A (in1), .Y (out1));
endmodule


