`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 07:27:48 CST (May 14 2023 23:27:48 UTC)

module Filter_Sub_32Ux8U_32S_1(in2, in1, out1);
  input [31:0] in2;
  input [7:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [7:0] in1;
  wire [31:0] out1;
  wire n_208, n_209, n_213, n_214, n_215, n_217, n_218, n_220;
  wire n_221, n_222, n_223, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_233, n_236, n_237, sub_23_2_n_3, sub_23_2_n_4,
       sub_23_2_n_5;
  wire sub_23_2_n_6, sub_23_2_n_9, sub_23_2_n_10, sub_23_2_n_11,
       sub_23_2_n_12, sub_23_2_n_13, sub_23_2_n_20, sub_23_2_n_22;
  wire sub_23_2_n_23, sub_23_2_n_24, sub_23_2_n_25, sub_23_2_n_26,
       sub_23_2_n_27, sub_23_2_n_28, sub_23_2_n_29, sub_23_2_n_31;
  wire sub_23_2_n_33, sub_23_2_n_34, sub_23_2_n_35, sub_23_2_n_36,
       sub_23_2_n_37, sub_23_2_n_38, sub_23_2_n_39, sub_23_2_n_40;
  wire sub_23_2_n_41, sub_23_2_n_42, sub_23_2_n_43, sub_23_2_n_44,
       sub_23_2_n_45, sub_23_2_n_47, sub_23_2_n_48, sub_23_2_n_49;
  wire sub_23_2_n_50, sub_23_2_n_51, sub_23_2_n_52, sub_23_2_n_53,
       sub_23_2_n_54, sub_23_2_n_55, sub_23_2_n_56, sub_23_2_n_57;
  wire sub_23_2_n_58, sub_23_2_n_59, sub_23_2_n_60, sub_23_2_n_61,
       sub_23_2_n_62, sub_23_2_n_63, sub_23_2_n_64, sub_23_2_n_65;
  wire sub_23_2_n_66, sub_23_2_n_67, sub_23_2_n_68, sub_23_2_n_69,
       sub_23_2_n_71, sub_23_2_n_72, sub_23_2_n_73, sub_23_2_n_74;
  wire sub_23_2_n_75, sub_23_2_n_76, sub_23_2_n_77, sub_23_2_n_78,
       sub_23_2_n_79, sub_23_2_n_80, sub_23_2_n_81, sub_23_2_n_82;
  wire sub_23_2_n_83, sub_23_2_n_84, sub_23_2_n_85, sub_23_2_n_86,
       sub_23_2_n_87, sub_23_2_n_88, sub_23_2_n_89, sub_23_2_n_90;
  wire sub_23_2_n_91, sub_23_2_n_92, sub_23_2_n_93, sub_23_2_n_94,
       sub_23_2_n_95, sub_23_2_n_96, sub_23_2_n_97, sub_23_2_n_98;
  wire sub_23_2_n_99, sub_23_2_n_100, sub_23_2_n_101, sub_23_2_n_102,
       sub_23_2_n_103, sub_23_2_n_104, sub_23_2_n_105, sub_23_2_n_106;
  wire sub_23_2_n_107, sub_23_2_n_108, sub_23_2_n_109, sub_23_2_n_110,
       sub_23_2_n_111, sub_23_2_n_112, sub_23_2_n_113, sub_23_2_n_115;
  wire sub_23_2_n_116, sub_23_2_n_117, sub_23_2_n_118, sub_23_2_n_119,
       sub_23_2_n_120, sub_23_2_n_121, sub_23_2_n_122, sub_23_2_n_124;
  wire sub_23_2_n_125, sub_23_2_n_126, sub_23_2_n_127, sub_23_2_n_128,
       sub_23_2_n_129, sub_23_2_n_130, sub_23_2_n_131, sub_23_2_n_132;
  wire sub_23_2_n_133, sub_23_2_n_134, sub_23_2_n_135, sub_23_2_n_136,
       sub_23_2_n_137, sub_23_2_n_138, sub_23_2_n_139, sub_23_2_n_140;
  wire sub_23_2_n_141, sub_23_2_n_142, sub_23_2_n_143, sub_23_2_n_144,
       sub_23_2_n_145, sub_23_2_n_146, sub_23_2_n_147, sub_23_2_n_148;
  MXI2XL sub_23_2_g818(.A (sub_23_2_n_42), .B (in2[17]), .S0
       (sub_23_2_n_148), .Y (out1[17]));
  MXI2XL sub_23_2_g819(.A (sub_23_2_n_27), .B (in2[9]), .S0
       (sub_23_2_n_133), .Y (out1[9]));
  MXI2XL sub_23_2_g820(.A (sub_23_2_n_43), .B (in2[21]), .S0
       (sub_23_2_n_139), .Y (out1[21]));
  MXI2XL sub_23_2_g821(.A (sub_23_2_n_23), .B (in2[28]), .S0
       (sub_23_2_n_144), .Y (out1[28]));
  MXI2XL sub_23_2_g822(.A (sub_23_2_n_33), .B (in2[18]), .S0
       (sub_23_2_n_13), .Y (out1[18]));
  MXI2XL sub_23_2_g823(.A (sub_23_2_n_44), .B (in2[31]), .S0
       (sub_23_2_n_145), .Y (out1[31]));
  MXI2XL sub_23_2_g824(.A (sub_23_2_n_25), .B (in2[22]), .S0
       (sub_23_2_n_142), .Y (out1[22]));
  MXI2XL sub_23_2_g825(.A (sub_23_2_n_35), .B (in2[26]), .S0
       (sub_23_2_n_141), .Y (out1[26]));
  MXI2XL sub_23_2_g826(.A (in2[30]), .B (sub_23_2_n_36), .S0
       (sub_23_2_n_137), .Y (out1[30]));
  MXI2XL sub_23_2_g827(.A (sub_23_2_n_28), .B (in2[27]), .S0
       (sub_23_2_n_135), .Y (out1[27]));
  MXI2XL sub_23_2_g828(.A (sub_23_2_n_24), .B (in2[24]), .S0
       (sub_23_2_n_146), .Y (out1[24]));
  MXI2XL sub_23_2_g829(.A (sub_23_2_n_40), .B (in2[25]), .S0
       (sub_23_2_n_140), .Y (out1[25]));
  MXI2XL sub_23_2_g830(.A (sub_23_2_n_41), .B (in2[19]), .S0
       (sub_23_2_n_138), .Y (out1[19]));
  MXI2XL sub_23_2_g831(.A (sub_23_2_n_29), .B (in2[23]), .S0
       (sub_23_2_n_143), .Y (out1[23]));
  MXI2XL sub_23_2_g832(.A (sub_23_2_n_39), .B (in2[29]), .S0
       (sub_23_2_n_136), .Y (out1[29]));
  MXI2XL sub_23_2_g833(.A (sub_23_2_n_34), .B (in2[20]), .S0
       (sub_23_2_n_147), .Y (out1[20]));
  MXI2XL sub_23_2_g834(.A (in2[10]), .B (sub_23_2_n_22), .S0
       (sub_23_2_n_134), .Y (out1[10]));
  MXI2XL sub_23_2_g835(.A (in2[14]), .B (sub_23_2_n_26), .S0
       (sub_23_2_n_129), .Y (out1[14]));
  MXI2XL sub_23_2_g840(.A (sub_23_2_n_37), .B (in2[15]), .S0
       (sub_23_2_n_128), .Y (out1[15]));
  NOR2XL sub_23_2_g842(.A (in2[16]), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_148));
  NOR2XL sub_23_2_g843(.A (sub_23_2_n_74), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_147));
  NOR2XL sub_23_2_g844(.A (sub_23_2_n_94), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_146));
  NOR2XL sub_23_2_g845(.A (sub_23_2_n_106), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_145));
  NOR2XL sub_23_2_g846(.A (sub_23_2_n_109), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_144));
  NOR2XL sub_23_2_g847(.A (sub_23_2_n_91), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_143));
  NOR2XL sub_23_2_g848(.A (sub_23_2_n_97), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_142));
  NOR2XL sub_23_2_g853(.A (sub_23_2_n_108), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_141));
  NOR2XL sub_23_2_g854(.A (sub_23_2_n_110), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_140));
  NOR2XL sub_23_2_g855(.A (sub_23_2_n_102), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_139));
  NOR2XL sub_23_2_g856(.A (sub_23_2_n_82), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_138));
  NAND2X1 sub_23_2_g857(.A (sub_23_2_n_107), .B (sub_23_2_n_132), .Y
       (sub_23_2_n_137));
  NOR2XL sub_23_2_g858(.A (sub_23_2_n_105), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_136));
  NOR2XL sub_23_2_g859(.A (sub_23_2_n_104), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_135));
  NAND2X1 sub_23_2_g860(.A (sub_23_2_n_53), .B (n_209), .Y
       (sub_23_2_n_134));
  NOR2X1 sub_23_2_g861(.A (in2[8]), .B (n_208), .Y (sub_23_2_n_133));
  CLKINVX4 sub_23_2_g862(.A (sub_23_2_n_132), .Y (sub_23_2_n_131));
  CLKAND2X6 sub_23_2_g863(.A (sub_23_2_n_92), .B (sub_23_2_n_124), .Y
       (sub_23_2_n_132));
  NAND2X1 sub_23_2_g864(.A (sub_23_2_n_71), .B (n_209), .Y
       (sub_23_2_n_130));
  NAND2X1 sub_23_2_g865(.A (sub_23_2_n_101), .B (n_209), .Y
       (sub_23_2_n_129));
  NOR2X1 sub_23_2_g866(.A (sub_23_2_n_93), .B (n_208), .Y
       (sub_23_2_n_128));
  NAND2X1 sub_23_2_g867(.A (sub_23_2_n_100), .B (n_209), .Y
       (sub_23_2_n_127));
  NAND2X1 sub_23_2_g868(.A (sub_23_2_n_81), .B (n_209), .Y
       (sub_23_2_n_126));
  NOR2X1 sub_23_2_g870(.A (sub_23_2_n_9), .B (sub_23_2_n_121), .Y
       (sub_23_2_n_125));
  NOR2X4 sub_23_2_g872(.A (sub_23_2_n_112), .B (sub_23_2_n_119), .Y
       (sub_23_2_n_124));
  NOR2X1 sub_23_2_g875(.A (sub_23_2_n_113), .B (sub_23_2_n_118), .Y
       (sub_23_2_n_122));
  NOR2X1 sub_23_2_g876(.A (sub_23_2_n_4), .B (n_233), .Y
       (sub_23_2_n_121));
  NOR2X1 sub_23_2_g877(.A (sub_23_2_n_85), .B (n_233), .Y
       (sub_23_2_n_120));
  NOR2X4 sub_23_2_g878(.A (sub_23_2_n_98), .B (sub_23_2_n_116), .Y
       (sub_23_2_n_119));
  NOR2X1 sub_23_2_g879(.A (sub_23_2_n_103), .B (n_233), .Y
       (sub_23_2_n_118));
  AOI21X1 sub_23_2_g880(.A0 (sub_23_2_n_55), .A1 (n_218), .B0 (n_214),
       .Y (sub_23_2_n_117));
  NOR2X6 sub_23_2_g882(.A (sub_23_2_n_90), .B (sub_23_2_n_115), .Y
       (sub_23_2_n_116));
  NOR2X2 sub_23_2_g883(.A (sub_23_2_n_80), .B (sub_23_2_n_111), .Y
       (sub_23_2_n_115));
  OAI21X1 sub_23_2_g885(.A0 (n_220), .A1 (n_230), .B0 (sub_23_2_n_64),
       .Y (sub_23_2_n_113));
  OAI21X2 sub_23_2_g886(.A0 (sub_23_2_n_96), .A1 (sub_23_2_n_78), .B0
       (sub_23_2_n_89), .Y (sub_23_2_n_112));
  AOI21X2 sub_23_2_g887(.A0 (sub_23_2_n_56), .A1 (sub_23_2_n_52), .B0
       (sub_23_2_n_57), .Y (sub_23_2_n_111));
  NAND2XL sub_23_2_g889(.A (sub_23_2_n_24), .B (sub_23_2_n_95), .Y
       (sub_23_2_n_110));
  NAND2XL sub_23_2_g890(.A (sub_23_2_n_75), .B (sub_23_2_n_95), .Y
       (sub_23_2_n_109));
  NAND2XL sub_23_2_g891(.A (sub_23_2_n_65), .B (sub_23_2_n_95), .Y
       (sub_23_2_n_108));
  NOR2X1 sub_23_2_g892(.A (sub_23_2_n_99), .B (sub_23_2_n_94), .Y
       (sub_23_2_n_107));
  NAND4X1 sub_23_2_g893(.A (sub_23_2_n_58), .B (sub_23_2_n_75), .C
       (sub_23_2_n_36), .D (sub_23_2_n_95), .Y (sub_23_2_n_106));
  NAND3BXL sub_23_2_g894(.AN (in2[28]), .B (sub_23_2_n_95), .C
       (sub_23_2_n_75), .Y (sub_23_2_n_105));
  NAND3BXL sub_23_2_g895(.AN (in2[26]), .B (sub_23_2_n_95), .C
       (sub_23_2_n_65), .Y (sub_23_2_n_104));
  OR2XL sub_23_2_g897(.A (n_223), .B (sub_23_2_n_85), .Y
       (sub_23_2_n_103));
  NAND2X1 sub_23_2_g898(.A (sub_23_2_n_34), .B (sub_23_2_n_73), .Y
       (sub_23_2_n_102));
  AND2XL sub_23_2_g899(.A (sub_23_2_n_66), .B (sub_23_2_n_71), .Y
       (sub_23_2_n_101));
  NOR2X1 sub_23_2_g900(.A (in2[12]), .B (sub_23_2_n_72), .Y
       (sub_23_2_n_100));
  NAND2X1 sub_23_2_g901(.A (sub_23_2_n_58), .B (sub_23_2_n_75), .Y
       (sub_23_2_n_99));
  NAND2X1 sub_23_2_g902(.A (sub_23_2_n_77), .B (sub_23_2_n_84), .Y
       (sub_23_2_n_98));
  NAND2X1 sub_23_2_g903(.A (sub_23_2_n_49), .B (sub_23_2_n_73), .Y
       (sub_23_2_n_97));
  INVX1 sub_23_2_g905(.A (sub_23_2_n_95), .Y (sub_23_2_n_94));
  NAND3X1 sub_23_2_g906(.A (sub_23_2_n_71), .B (sub_23_2_n_26), .C
       (sub_23_2_n_66), .Y (sub_23_2_n_93));
  NOR4BBX2 sub_23_2_g907(.AN (sub_23_2_n_66), .BN (sub_23_2_n_37), .C
       (in2[14]), .D (sub_23_2_n_72), .Y (sub_23_2_n_92));
  NAND3X1 sub_23_2_g908(.A (sub_23_2_n_73), .B (sub_23_2_n_25), .C
       (sub_23_2_n_49), .Y (sub_23_2_n_91));
  NAND2X4 sub_23_2_g909(.A (sub_23_2_n_3), .B (sub_23_2_n_83), .Y
       (sub_23_2_n_90));
  AOI21X2 sub_23_2_g910(.A0 (sub_23_2_n_10), .A1 (sub_23_2_n_48), .B0
       (sub_23_2_n_6), .Y (sub_23_2_n_89));
  AOI21X2 sub_23_2_g911(.A0 (sub_23_2_n_50), .A1 (sub_23_2_n_9), .B0
       (sub_23_2_n_68), .Y (sub_23_2_n_96));
  NOR2X1 sub_23_2_g912(.A (sub_23_2_n_69), .B (sub_23_2_n_74), .Y
       (sub_23_2_n_95));
  INVX1 sub_23_2_g916(.A (sub_23_2_n_84), .Y (sub_23_2_n_85));
  NAND2X2 sub_23_2_g917(.A (sub_23_2_n_63), .B (sub_23_2_n_54), .Y
       (sub_23_2_n_83));
  NAND2X1 sub_23_2_g918(.A (sub_23_2_n_33), .B (sub_23_2_n_67), .Y
       (sub_23_2_n_82));
  AND2XL sub_23_2_g919(.A (sub_23_2_n_22), .B (sub_23_2_n_53), .Y
       (sub_23_2_n_81));
  NAND2X1 sub_23_2_g920(.A (sub_23_2_n_54), .B (sub_23_2_n_55), .Y
       (sub_23_2_n_80));
  NOR2BX1 sub_23_2_g921(.AN (sub_23_2_n_48), .B (sub_23_2_n_6), .Y
       (sub_23_2_n_88));
  NAND2X1 sub_23_2_g923(.A (sub_23_2_n_54), .B (sub_23_2_n_3), .Y
       (sub_23_2_n_87));
  NOR2X1 sub_23_2_g924(.A (sub_23_2_n_4), .B (sub_23_2_n_9), .Y
       (sub_23_2_n_86));
  NOR2X2 sub_23_2_g925(.A (sub_23_2_n_51), .B (sub_23_2_n_4), .Y
       (sub_23_2_n_84));
  INVX1 sub_23_2_g928(.A (sub_23_2_n_77), .Y (sub_23_2_n_78));
  INVX1 sub_23_2_g930(.A (sub_23_2_n_74), .Y (sub_23_2_n_73));
  INVX1 sub_23_2_g931(.A (sub_23_2_n_72), .Y (sub_23_2_n_71));
  MXI2XL sub_23_2_g932(.A (sub_23_2_n_38), .B (in2[0]), .S0 (in1[0]),
       .Y (out1[0]));
  NAND2X1 sub_23_2_g933(.A (sub_23_2_n_59), .B (sub_23_2_n_49), .Y
       (sub_23_2_n_69));
  NOR2X1 sub_23_2_g935(.A (sub_23_2_n_51), .B (sub_23_2_n_68), .Y
       (sub_23_2_n_79));
  NOR2X1 sub_23_2_g936(.A (sub_23_2_n_47), .B (sub_23_2_n_5), .Y
       (sub_23_2_n_77));
  NOR2X1 sub_23_2_g937(.A (n_221), .B (sub_23_2_n_10), .Y
       (sub_23_2_n_76));
  AND2XL sub_23_2_g938(.A (sub_23_2_n_62), .B (sub_23_2_n_65), .Y
       (sub_23_2_n_75));
  NAND2X1 sub_23_2_g939(.A (sub_23_2_n_60), .B (sub_23_2_n_67), .Y
       (sub_23_2_n_74));
  NAND2X1 sub_23_2_g940(.A (sub_23_2_n_61), .B (sub_23_2_n_53), .Y
       (sub_23_2_n_72));
  INVX1 sub_23_2_g942(.A (sub_23_2_n_10), .Y (sub_23_2_n_64));
  NOR2X1 sub_23_2_g944(.A (in2[27]), .B (in2[26]), .Y (sub_23_2_n_62));
  NOR2X1 sub_23_2_g945(.A (in2[11]), .B (in2[10]), .Y (sub_23_2_n_61));
  NOR2X1 sub_23_2_g946(.A (in2[19]), .B (in2[18]), .Y (sub_23_2_n_60));
  NOR2X1 sub_23_2_g947(.A (in2[23]), .B (in2[22]), .Y (sub_23_2_n_59));
  NOR2X1 sub_23_2_g948(.A (n_236), .B (in1[5]), .Y (sub_23_2_n_68));
  NOR2X1 sub_23_2_g950(.A (in2[17]), .B (in2[16]), .Y (sub_23_2_n_67));
  NOR2X1 sub_23_2_g951(.A (in2[13]), .B (in2[12]), .Y (sub_23_2_n_66));
  NOR2X1 sub_23_2_g952(.A (in2[25]), .B (in2[24]), .Y (sub_23_2_n_65));
  NOR2X1 sub_23_2_g954(.A (in1[2]), .B (sub_23_2_n_45), .Y
       (sub_23_2_n_63));
  INVX2 sub_23_2_g957(.A (sub_23_2_n_50), .Y (sub_23_2_n_51));
  INVX1 sub_23_2_g958(.A (sub_23_2_n_47), .Y (sub_23_2_n_48));
  NOR2X1 sub_23_2_g959(.A (in2[29]), .B (in2[28]), .Y (sub_23_2_n_58));
  NOR2X1 sub_23_2_g960(.A (sub_23_2_n_31), .B (in1[1]), .Y
       (sub_23_2_n_57));
  NAND2X4 sub_23_2_g961(.A (in1[1]), .B (sub_23_2_n_31), .Y
       (sub_23_2_n_56));
  NAND2X2 sub_23_2_g964(.A (in1[2]), .B (sub_23_2_n_45), .Y
       (sub_23_2_n_55));
  NAND2X2 sub_23_2_g965(.A (in1[3]), .B (n_226), .Y (sub_23_2_n_54));
  NOR2X1 sub_23_2_g966(.A (in2[9]), .B (in2[8]), .Y (sub_23_2_n_53));
  NAND2X4 sub_23_2_g967(.A (in1[0]), .B (sub_23_2_n_38), .Y
       (sub_23_2_n_52));
  NAND2X4 sub_23_2_g968(.A (in1[5]), .B (n_237), .Y (sub_23_2_n_50));
  NOR2X1 sub_23_2_g969(.A (in2[21]), .B (in2[20]), .Y (sub_23_2_n_49));
  NOR2X2 sub_23_2_g970(.A (in2[7]), .B (n_228), .Y (sub_23_2_n_47));
  INVX2 sub_23_2_g975(.A (in2[2]), .Y (sub_23_2_n_45));
  INVXL sub_23_2_g976(.A (in2[31]), .Y (sub_23_2_n_44));
  INVXL sub_23_2_g977(.A (in2[21]), .Y (sub_23_2_n_43));
  INVXL sub_23_2_g978(.A (in2[17]), .Y (sub_23_2_n_42));
  INVXL sub_23_2_g980(.A (in2[19]), .Y (sub_23_2_n_41));
  INVXL sub_23_2_g981(.A (in2[25]), .Y (sub_23_2_n_40));
  INVXL sub_23_2_g982(.A (in2[29]), .Y (sub_23_2_n_39));
  CLKINVX3 sub_23_2_g983(.A (in2[0]), .Y (sub_23_2_n_38));
  INVX1 sub_23_2_g984(.A (in2[15]), .Y (sub_23_2_n_37));
  INVX1 sub_23_2_g985(.A (in2[30]), .Y (sub_23_2_n_36));
  INVXL sub_23_2_g986(.A (in2[26]), .Y (sub_23_2_n_35));
  INVX1 sub_23_2_g987(.A (in2[20]), .Y (sub_23_2_n_34));
  INVX1 sub_23_2_g988(.A (in2[18]), .Y (sub_23_2_n_33));
  CLKINVX12 sub_23_2_g993(.A (in2[1]), .Y (sub_23_2_n_31));
  INVXL sub_23_2_g999(.A (in2[23]), .Y (sub_23_2_n_29));
  INVXL sub_23_2_g1000(.A (in2[27]), .Y (sub_23_2_n_28));
  INVX1 sub_23_2_g1001(.A (in2[9]), .Y (sub_23_2_n_27));
  INVX1 sub_23_2_g1002(.A (in2[14]), .Y (sub_23_2_n_26));
  INVX1 sub_23_2_g1003(.A (in2[22]), .Y (sub_23_2_n_25));
  INVX1 sub_23_2_g1004(.A (in2[24]), .Y (sub_23_2_n_24));
  INVXL sub_23_2_g1005(.A (in2[28]), .Y (sub_23_2_n_23));
  INVX1 sub_23_2_g1007(.A (in2[10]), .Y (sub_23_2_n_22));
  XNOR2X1 sub_23_2_g2(.A (sub_23_2_n_52), .B (sub_23_2_n_11), .Y
       (out1[1]));
  NOR2BX1 sub_23_2_g1008(.AN (n_229), .B (sub_23_2_n_120), .Y
       (sub_23_2_n_20));
  XNOR2X1 sub_23_2_g1009(.A (sub_23_2_n_88), .B (sub_23_2_n_122), .Y
       (out1[7]));
  CLKXOR2X1 sub_23_2_g1010(.A (sub_23_2_n_87), .B (sub_23_2_n_117), .Y
       (out1[3]));
  XNOR2X1 sub_23_2_g1011(.A (sub_23_2_n_86), .B (n_233), .Y (out1[4]));
  CLKXOR2X1 sub_23_2_g1012(.A (sub_23_2_n_12), .B (n_217), .Y
       (out1[2]));
  XNOR2X1 sub_23_2_g1013(.A (sub_23_2_n_79), .B (sub_23_2_n_125), .Y
       (out1[5]));
  XNOR2X1 sub_23_2_g1014(.A (sub_23_2_n_76), .B (sub_23_2_n_20), .Y
       (out1[6]));
  NOR2BX1 sub_23_2_g1015(.AN (sub_23_2_n_67), .B (sub_23_2_n_131), .Y
       (sub_23_2_n_13));
  NAND2BX1 sub_23_2_g1016(.AN (n_213), .B (sub_23_2_n_55), .Y
       (sub_23_2_n_12));
  NAND2BX1 sub_23_2_g1017(.AN (sub_23_2_n_57), .B (sub_23_2_n_56), .Y
       (sub_23_2_n_11));
  NOR2BX1 sub_23_2_g1018(.AN (in2[6]), .B (in1[6]), .Y (sub_23_2_n_10));
  NOR2BX2 sub_23_2_g1019(.AN (in2[4]), .B (in1[4]), .Y (sub_23_2_n_9));
  XNOR2XL sub_23_2_g1020(.A (in2[11]), .B (sub_23_2_n_126), .Y
       (out1[11]));
  CLKXOR2X1 sub_23_2_g1021(.A (in2[16]), .B (sub_23_2_n_132), .Y
       (out1[16]));
  NOR2BX1 sub_23_2_g1022(.AN (in2[7]), .B (n_227), .Y (sub_23_2_n_6));
  NOR2BX2 sub_23_2_g1023(.AN (in1[6]), .B (in2[6]), .Y (sub_23_2_n_5));
  NOR2BX1 sub_23_2_g1024(.AN (in1[4]), .B (in2[4]), .Y (sub_23_2_n_4));
  NAND2BX1 sub_23_2_g1025(.AN (in1[3]), .B (n_225), .Y (sub_23_2_n_3));
  CLKXOR2X1 sub_23_2_g1026(.A (in2[8]), .B (n_209), .Y (out1[8]));
  XNOR2XL sub_23_2_g1027(.A (in2[13]), .B (sub_23_2_n_127), .Y
       (out1[13]));
  XNOR2XL sub_23_2_g1028(.A (in2[12]), .B (sub_23_2_n_130), .Y
       (out1[12]));
  CLKINVX1 fopt(.A (n_209), .Y (n_208));
  BUFX3 fopt1029(.A (sub_23_2_n_124), .Y (n_209));
  INVXL fopt1030(.A (n_215), .Y (n_213));
  INVXL fopt1031(.A (n_215), .Y (n_214));
  INVXL fopt1032(.A (sub_23_2_n_63), .Y (n_215));
  INVXL fopt1033(.A (n_218), .Y (n_217));
  CLKINVX1 fopt1034(.A (sub_23_2_n_111), .Y (n_218));
  INVXL fopt1035(.A (n_222), .Y (n_220));
  INVXL fopt1036(.A (n_222), .Y (n_221));
  INVXL fopt1037(.A (n_223), .Y (n_222));
  BUFX2 fopt1038(.A (sub_23_2_n_5), .Y (n_223));
  INVXL fopt1039(.A (n_226), .Y (n_225));
  CLKINVX3 fopt1040(.A (in2[3]), .Y (n_226));
  INVXL fopt1041(.A (n_228), .Y (n_227));
  CLKINVX3 fopt1042(.A (in1[7]), .Y (n_228));
  INVXL fopt1043(.A (n_231), .Y (n_229));
  INVXL fopt1044(.A (n_231), .Y (n_230));
  INVXL fopt1045(.A (sub_23_2_n_96), .Y (n_231));
  BUFX3 fopt1046(.A (sub_23_2_n_116), .Y (n_233));
  INVXL fopt1047(.A (in2[5]), .Y (n_236));
  CLKINVX4 fopt1048(.A (in2[5]), .Y (n_237));
endmodule


