`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 07:27:56 CST (May 14 2023 23:27:56 UTC)

module Filter_NotEQ_2Ux2U_1U_1(in2, in1, out1);
  input [1:0] in2, in1;
  output out1;
  wire [1:0] in2, in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  NAND2X2 g26(.A (n_9), .B (n_8), .Y (out1));
  NAND2X2 g27(.A (n_4), .B (n_6), .Y (n_9));
  NAND2X1 g28(.A (n_5), .B (n_7), .Y (n_8));
  NAND2X2 g30(.A (n_1), .B (n_0), .Y (n_7));
  NAND2X2 g31(.A (n_3), .B (n_2), .Y (n_6));
  NAND2X1 g29(.A (in2[0]), .B (in1[0]), .Y (n_5));
  NAND2X2 g32(.A (in2[1]), .B (in1[1]), .Y (n_4));
  CLKINVX4 g35(.A (in2[1]), .Y (n_3));
  INVX2 g33(.A (in1[1]), .Y (n_2));
  CLKINVX3 g36(.A (in2[0]), .Y (n_1));
  INVX2 g34(.A (in1[0]), .Y (n_0));
endmodule


