`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 07:26:49 CST (May 14 2023 23:26:49 UTC)

module Filter_Add_32Ux9U_32U_4(in2, in1, out1);
  input [31:0] in2;
  input [8:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [8:0] in1;
  wire [31:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27,
       add_23_2_n_28, add_23_2_n_29, add_23_2_n_30, add_23_2_n_31;
  wire add_23_2_n_32, add_23_2_n_33, add_23_2_n_34, add_23_2_n_35,
       add_23_2_n_36, add_23_2_n_37, add_23_2_n_38, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45,
       add_23_2_n_46, add_23_2_n_48, add_23_2_n_51, add_23_2_n_52;
  wire add_23_2_n_53, add_23_2_n_54, add_23_2_n_55, add_23_2_n_59,
       add_23_2_n_60, add_23_2_n_61, add_23_2_n_62, add_23_2_n_63;
  wire add_23_2_n_64, add_23_2_n_65, add_23_2_n_66, add_23_2_n_67,
       add_23_2_n_68, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76;
  wire add_23_2_n_77, add_23_2_n_78, add_23_2_n_79, add_23_2_n_80,
       add_23_2_n_85, add_23_2_n_86, add_23_2_n_87, add_23_2_n_88;
  wire add_23_2_n_92;
  XNOR2X1 add_23_2_g637(.A (in2[31]), .B (add_23_2_n_92), .Y
       (out1[31]));
  XNOR2X1 add_23_2_g638(.A (in2[23]), .B (add_23_2_n_86), .Y
       (out1[23]));
  XNOR2X1 add_23_2_g639(.A (in2[27]), .B (add_23_2_n_87), .Y
       (out1[27]));
  XNOR2X1 add_23_2_g640(.A (in2[29]), .B (add_23_2_n_85), .Y
       (out1[29]));
  XNOR2X1 add_23_2_g641(.A (in2[21]), .B (add_23_2_n_76), .Y
       (out1[21]));
  XNOR2X1 add_23_2_g642(.A (in2[19]), .B (add_23_2_n_77), .Y
       (out1[19]));
  XNOR2X1 add_23_2_g643(.A (in2[15]), .B (add_23_2_n_78), .Y
       (out1[15]));
  XNOR2X1 add_23_2_g644(.A (in2[25]), .B (add_23_2_n_75), .Y
       (out1[25]));
  XNOR2X1 add_23_2_g645(.A (in2[30]), .B (add_23_2_n_88), .Y
       (out1[30]));
  XNOR2X1 add_23_2_g646(.A (in2[17]), .B (add_23_2_n_0), .Y (out1[17]));
  XNOR2X1 add_23_2_g647(.A (in2[11]), .B (add_23_2_n_64), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g648(.A (in2[13]), .B (add_23_2_n_65), .Y
       (out1[13]));
  NAND2BX1 add_23_2_g649(.AN (add_23_2_n_88), .B (in2[30]), .Y
       (add_23_2_n_92));
  XNOR2X1 add_23_2_g650(.A (in2[28]), .B (add_23_2_n_74), .Y
       (out1[28]));
  XNOR2X1 add_23_2_g651(.A (in2[22]), .B (add_23_2_n_80), .Y
       (out1[22]));
  XNOR2X1 add_23_2_g652(.A (in2[26]), .B (add_23_2_n_79), .Y
       (out1[26]));
  NAND2BX1 add_23_2_g653(.AN (add_23_2_n_79), .B (in2[26]), .Y
       (add_23_2_n_87));
  NAND2BX1 add_23_2_g654(.AN (add_23_2_n_80), .B (in2[22]), .Y
       (add_23_2_n_86));
  NAND2BX1 add_23_2_g655(.AN (add_23_2_n_74), .B (in2[28]), .Y
       (add_23_2_n_85));
  NAND3BXL add_23_2_g656(.AN (add_23_2_n_74), .B (in2[29]), .C
       (in2[28]), .Y (add_23_2_n_88));
  XOR2XL add_23_2_g657(.A (in2[18]), .B (add_23_2_n_67), .Y (out1[18]));
  XOR2XL add_23_2_g658(.A (in2[20]), .B (add_23_2_n_68), .Y (out1[20]));
  XOR2XL add_23_2_g659(.A (in2[24]), .B (add_23_2_n_63), .Y (out1[24]));
  XOR2XL add_23_2_g660(.A (in2[14]), .B (add_23_2_n_66), .Y (out1[14]));
  NAND2X1 add_23_2_g661(.A (in2[14]), .B (add_23_2_n_66), .Y
       (add_23_2_n_78));
  NAND2X1 add_23_2_g662(.A (in2[18]), .B (add_23_2_n_67), .Y
       (add_23_2_n_77));
  NAND2X1 add_23_2_g663(.A (in2[20]), .B (add_23_2_n_68), .Y
       (add_23_2_n_76));
  NAND2X1 add_23_2_g664(.A (in2[24]), .B (add_23_2_n_63), .Y
       (add_23_2_n_75));
  NAND2BX1 add_23_2_g665(.AN (add_23_2_n_9), .B (add_23_2_n_68), .Y
       (add_23_2_n_80));
  NAND2BX1 add_23_2_g666(.AN (add_23_2_n_8), .B (add_23_2_n_63), .Y
       (add_23_2_n_79));
  XNOR2X1 add_23_2_g667(.A (add_23_2_n_24), .B (add_23_2_n_60), .Y
       (out1[7]));
  XNOR2X1 add_23_2_g668(.A (in2[16]), .B (add_23_2_n_55), .Y
       (out1[16]));
  XNOR2X1 add_23_2_g669(.A (in2[12]), .B (add_23_2_n_61), .Y
       (out1[12]));
  XOR2XL add_23_2_g670(.A (in2[9]), .B (add_23_2_n_62), .Y (out1[9]));
  XNOR2X1 add_23_2_g671(.A (in2[10]), .B (add_23_2_n_59), .Y
       (out1[10]));
  NAND4BX1 add_23_2_g672(.AN (add_23_2_n_8), .B (add_23_2_n_63), .C
       (in2[27]), .D (in2[26]), .Y (add_23_2_n_74));
  NOR2X1 add_23_2_g673(.A (add_23_2_n_28), .B (add_23_2_n_55), .Y
       (add_23_2_n_68));
  NOR2X1 add_23_2_g674(.A (add_23_2_n_10), .B (add_23_2_n_55), .Y
       (add_23_2_n_67));
  NOR2X1 add_23_2_g676(.A (add_23_2_n_21), .B (add_23_2_n_61), .Y
       (add_23_2_n_66));
  NAND2BX1 add_23_2_g677(.AN (add_23_2_n_61), .B (in2[12]), .Y
       (add_23_2_n_65));
  NAND2BX1 add_23_2_g678(.AN (add_23_2_n_59), .B (in2[10]), .Y
       (add_23_2_n_64));
  NOR4X1 add_23_2_g679(.A (add_23_2_n_55), .B (add_23_2_n_28), .C
       (add_23_2_n_13), .D (add_23_2_n_9), .Y (add_23_2_n_63));
  OAI21X1 add_23_2_g680(.A0 (add_23_2_n_2), .A1 (add_23_2_n_54), .B0
       (add_23_2_n_4), .Y (add_23_2_n_62));
  AOI21X1 add_23_2_g681(.A0 (add_23_2_n_37), .A1 (add_23_2_n_53), .B0
       (add_23_2_n_36), .Y (add_23_2_n_61));
  OAI21X1 add_23_2_g682(.A0 (add_23_2_n_3), .A1 (add_23_2_n_52), .B0
       (add_23_2_n_19), .Y (add_23_2_n_60));
  AOI21X1 add_23_2_g683(.A0 (add_23_2_n_33), .A1 (add_23_2_n_53), .B0
       (add_23_2_n_26), .Y (add_23_2_n_59));
  XNOR2X1 add_23_2_g684(.A (add_23_2_n_25), .B (add_23_2_n_54), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g685(.A (add_23_2_n_23), .B (add_23_2_n_52), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g686(.A (add_23_2_n_30), .B (add_23_2_n_51), .Y
       (out1[5]));
  AOI32X1 add_23_2_g688(.A0 (add_23_2_n_53), .A1 (add_23_2_n_27), .A2
       (add_23_2_n_37), .B0 (add_23_2_n_27), .B1 (add_23_2_n_36), .Y
       (add_23_2_n_55));
  INVX1 add_23_2_g689(.A (add_23_2_n_54), .Y (add_23_2_n_53));
  AOI31X1 add_23_2_g690(.A0 (add_23_2_n_45), .A1 (add_23_2_n_34), .A2
       (add_23_2_n_32), .B0 (add_23_2_n_41), .Y (add_23_2_n_54));
  AOI21X1 add_23_2_g691(.A0 (add_23_2_n_32), .A1 (add_23_2_n_45), .B0
       (add_23_2_n_35), .Y (add_23_2_n_52));
  OAI21X1 add_23_2_g692(.A0 (add_23_2_n_16), .A1 (add_23_2_n_46), .B0
       (add_23_2_n_15), .Y (add_23_2_n_51));
  XNOR2X1 add_23_2_g693(.A (add_23_2_n_29), .B (add_23_2_n_46), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g694(.A (add_23_2_n_31), .B (add_23_2_n_48), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g695(.A0N (add_23_2_n_5), .A1N (add_23_2_n_43),
       .B0 (add_23_2_n_14), .Y (add_23_2_n_48));
  XNOR2X1 add_23_2_g696(.A (add_23_2_n_22), .B (add_23_2_n_43), .Y
       (out1[2]));
  INVX1 add_23_2_g697(.A (add_23_2_n_45), .Y (add_23_2_n_46));
  OAI211X1 add_23_2_g698(.A0 (add_23_2_n_14), .A1 (add_23_2_n_17), .B0
       (add_23_2_n_44), .C0 (add_23_2_n_6), .Y (add_23_2_n_45));
  NAND3BXL add_23_2_g699(.AN (add_23_2_n_17), .B (add_23_2_n_43), .C
       (add_23_2_n_5), .Y (add_23_2_n_44));
  ADDFX1 add_23_2_g700(.A (add_23_2_n_38), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_43), .S (out1[1]));
  OAI211X1 add_23_2_g701(.A0 (add_23_2_n_19), .A1 (add_23_2_n_18), .B0
       (add_23_2_n_40), .C0 (add_23_2_n_7), .Y (add_23_2_n_41));
  NAND2X1 add_23_2_g702(.A (add_23_2_n_34), .B (add_23_2_n_35), .Y
       (add_23_2_n_40));
  ADDHX1 add_23_2_g703(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_38),
       .S (out1[0]));
  NOR2BX1 add_23_2_g704(.AN (add_23_2_n_33), .B (add_23_2_n_11), .Y
       (add_23_2_n_37));
  NOR2BX1 add_23_2_g705(.AN (add_23_2_n_26), .B (add_23_2_n_11), .Y
       (add_23_2_n_36));
  OAI21X1 add_23_2_g706(.A0 (add_23_2_n_15), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_20), .Y (add_23_2_n_35));
  NOR2X1 add_23_2_g707(.A (add_23_2_n_18), .B (add_23_2_n_3), .Y
       (add_23_2_n_34));
  NAND2BX1 add_23_2_g708(.AN (add_23_2_n_17), .B (add_23_2_n_6), .Y
       (add_23_2_n_31));
  NOR2BX1 add_23_2_g709(.AN (in2[9]), .B (add_23_2_n_2), .Y
       (add_23_2_n_33));
  NOR2X1 add_23_2_g710(.A (add_23_2_n_1), .B (add_23_2_n_16), .Y
       (add_23_2_n_32));
  NAND2BX1 add_23_2_g711(.AN (add_23_2_n_1), .B (add_23_2_n_20), .Y
       (add_23_2_n_30));
  NOR2BX1 add_23_2_g712(.AN (add_23_2_n_15), .B (add_23_2_n_16), .Y
       (add_23_2_n_29));
  NAND3BXL add_23_2_g713(.AN (add_23_2_n_10), .B (in2[19]), .C
       (in2[18]), .Y (add_23_2_n_28));
  NOR2BX1 add_23_2_g714(.AN (add_23_2_n_4), .B (add_23_2_n_2), .Y
       (add_23_2_n_25));
  NAND2BX1 add_23_2_g715(.AN (add_23_2_n_18), .B (add_23_2_n_7), .Y
       (add_23_2_n_24));
  NOR2BX1 add_23_2_g716(.AN (add_23_2_n_19), .B (add_23_2_n_3), .Y
       (add_23_2_n_23));
  NAND2X1 add_23_2_g717(.A (add_23_2_n_14), .B (add_23_2_n_5), .Y
       (add_23_2_n_22));
  NOR2X1 add_23_2_g718(.A (add_23_2_n_12), .B (add_23_2_n_21), .Y
       (add_23_2_n_27));
  NOR2BX1 add_23_2_g719(.AN (in2[9]), .B (add_23_2_n_4), .Y
       (add_23_2_n_26));
  NAND2X1 add_23_2_g720(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_13));
  NAND2X1 add_23_2_g721(.A (in2[15]), .B (in2[14]), .Y (add_23_2_n_12));
  NAND2X1 add_23_2_g722(.A (in2[13]), .B (in2[12]), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g723(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_20));
  NAND2X1 add_23_2_g724(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g725(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_18));
  NOR2X1 add_23_2_g726(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_17));
  NOR2X1 add_23_2_g727(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_16));
  NAND2X1 add_23_2_g728(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g729(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g730(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g731(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g732(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_9));
  NAND2X1 add_23_2_g733(.A (in2[25]), .B (in2[24]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g734(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g735(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_6));
  OR2X1 add_23_2_g736(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g737(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g738(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_3));
  NOR2X1 add_23_2_g739(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g740(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NAND2BX1 add_23_2_g2(.AN (add_23_2_n_55), .B (in2[16]), .Y
       (add_23_2_n_0));
endmodule


