`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:45 CST (May 15 2023 01:24:45 UTC)

module Filter_Add_5U_2_4(in1, out1);
  input [4:0] in1;
  output [4:0] out1;
  wire [4:0] in1;
  wire [4:0] out1;
  wire inc_add_21_2_1_n_0, inc_add_21_2_1_n_2, inc_add_21_2_1_n_3;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_21_2_1_g39(.A (in1[3]), .B (inc_add_21_2_1_n_3), .Y
       (out1[3]));
  XNOR2X1 inc_add_21_2_1_g40(.A (in1[4]), .B (inc_add_21_2_1_n_2), .Y
       (out1[4]));
  XNOR2X1 inc_add_21_2_1_g41(.A (in1[2]), .B (inc_add_21_2_1_n_0), .Y
       (out1[2]));
  NAND2BX1 inc_add_21_2_1_g42(.AN (inc_add_21_2_1_n_0), .B (in1[2]), .Y
       (inc_add_21_2_1_n_3));
  NAND3BXL inc_add_21_2_1_g43(.AN (inc_add_21_2_1_n_0), .B (in1[3]), .C
       (in1[2]), .Y (inc_add_21_2_1_n_2));
  XOR2XL inc_add_21_2_1_g44(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_21_2_1_g45(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_1_n_0));
endmodule


