`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:18:44 CST (May 15 2023 01:18:44 UTC)

module Filter_Mul_2Ux2U_4U_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [3:0] out1;
  wire [1:0] in2, in1;
  wire [3:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_2, mul_22_8_n_3, mul_22_8_n_4;
  XNOR2X1 mul_22_8_g74(.A (mul_22_8_n_3), .B (mul_22_8_n_4), .Y
       (out1[2]));
  NOR2BX1 mul_22_8_g75(.AN (mul_22_8_n_4), .B (mul_22_8_n_3), .Y
       (out1[3]));
  AOI21X1 mul_22_8_g76(.A0 (mul_22_8_n_0), .A1 (mul_22_8_n_2), .B0
       (mul_22_8_n_4), .Y (out1[1]));
  NOR2X1 mul_22_8_g77(.A (mul_22_8_n_0), .B (mul_22_8_n_2), .Y
       (mul_22_8_n_4));
  NAND2X1 mul_22_8_g78(.A (in1[1]), .B (in2[1]), .Y (mul_22_8_n_3));
  NAND2X1 mul_22_8_g79(.A (in1[1]), .B (in2[0]), .Y (mul_22_8_n_2));
  AND2XL mul_22_8_g80(.A (in1[0]), .B (in2[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g81(.A (in1[0]), .B (in2[1]), .Y (mul_22_8_n_0));
endmodule


