`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:18:32 CST (May 15 2023 01:18:32 UTC)

module Filter_Xor_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  XOR2XL g10(.A (in2), .B (in1), .Y (out1));
endmodule


