`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:18:33 CST (May 15 2023 01:18:33 UTC)

module Filter_N_Muxb_1_2_2_4(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  MX2XL g11(.A (in3), .B (in2), .S0 (ctrl1), .Y (out1));
endmodule


