`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:14 CST (May 15 2023 01:19:14 UTC)

module Filter_Add_5Ux2U_5U_1(in2, in1, out1);
  input [4:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [4:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_12, add_23_2_n_14, add_23_2_n_15, n_26,
       n_27, n_31, n_32;
  wire n_34;
  MXI2X1 add_23_2_g74(.A (add_23_2_n_2), .B (in2[3]), .S0
       (add_23_2_n_15), .Y (out1[3]));
  MXI2X1 add_23_2_g75(.A (add_23_2_n_1), .B (in2[4]), .S0
       (add_23_2_n_14), .Y (out1[4]));
  MXI2XL add_23_2_g76(.A (add_23_2_n_4), .B (in2[2]), .S0 (n_26), .Y
       (out1[2]));
  NOR2X1 add_23_2_g77(.A (add_23_2_n_4), .B (n_27), .Y (add_23_2_n_15));
  NOR2X1 add_23_2_g78(.A (add_23_2_n_6), .B (n_27), .Y (add_23_2_n_14));
  OAI21X2 add_23_2_g80(.A0 (add_23_2_n_5), .A1 (add_23_2_n_8), .B0
       (add_23_2_n_7), .Y (add_23_2_n_12));
  MXI2XL add_23_2_g81(.A (n_31), .B (n_32), .S0 (add_23_2_n_0), .Y
       (out1[1]));
  MXI2XL add_23_2_g84(.A (add_23_2_n_3), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NOR2X2 add_23_2_g85(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_8));
  NAND2X2 add_23_2_g87(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g88(.A (in2[3]), .B (in2[2]), .Y (add_23_2_n_6));
  NAND2X8 add_23_2_g89(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_5));
  INVX1 add_23_2_g90(.A (in2[2]), .Y (add_23_2_n_4));
  INVX1 add_23_2_g91(.A (in2[0]), .Y (add_23_2_n_3));
  INVXL add_23_2_g92(.A (in2[3]), .Y (add_23_2_n_2));
  INVXL add_23_2_g93(.A (in2[4]), .Y (add_23_2_n_1));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_7), .B (n_34), .Y (add_23_2_n_0));
  INVXL fopt(.A (n_27), .Y (n_26));
  CLKINVX2 fopt94(.A (add_23_2_n_12), .Y (n_27));
  INVXL fopt97(.A (n_32), .Y (n_31));
  INVXL fopt98(.A (add_23_2_n_5), .Y (n_32));
  BUFX2 fopt99(.A (add_23_2_n_8), .Y (n_34));
endmodule


