`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:33 CST (May 15 2023 01:24:33 UTC)

module Filter_Add_12Ux8U_12U_1(in2, in1, out1);
  input [11:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_1, add_23_2_n_5, add_23_2_n_7, add_23_2_n_8,
       add_23_2_n_9, add_23_2_n_10, add_23_2_n_11, add_23_2_n_12;
  wire add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16,
       add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20;
  wire add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24,
       add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29;
  wire add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33,
       add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37;
  wire add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41,
       add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45;
  wire add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49,
       add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53;
  wire add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57,
       add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61;
  wire add_23_2_n_62, add_23_2_n_63, add_23_2_n_64, add_23_2_n_65,
       add_23_2_n_66, add_23_2_n_67, n_95, n_96;
  wire n_97, n_99, n_100, n_101, n_102, n_103;
  MXI2XL add_23_2_g244(.A (add_23_2_n_10), .B (in2[9]), .S0
       (add_23_2_n_67), .Y (out1[9]));
  MXI2XL add_23_2_g245(.A (add_23_2_n_8), .B (in2[11]), .S0
       (add_23_2_n_65), .Y (out1[11]));
  MXI2XL add_23_2_g246(.A (add_23_2_n_11), .B (in2[10]), .S0
       (add_23_2_n_66), .Y (out1[10]));
  MXI2XL add_23_2_g247(.A (in2[8]), .B (add_23_2_n_9), .S0
       (add_23_2_n_64), .Y (out1[8]));
  MXI2XL add_23_2_g248(.A (add_23_2_n_43), .B (add_23_2_n_44), .S0
       (add_23_2_n_62), .Y (out1[7]));
  MXI2XL add_23_2_g249(.A (add_23_2_n_42), .B (add_23_2_n_41), .S0
       (add_23_2_n_5), .Y (out1[6]));
  MXI2XL add_23_2_g250(.A (add_23_2_n_36), .B (add_23_2_n_37), .S0
       (add_23_2_n_63), .Y (out1[5]));
  NOR2X1 add_23_2_g251(.A (add_23_2_n_9), .B (add_23_2_n_64), .Y
       (add_23_2_n_67));
  NOR2X1 add_23_2_g252(.A (add_23_2_n_19), .B (add_23_2_n_64), .Y
       (add_23_2_n_66));
  NOR2X1 add_23_2_g253(.A (add_23_2_n_38), .B (add_23_2_n_64), .Y
       (add_23_2_n_65));
  NOR2X2 add_23_2_g254(.A (add_23_2_n_52), .B (add_23_2_n_59), .Y
       (add_23_2_n_64));
  NOR2BX1 add_23_2_g256(.AN (add_23_2_n_17), .B (add_23_2_n_60), .Y
       (add_23_2_n_63));
  NOR2X1 add_23_2_g259(.A (add_23_2_n_53), .B (add_23_2_n_58), .Y
       (add_23_2_n_62));
  NOR2BX1 add_23_2_g260(.AN (add_23_2_n_39), .B (add_23_2_n_56), .Y
       (add_23_2_n_61));
  NOR2X1 add_23_2_g261(.A (add_23_2_n_22), .B (add_23_2_n_56), .Y
       (add_23_2_n_60));
  NOR2X2 add_23_2_g262(.A (add_23_2_n_49), .B (add_23_2_n_56), .Y
       (add_23_2_n_59));
  NOR2X1 add_23_2_g263(.A (add_23_2_n_48), .B (add_23_2_n_56), .Y
       (add_23_2_n_58));
  NOR2BX1 add_23_2_g264(.AN (add_23_2_n_13), .B (add_23_2_n_55), .Y
       (add_23_2_n_57));
  NOR2X2 add_23_2_g266(.A (add_23_2_n_47), .B (add_23_2_n_54), .Y
       (add_23_2_n_56));
  NOR2X1 add_23_2_g267(.A (n_100), .B (n_96), .Y (add_23_2_n_55));
  NOR2X2 add_23_2_g268(.A (add_23_2_n_1), .B (add_23_2_n_51), .Y
       (add_23_2_n_54));
  OAI21X1 add_23_2_g269(.A0 (add_23_2_n_21), .A1 (add_23_2_n_46), .B0
       (add_23_2_n_23), .Y (add_23_2_n_53));
  OAI21X1 add_23_2_g270(.A0 (add_23_2_n_33), .A1 (add_23_2_n_46), .B0
       (add_23_2_n_45), .Y (add_23_2_n_52));
  NOR2X2 add_23_2_g271(.A (add_23_2_n_26), .B (add_23_2_n_50), .Y
       (add_23_2_n_51));
  NOR2X2 add_23_2_g273(.A (add_23_2_n_14), .B (add_23_2_n_28), .Y
       (add_23_2_n_50));
  NAND2X1 add_23_2_g275(.A (add_23_2_n_32), .B (add_23_2_n_39), .Y
       (add_23_2_n_49));
  NAND2BX1 add_23_2_g276(.AN (add_23_2_n_21), .B (add_23_2_n_39), .Y
       (add_23_2_n_48));
  OAI21X1 add_23_2_g277(.A0 (add_23_2_n_15), .A1 (add_23_2_n_13), .B0
       (add_23_2_n_29), .Y (add_23_2_n_47));
  NOR2X1 add_23_2_g279(.A (add_23_2_n_20), .B (add_23_2_n_31), .Y
       (add_23_2_n_46));
  AOI2BB1X1 add_23_2_g280(.A0N (add_23_2_n_23), .A1N (add_23_2_n_18),
       .B0 (add_23_2_n_27), .Y (add_23_2_n_45));
  INVX1 add_23_2_g281(.A (add_23_2_n_43), .Y (add_23_2_n_44));
  INVX1 add_23_2_g282(.A (add_23_2_n_41), .Y (add_23_2_n_42));
  OR2XL add_23_2_g285(.A (add_23_2_n_11), .B (add_23_2_n_19), .Y
       (add_23_2_n_38));
  NOR2X1 add_23_2_g286(.A (add_23_2_n_27), .B (add_23_2_n_18), .Y
       (add_23_2_n_43));
  NAND2BX1 add_23_2_g287(.AN (add_23_2_n_21), .B (add_23_2_n_23), .Y
       (add_23_2_n_41));
  NOR2BX1 add_23_2_g288(.AN (add_23_2_n_29), .B (n_103), .Y
       (add_23_2_n_40));
  NOR2X1 add_23_2_g289(.A (add_23_2_n_16), .B (add_23_2_n_22), .Y
       (add_23_2_n_39));
  INVX1 add_23_2_g290(.A (add_23_2_n_36), .Y (add_23_2_n_37));
  INVX1 add_23_2_g293(.A (add_23_2_n_32), .Y (add_23_2_n_33));
  NOR2X1 add_23_2_g295(.A (add_23_2_n_17), .B (add_23_2_n_16), .Y
       (add_23_2_n_31));
  NOR2X1 add_23_2_g296(.A (add_23_2_n_20), .B (add_23_2_n_16), .Y
       (add_23_2_n_36));
  NOR2X1 add_23_2_g297(.A (add_23_2_n_26), .B (add_23_2_n_28), .Y
       (add_23_2_n_30));
  NAND2X1 add_23_2_g298(.A (add_23_2_n_13), .B (n_99), .Y
       (add_23_2_n_35));
  NAND2BX1 add_23_2_g299(.AN (add_23_2_n_22), .B (add_23_2_n_17), .Y
       (add_23_2_n_34));
  NOR2X1 add_23_2_g300(.A (add_23_2_n_18), .B (add_23_2_n_21), .Y
       (add_23_2_n_32));
  NAND2X1 add_23_2_g302(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_29));
  NOR2X8 add_23_2_g303(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_28));
  AND2X1 add_23_2_g304(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_27));
  NOR2X2 add_23_2_g305(.A (add_23_2_n_12), .B (add_23_2_n_7), .Y
       (add_23_2_n_26));
  NOR2X2 add_23_2_g306(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g307(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_23));
  NOR2X1 add_23_2_g308(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_22));
  NOR2X1 add_23_2_g309(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_21));
  AND2X1 add_23_2_g311(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_20));
  NAND2X1 add_23_2_g312(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g313(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_18));
  NAND2X1 add_23_2_g314(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_17));
  NOR2X2 add_23_2_g315(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_16));
  NOR2X8 add_23_2_g316(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_15));
  NAND2X4 add_23_2_g317(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g318(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_13));
  CLKINVX2 add_23_2_g319(.A (in2[1]), .Y (add_23_2_n_12));
  INVX1 add_23_2_g320(.A (in2[10]), .Y (add_23_2_n_11));
  INVXL add_23_2_g321(.A (in2[9]), .Y (add_23_2_n_10));
  INVX1 add_23_2_g322(.A (in2[8]), .Y (add_23_2_n_9));
  INVXL add_23_2_g323(.A (in2[11]), .Y (add_23_2_n_8));
  CLKINVX2 add_23_2_g324(.A (in1[1]), .Y (add_23_2_n_7));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_14), .B (add_23_2_n_30), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g326(.AN (add_23_2_n_46), .B (add_23_2_n_61), .Y
       (add_23_2_n_5));
  XNOR2XL add_23_2_g327(.A (add_23_2_n_40), .B (add_23_2_n_57), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g328(.A (add_23_2_n_35), .B (n_95), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g329(.A (add_23_2_n_34), .B (add_23_2_n_56), .Y
       (out1[4]));
  NAND2BX1 add_23_2_g330(.AN (add_23_2_n_15), .B (n_102), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g331(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_97), .Y (n_95));
  INVXL fopt332(.A (n_97), .Y (n_96));
  INVXL fopt333(.A (add_23_2_n_51), .Y (n_97));
  INVXL fopt334(.A (n_101), .Y (n_99));
  BUFX2 fopt335(.A (n_101), .Y (n_100));
  INVXL fopt336(.A (n_102), .Y (n_101));
  CLKINVX2 fopt337(.A (add_23_2_n_24), .Y (n_102));
  BUFX2 fopt338(.A (add_23_2_n_15), .Y (n_103));
endmodule


