`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:18:40 CST (May 15 2023 01:18:40 UTC)

module Filter_Add_5Ux2U_5U_4(in2, in1, out1);
  input [4:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [4:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_3, add_23_2_n_4, add_23_2_n_5;
  XNOR2X1 add_23_2_g74(.A (in2[3]), .B (add_23_2_n_5), .Y (out1[3]));
  XNOR2X1 add_23_2_g75(.A (in2[4]), .B (add_23_2_n_4), .Y (out1[4]));
  XOR2XL add_23_2_g76(.A (in2[2]), .B (add_23_2_n_3), .Y (out1[2]));
  NAND2X1 add_23_2_g77(.A (in2[2]), .B (add_23_2_n_3), .Y
       (add_23_2_n_5));
  NAND3X1 add_23_2_g78(.A (add_23_2_n_3), .B (in2[3]), .C (in2[2]), .Y
       (add_23_2_n_4));
  ADDFX1 add_23_2_g79(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_3), .S (out1[1]));
  ADDHX1 add_23_2_g80(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


