`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:34 CST (May 15 2023 01:24:34 UTC)

module Filter_Add_11Ux8U_12U_1(in2, in1, out1);
  input [10:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [10:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_1, add_23_2_n_5, add_23_2_n_7, add_23_2_n_8,
       add_23_2_n_9, add_23_2_n_10, add_23_2_n_11, add_23_2_n_12;
  wire add_23_2_n_13, add_23_2_n_15, add_23_2_n_16, add_23_2_n_17,
       add_23_2_n_18, add_23_2_n_19, add_23_2_n_20, add_23_2_n_21;
  wire add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_25,
       add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29;
  wire add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33,
       add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37;
  wire add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41,
       add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45;
  wire add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49,
       add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53;
  wire add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57,
       add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61;
  wire add_23_2_n_62, add_23_2_n_63, add_23_2_n_65, add_23_2_n_66,
       n_92, n_94, n_95, n_96;
  wire n_98, n_99, n_100, n_101, n_102;
  MXI2XL add_23_2_g228(.A (add_23_2_n_10), .B (in2[9]), .S0
       (add_23_2_n_65), .Y (out1[9]));
  MXI2XL add_23_2_g229(.A (add_23_2_n_7), .B (in2[10]), .S0
       (add_23_2_n_66), .Y (out1[10]));
  MXI2XL add_23_2_g230(.A (in2[8]), .B (add_23_2_n_9), .S0
       (add_23_2_n_63), .Y (out1[8]));
  MXI2XL add_23_2_g231(.A (add_23_2_n_42), .B (add_23_2_n_43), .S0
       (add_23_2_n_61), .Y (out1[7]));
  MXI2XL add_23_2_g232(.A (add_23_2_n_38), .B (add_23_2_n_37), .S0
       (add_23_2_n_5), .Y (out1[6]));
  MXI2XL add_23_2_g233(.A (add_23_2_n_35), .B (add_23_2_n_36), .S0
       (add_23_2_n_62), .Y (out1[5]));
  NOR2X1 add_23_2_g234(.A (add_23_2_n_17), .B (add_23_2_n_63), .Y
       (add_23_2_n_66));
  NOR2X1 add_23_2_g235(.A (add_23_2_n_9), .B (add_23_2_n_63), .Y
       (add_23_2_n_65));
  NOR2X1 add_23_2_g236(.A (add_23_2_n_31), .B (n_92), .Y (out1[11]));
  NOR2X2 add_23_2_g237(.A (add_23_2_n_51), .B (add_23_2_n_58), .Y
       (add_23_2_n_63));
  NOR2BX1 add_23_2_g239(.AN (add_23_2_n_25), .B (add_23_2_n_59), .Y
       (add_23_2_n_62));
  NOR2X1 add_23_2_g242(.A (add_23_2_n_52), .B (add_23_2_n_57), .Y
       (add_23_2_n_61));
  NOR2BX1 add_23_2_g243(.AN (add_23_2_n_34), .B (add_23_2_n_55), .Y
       (add_23_2_n_60));
  NOR2X1 add_23_2_g244(.A (add_23_2_n_22), .B (add_23_2_n_55), .Y
       (add_23_2_n_59));
  NOR2X2 add_23_2_g245(.A (add_23_2_n_47), .B (add_23_2_n_55), .Y
       (add_23_2_n_58));
  NOR2X1 add_23_2_g246(.A (add_23_2_n_48), .B (add_23_2_n_55), .Y
       (add_23_2_n_57));
  NOR2BX1 add_23_2_g247(.AN (add_23_2_n_23), .B (add_23_2_n_54), .Y
       (add_23_2_n_56));
  NOR2X2 add_23_2_g249(.A (add_23_2_n_45), .B (add_23_2_n_53), .Y
       (add_23_2_n_55));
  NOR2X1 add_23_2_g250(.A (n_99), .B (n_95), .Y (add_23_2_n_54));
  NOR2X2 add_23_2_g251(.A (add_23_2_n_1), .B (add_23_2_n_50), .Y
       (add_23_2_n_53));
  OAI21X1 add_23_2_g252(.A0 (add_23_2_n_21), .A1 (add_23_2_n_46), .B0
       (add_23_2_n_24), .Y (add_23_2_n_52));
  OAI21X1 add_23_2_g253(.A0 (add_23_2_n_40), .A1 (add_23_2_n_46), .B0
       (add_23_2_n_44), .Y (add_23_2_n_51));
  NOR2X2 add_23_2_g254(.A (add_23_2_n_28), .B (add_23_2_n_49), .Y
       (add_23_2_n_50));
  NOR2X2 add_23_2_g256(.A (add_23_2_n_16), .B (add_23_2_n_20), .Y
       (add_23_2_n_49));
  NAND2BX1 add_23_2_g258(.AN (add_23_2_n_21), .B (add_23_2_n_34), .Y
       (add_23_2_n_48));
  NAND2X1 add_23_2_g259(.A (add_23_2_n_39), .B (add_23_2_n_34), .Y
       (add_23_2_n_47));
  NOR2X1 add_23_2_g261(.A (add_23_2_n_19), .B (add_23_2_n_30), .Y
       (add_23_2_n_46));
  OAI21X1 add_23_2_g262(.A0 (add_23_2_n_12), .A1 (add_23_2_n_23), .B0
       (add_23_2_n_18), .Y (add_23_2_n_45));
  AOI2BB1X1 add_23_2_g263(.A0N (add_23_2_n_24), .A1N (add_23_2_n_26),
       .B0 (add_23_2_n_27), .Y (add_23_2_n_44));
  INVX1 add_23_2_g264(.A (add_23_2_n_42), .Y (add_23_2_n_43));
  INVX1 add_23_2_g266(.A (add_23_2_n_39), .Y (add_23_2_n_40));
  INVX1 add_23_2_g267(.A (add_23_2_n_37), .Y (add_23_2_n_38));
  INVX1 add_23_2_g268(.A (add_23_2_n_35), .Y (add_23_2_n_36));
  NOR2X1 add_23_2_g269(.A (add_23_2_n_27), .B (add_23_2_n_26), .Y
       (add_23_2_n_42));
  NOR2BX1 add_23_2_g270(.AN (add_23_2_n_18), .B (n_102), .Y
       (add_23_2_n_41));
  NOR2X1 add_23_2_g271(.A (add_23_2_n_26), .B (add_23_2_n_21), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g272(.AN (add_23_2_n_21), .B (add_23_2_n_24), .Y
       (add_23_2_n_37));
  NOR2X1 add_23_2_g273(.A (add_23_2_n_19), .B (add_23_2_n_15), .Y
       (add_23_2_n_35));
  NOR2X1 add_23_2_g274(.A (add_23_2_n_15), .B (add_23_2_n_22), .Y
       (add_23_2_n_34));
  OR2XL add_23_2_g278(.A (add_23_2_n_7), .B (add_23_2_n_17), .Y
       (add_23_2_n_31));
  NOR2X1 add_23_2_g280(.A (add_23_2_n_25), .B (add_23_2_n_15), .Y
       (add_23_2_n_30));
  NAND2BX1 add_23_2_g281(.AN (add_23_2_n_22), .B (add_23_2_n_25), .Y
       (add_23_2_n_33));
  NOR2X1 add_23_2_g282(.A (add_23_2_n_28), .B (add_23_2_n_20), .Y
       (add_23_2_n_29));
  NAND2X1 add_23_2_g283(.A (add_23_2_n_23), .B (n_98), .Y
       (add_23_2_n_32));
  NOR2X2 add_23_2_g284(.A (add_23_2_n_8), .B (add_23_2_n_11), .Y
       (add_23_2_n_28));
  AND2X1 add_23_2_g285(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_27));
  NOR2X1 add_23_2_g286(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_26));
  NAND2X1 add_23_2_g287(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_25));
  NAND2X1 add_23_2_g288(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g289(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_23));
  NOR2X1 add_23_2_g290(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_22));
  NOR2X1 add_23_2_g291(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_21));
  NOR2X8 add_23_2_g294(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_20));
  AND2X1 add_23_2_g295(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_19));
  NAND2X1 add_23_2_g296(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_18));
  NAND2X1 add_23_2_g297(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_17));
  NAND2X4 add_23_2_g298(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_16));
  NOR2X2 add_23_2_g299(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_15));
  NOR2X2 add_23_2_g300(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_13));
  NOR2X8 add_23_2_g301(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_12));
  CLKINVX2 add_23_2_g302(.A (in1[1]), .Y (add_23_2_n_11));
  INVXL add_23_2_g303(.A (in2[9]), .Y (add_23_2_n_10));
  INVX1 add_23_2_g304(.A (in2[8]), .Y (add_23_2_n_9));
  CLKINVX2 add_23_2_g305(.A (in2[1]), .Y (add_23_2_n_8));
  INVX1 add_23_2_g307(.A (in2[10]), .Y (add_23_2_n_7));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_16), .B (add_23_2_n_29), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g308(.AN (add_23_2_n_46), .B (add_23_2_n_60), .Y
       (add_23_2_n_5));
  XNOR2XL add_23_2_g309(.A (add_23_2_n_41), .B (add_23_2_n_56), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g310(.A (add_23_2_n_33), .B (add_23_2_n_55), .Y
       (out1[4]));
  CLKXOR2X1 add_23_2_g311(.A (add_23_2_n_32), .B (n_94), .Y (out1[2]));
  NAND2BX1 add_23_2_g312(.AN (add_23_2_n_12), .B (n_101), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g313(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX2 fopt(.A (add_23_2_n_63), .Y (n_92));
  INVXL fopt314(.A (n_96), .Y (n_94));
  INVXL fopt315(.A (n_96), .Y (n_95));
  INVXL fopt316(.A (add_23_2_n_50), .Y (n_96));
  INVXL fopt317(.A (n_100), .Y (n_98));
  BUFX2 fopt318(.A (n_100), .Y (n_99));
  INVXL fopt319(.A (n_101), .Y (n_100));
  CLKINVX2 fopt320(.A (add_23_2_n_13), .Y (n_101));
  BUFX2 fopt321(.A (add_23_2_n_12), .Y (n_102));
endmodule


