`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:19 CST (May 15 2023 01:24:19 UTC)

module Filter_Add_12Ux8U_12U_4(in2, in1, out1);
  input [11:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29,
       add_23_2_n_31, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36;
  wire add_23_2_n_37, add_23_2_n_38, add_23_2_n_42, add_23_2_n_43;
  XNOR2X1 add_23_2_g227(.A (in2[11]), .B (add_23_2_n_43), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g228(.A (in2[9]), .B (add_23_2_n_38), .Y (out1[9]));
  XNOR2X1 add_23_2_g229(.A (add_23_2_n_18), .B (add_23_2_n_42), .Y
       (out1[7]));
  XNOR2X1 add_23_2_g230(.A (in2[10]), .B (add_23_2_n_37), .Y
       (out1[10]));
  NAND2BX1 add_23_2_g231(.AN (add_23_2_n_37), .B (in2[10]), .Y
       (add_23_2_n_43));
  OAI21X1 add_23_2_g232(.A0 (add_23_2_n_8), .A1 (add_23_2_n_35), .B0
       (add_23_2_n_2), .Y (add_23_2_n_42));
  XNOR2X1 add_23_2_g233(.A (in2[8]), .B (add_23_2_n_36), .Y (out1[8]));
  XNOR2X1 add_23_2_g234(.A (add_23_2_n_16), .B (add_23_2_n_35), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g235(.A (add_23_2_n_14), .B (add_23_2_n_34), .Y
       (out1[5]));
  NAND2BX1 add_23_2_g236(.AN (add_23_2_n_36), .B (in2[8]), .Y
       (add_23_2_n_38));
  NAND3BXL add_23_2_g237(.AN (add_23_2_n_36), .B (in2[9]), .C (in2[8]),
       .Y (add_23_2_n_37));
  AOI31X1 add_23_2_g238(.A0 (add_23_2_n_28), .A1 (add_23_2_n_13), .A2
       (add_23_2_n_19), .B0 (add_23_2_n_24), .Y (add_23_2_n_36));
  AOI21X1 add_23_2_g239(.A0 (add_23_2_n_19), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_20), .Y (add_23_2_n_35));
  OAI21X1 add_23_2_g240(.A0 (add_23_2_n_1), .A1 (add_23_2_n_29), .B0
       (add_23_2_n_3), .Y (add_23_2_n_34));
  XNOR2X1 add_23_2_g241(.A (add_23_2_n_17), .B (add_23_2_n_29), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g242(.A (add_23_2_n_15), .B (add_23_2_n_31), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g243(.A0N (add_23_2_n_0), .A1N (add_23_2_n_26),
       .B0 (add_23_2_n_7), .Y (add_23_2_n_31));
  XNOR2X1 add_23_2_g244(.A (add_23_2_n_12), .B (add_23_2_n_26), .Y
       (out1[2]));
  INVX1 add_23_2_g245(.A (add_23_2_n_28), .Y (add_23_2_n_29));
  OAI211X1 add_23_2_g246(.A0 (add_23_2_n_7), .A1 (add_23_2_n_10), .B0
       (add_23_2_n_27), .C0 (add_23_2_n_5), .Y (add_23_2_n_28));
  NAND3BXL add_23_2_g247(.AN (add_23_2_n_10), .B (add_23_2_n_26), .C
       (add_23_2_n_0), .Y (add_23_2_n_27));
  ADDFX1 add_23_2_g248(.A (add_23_2_n_21), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_26), .S (out1[1]));
  OAI211X1 add_23_2_g249(.A0 (add_23_2_n_2), .A1 (add_23_2_n_9), .B0
       (add_23_2_n_23), .C0 (add_23_2_n_4), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g250(.A (add_23_2_n_13), .B (add_23_2_n_20), .Y
       (add_23_2_n_23));
  ADDHX1 add_23_2_g251(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_21),
       .S (out1[0]));
  OAI21X1 add_23_2_g252(.A0 (add_23_2_n_3), .A1 (add_23_2_n_6), .B0
       (add_23_2_n_11), .Y (add_23_2_n_20));
  NOR2X1 add_23_2_g253(.A (add_23_2_n_6), .B (add_23_2_n_1), .Y
       (add_23_2_n_19));
  NAND2BX1 add_23_2_g254(.AN (add_23_2_n_9), .B (add_23_2_n_4), .Y
       (add_23_2_n_18));
  NOR2BX1 add_23_2_g255(.AN (add_23_2_n_3), .B (add_23_2_n_1), .Y
       (add_23_2_n_17));
  NOR2BX1 add_23_2_g256(.AN (add_23_2_n_2), .B (add_23_2_n_8), .Y
       (add_23_2_n_16));
  NAND2BX1 add_23_2_g257(.AN (add_23_2_n_10), .B (add_23_2_n_5), .Y
       (add_23_2_n_15));
  NAND2BX1 add_23_2_g258(.AN (add_23_2_n_6), .B (add_23_2_n_11), .Y
       (add_23_2_n_14));
  NOR2X1 add_23_2_g259(.A (add_23_2_n_9), .B (add_23_2_n_8), .Y
       (add_23_2_n_13));
  NAND2X1 add_23_2_g260(.A (add_23_2_n_7), .B (add_23_2_n_0), .Y
       (add_23_2_n_12));
  NAND2X1 add_23_2_g261(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_11));
  NOR2X1 add_23_2_g262(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g263(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_9));
  NOR2X1 add_23_2_g264(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g265(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g266(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g267(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g268(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g269(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g270(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g271(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_1));
  OR2X1 add_23_2_g272(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_0));
endmodule


