`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:19:18 CST (May 15 2023 01:19:18 UTC)

module Filter_Mul_2Ux2U_4U_1(in2, in1, out1);
  input [1:0] in2, in1;
  output [3:0] out1;
  wire [1:0] in2, in1;
  wire [3:0] out1;
  wire mul_22_8_n_2, mul_22_8_n_3, mul_22_8_n_4, mul_22_8_n_5,
       mul_22_8_n_6, n_13;
  NOR3X1 mul_22_8_g88(.A (mul_22_8_n_3), .B (mul_22_8_n_2), .C
       (mul_22_8_n_4), .Y (out1[3]));
  NOR2BX1 mul_22_8_g89(.AN (mul_22_8_n_5), .B (n_13), .Y (out1[1]));
  NOR2X4 mul_22_8_g90(.A (mul_22_8_n_2), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_6));
  NAND2X1 mul_22_8_g91(.A (mul_22_8_n_2), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_5));
  NAND2X6 mul_22_8_g92(.A (in1[1]), .B (in2[0]), .Y (mul_22_8_n_4));
  NAND2X2 mul_22_8_g94(.A (in1[1]), .B (in2[1]), .Y (mul_22_8_n_3));
  NAND2X8 mul_22_8_g95(.A (in1[0]), .B (in2[1]), .Y (mul_22_8_n_2));
  XNOR2XL mul_22_8_g2(.A (mul_22_8_n_3), .B (mul_22_8_n_6), .Y
       (out1[2]));
  AND2XL mul_22_8_g99(.A (in1[0]), .B (in2[0]), .Y (out1[0]));
  BUFX2 fopt(.A (mul_22_8_n_6), .Y (n_13));
endmodule


