`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:23 CST (May 15 2023 01:24:23 UTC)

module Filter_Add_9Ux8U_10U_4(in2, in1, out1);
  input [8:0] in2;
  input [7:0] in1;
  output [9:0] out1;
  wire [8:0] in2;
  wire [7:0] in1;
  wire [9:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29,
       add_23_2_n_31, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36;
  wire add_23_2_n_41;
  XNOR2X1 add_23_2_g177(.A (add_23_2_n_13), .B (add_23_2_n_41), .Y
       (out1[7]));
  OAI21X1 add_23_2_g178(.A0 (add_23_2_n_8), .A1 (add_23_2_n_34), .B0
       (add_23_2_n_0), .Y (add_23_2_n_41));
  XNOR2X1 add_23_2_g179(.A (in2[8]), .B (add_23_2_n_36), .Y (out1[8]));
  XNOR2X1 add_23_2_g180(.A (add_23_2_n_18), .B (add_23_2_n_35), .Y
       (out1[5]));
  XNOR2X1 add_23_2_g181(.A (add_23_2_n_19), .B (add_23_2_n_34), .Y
       (out1[6]));
  NOR2BX1 add_23_2_g182(.AN (in2[8]), .B (add_23_2_n_36), .Y (out1[9]));
  AOI31X1 add_23_2_g183(.A0 (add_23_2_n_28), .A1 (add_23_2_n_12), .A2
       (add_23_2_n_14), .B0 (add_23_2_n_24), .Y (add_23_2_n_36));
  OAI21X1 add_23_2_g184(.A0 (add_23_2_n_6), .A1 (add_23_2_n_29), .B0
       (add_23_2_n_4), .Y (add_23_2_n_35));
  AOI21X1 add_23_2_g185(.A0 (add_23_2_n_14), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_20), .Y (add_23_2_n_34));
  XNOR2X1 add_23_2_g186(.A (add_23_2_n_16), .B (add_23_2_n_29), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g187(.A (add_23_2_n_17), .B (add_23_2_n_31), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g188(.A0N (add_23_2_n_1), .A1N (add_23_2_n_26),
       .B0 (add_23_2_n_9), .Y (add_23_2_n_31));
  XNOR2X1 add_23_2_g189(.A (add_23_2_n_15), .B (add_23_2_n_26), .Y
       (out1[2]));
  INVX1 add_23_2_g190(.A (add_23_2_n_28), .Y (add_23_2_n_29));
  OAI211X1 add_23_2_g191(.A0 (add_23_2_n_9), .A1 (add_23_2_n_7), .B0
       (add_23_2_n_27), .C0 (add_23_2_n_10), .Y (add_23_2_n_28));
  NAND3BXL add_23_2_g192(.AN (add_23_2_n_7), .B (add_23_2_n_26), .C
       (add_23_2_n_1), .Y (add_23_2_n_27));
  ADDFX1 add_23_2_g193(.A (add_23_2_n_21), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_26), .S (out1[1]));
  OAI211X1 add_23_2_g194(.A0 (add_23_2_n_0), .A1 (add_23_2_n_2), .B0
       (add_23_2_n_23), .C0 (add_23_2_n_5), .Y (add_23_2_n_24));
  NAND2XL add_23_2_g195(.A (add_23_2_n_12), .B (add_23_2_n_20), .Y
       (add_23_2_n_23));
  ADDHX1 add_23_2_g196(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_21),
       .S (out1[0]));
  OAI21X1 add_23_2_g197(.A0 (add_23_2_n_4), .A1 (add_23_2_n_3), .B0
       (add_23_2_n_11), .Y (add_23_2_n_20));
  NOR2BX1 add_23_2_g198(.AN (add_23_2_n_0), .B (add_23_2_n_8), .Y
       (add_23_2_n_19));
  NAND2BX1 add_23_2_g199(.AN (add_23_2_n_3), .B (add_23_2_n_11), .Y
       (add_23_2_n_18));
  NAND2BX1 add_23_2_g200(.AN (add_23_2_n_7), .B (add_23_2_n_10), .Y
       (add_23_2_n_17));
  NOR2BX1 add_23_2_g201(.AN (add_23_2_n_4), .B (add_23_2_n_6), .Y
       (add_23_2_n_16));
  NAND2X1 add_23_2_g202(.A (add_23_2_n_9), .B (add_23_2_n_1), .Y
       (add_23_2_n_15));
  NOR2X1 add_23_2_g203(.A (add_23_2_n_3), .B (add_23_2_n_6), .Y
       (add_23_2_n_14));
  NAND2BX1 add_23_2_g204(.AN (add_23_2_n_2), .B (add_23_2_n_5), .Y
       (add_23_2_n_13));
  NOR2X1 add_23_2_g205(.A (add_23_2_n_2), .B (add_23_2_n_8), .Y
       (add_23_2_n_12));
  NAND2X1 add_23_2_g206(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g207(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g208(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_9));
  NOR2X1 add_23_2_g209(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_8));
  NOR2X1 add_23_2_g210(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g211(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g212(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g213(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g214(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_3));
  NOR2X1 add_23_2_g215(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_2));
  OR2XL add_23_2_g216(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g217(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_0));
endmodule


