`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 09:24:19 CST (May 15 2023 01:24:19 UTC)

module Filter_Add_11Ux9U_12U_4(in2, in1, out1);
  input [10:0] in2;
  input [8:0] in1;
  output [11:0] out1;
  wire [10:0] in2;
  wire [8:0] in1;
  wire [11:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33;
  wire add_23_2_n_35, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40,
       add_23_2_n_41, add_23_2_n_45, add_23_2_n_46;
  ADDHX1 add_23_2_g216(.A (in2[10]), .B (add_23_2_n_41), .CO
       (out1[11]), .S (out1[10]));
  XNOR2X1 add_23_2_g217(.A (add_23_2_n_17), .B (add_23_2_n_45), .Y
       (out1[7]));
  XOR2XL add_23_2_g218(.A (in2[9]), .B (add_23_2_n_46), .Y (out1[9]));
  OAI21X1 add_23_2_g219(.A0 (add_23_2_n_8), .A1 (add_23_2_n_40), .B0
       (add_23_2_n_5), .Y (add_23_2_n_46));
  OAI21X1 add_23_2_g220(.A0 (add_23_2_n_1), .A1 (add_23_2_n_39), .B0
       (add_23_2_n_10), .Y (add_23_2_n_45));
  XNOR2X1 add_23_2_g221(.A (add_23_2_n_22), .B (add_23_2_n_40), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g222(.A (add_23_2_n_23), .B (add_23_2_n_39), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g223(.A (add_23_2_n_19), .B (add_23_2_n_38), .Y
       (out1[5]));
  OAI32X1 add_23_2_g224(.A0 (add_23_2_n_40), .A1 (add_23_2_n_0), .A2
       (add_23_2_n_8), .B0 (add_23_2_n_0), .B1 (add_23_2_n_5), .Y
       (add_23_2_n_41));
  AOI31X1 add_23_2_g225(.A0 (add_23_2_n_32), .A1 (add_23_2_n_16), .A2
       (add_23_2_n_21), .B0 (add_23_2_n_28), .Y (add_23_2_n_40));
  AOI21X1 add_23_2_g226(.A0 (add_23_2_n_21), .A1 (add_23_2_n_32), .B0
       (add_23_2_n_24), .Y (add_23_2_n_39));
  OAI21X1 add_23_2_g227(.A0 (add_23_2_n_11), .A1 (add_23_2_n_33), .B0
       (add_23_2_n_2), .Y (add_23_2_n_38));
  XNOR2X1 add_23_2_g228(.A (add_23_2_n_18), .B (add_23_2_n_33), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g229(.A (add_23_2_n_20), .B (add_23_2_n_35), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g230(.A0N (add_23_2_n_12), .A1N (add_23_2_n_30),
       .B0 (add_23_2_n_3), .Y (add_23_2_n_35));
  XNOR2X1 add_23_2_g231(.A (add_23_2_n_15), .B (add_23_2_n_30), .Y
       (out1[2]));
  INVX1 add_23_2_g232(.A (add_23_2_n_32), .Y (add_23_2_n_33));
  OAI211X1 add_23_2_g233(.A0 (add_23_2_n_3), .A1 (add_23_2_n_9), .B0
       (add_23_2_n_31), .C0 (add_23_2_n_6), .Y (add_23_2_n_32));
  NAND3BXL add_23_2_g234(.AN (add_23_2_n_9), .B (add_23_2_n_30), .C
       (add_23_2_n_12), .Y (add_23_2_n_31));
  ADDFX1 add_23_2_g235(.A (add_23_2_n_25), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_30), .S (out1[1]));
  OAI211X1 add_23_2_g236(.A0 (add_23_2_n_10), .A1 (add_23_2_n_4), .B0
       (add_23_2_n_27), .C0 (add_23_2_n_14), .Y (add_23_2_n_28));
  NAND2XL add_23_2_g237(.A (add_23_2_n_16), .B (add_23_2_n_24), .Y
       (add_23_2_n_27));
  ADDHX1 add_23_2_g238(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_25),
       .S (out1[0]));
  OAI21X1 add_23_2_g239(.A0 (add_23_2_n_2), .A1 (add_23_2_n_13), .B0
       (add_23_2_n_7), .Y (add_23_2_n_24));
  NOR2BX1 add_23_2_g240(.AN (add_23_2_n_10), .B (add_23_2_n_1), .Y
       (add_23_2_n_23));
  NOR2BX1 add_23_2_g241(.AN (add_23_2_n_5), .B (add_23_2_n_8), .Y
       (add_23_2_n_22));
  NOR2X1 add_23_2_g242(.A (add_23_2_n_13), .B (add_23_2_n_11), .Y
       (add_23_2_n_21));
  NAND2BX1 add_23_2_g243(.AN (add_23_2_n_9), .B (add_23_2_n_6), .Y
       (add_23_2_n_20));
  NAND2BX1 add_23_2_g244(.AN (add_23_2_n_13), .B (add_23_2_n_7), .Y
       (add_23_2_n_19));
  NOR2BX1 add_23_2_g245(.AN (add_23_2_n_2), .B (add_23_2_n_11), .Y
       (add_23_2_n_18));
  NAND2BX1 add_23_2_g246(.AN (add_23_2_n_4), .B (add_23_2_n_14), .Y
       (add_23_2_n_17));
  NOR2X1 add_23_2_g247(.A (add_23_2_n_4), .B (add_23_2_n_1), .Y
       (add_23_2_n_16));
  NAND2X1 add_23_2_g248(.A (add_23_2_n_3), .B (add_23_2_n_12), .Y
       (add_23_2_n_15));
  NAND2X1 add_23_2_g249(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_14));
  NOR2X1 add_23_2_g250(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_13));
  OR2X1 add_23_2_g251(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_12));
  NOR2X1 add_23_2_g252(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g253(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g254(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_9));
  NOR2X1 add_23_2_g255(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g256(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g257(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g258(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g259(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g260(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g261(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g262(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_1));
  INVX1 add_23_2_g263(.A (in2[9]), .Y (add_23_2_n_0));
endmodule


